### ISSUE TITLE
As a program lead, I can understand how I might hire digital talent

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#10]
## Problem Statement

Hiring managers who are looking to hire digital talent do not have clarity on:

- guidance on how to structure organizations with digital talent on different kinds of teams
- job profiles they can use for the right roles
- who else has experience hiring digital talent (including e-lists)
- how to assess digital talent in the competition process

This is causing:

- inefficiency in hiring digital talent
- inconsistency for applicants
- inconsistency and confusion for existing employees in digital positions

## Desired Outcome

- Realize more efficiency, effectiveness, and consistency in hiring digital talent
- Attract, retain and develop digital talent 
- Build resilient organizations with high performing teams

## Hypothesis

- If we provide guidance on organization development to support application of digital principles, methods and mindset, then leaders and hiring managers will be able to take steps to build more resilient organizations capable of building and sustaining quality digital services.

**Comment by HeatherRemacle** [comment]
##Problem Statement

Public servants who are looking to hire digital talent need:

- guidance on how to structure organizations with digital talent on different kinds of teams
- job profiles they can use for the right roles
- to connect with others who are trying to hire digital talent for mentorship and to share tools

This is causing:
 a) inefficiency in hiring digital talent
 b) inconsistency for applicants
 c) inconsistency and confusion for existing employees in digital positions

## Desired Outcome
- Realize more efficiency, effectiveness, and consistency in hiring digital talent
- Attract, retain and develop digital talent 
- Build resilient organizations with high performing teams

**Comment by Dianadec** [comment]
Need to show how to build talent:
- link to job store
- link to Dea's talent webinars
- link to digital marketplace
- link to learning resources page (link to bcdevexchange.org)

**Comment by mark-a-wilson** [comment]
Stale Epic. Added "Content about Hiring Digital Talent" to feature wish list on MIRO Roadmap board (linked here).
