### ISSUE TITLE
As a website visitor, I can learn about the latest updates and what the dev team is learning

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#100]
## Acceptance Criteria
- There is a blog on the website that communicates the release notes for the Digital.gov.bc.ca
- We want to be cool like a video game designers
- Explore and decide on UI
- Implement Notify - https://notification.alpha.canada.ca/features

**Comment by HeatherRemacle** [comment]
Hey team. I love the latest Discord update. Here it is - for a sample of what we might do in our blog:

### A message from our founders, Jason & Stan
Video games are about people. They have the power to bring together people from different walks of life from different parts of the world. They help create memories filled with laughter, nostalgia, frustration, achievement, and togetherness.

That’s why we originally created Discord: we wanted a simple and easy way to capture these feelings we experienced growing up gaming with friends.

**More than gaming**
But, over the past year, we’ve been asking you what really makes the magic of Discord. It turns out that, for a lot of you, it wasn’t just about video games anymore.

Games are what brought many of you to Discord, and we'll always be grateful for that. As time passed, a lot of you said you simply wanted a place designed to hang out and talk in the comfort of your own communities and friends.

You came to us and said Discord was this place, that it felt like home. That you’re here sharing thoughts about books, music, and art, creating servers to just be yourself and share moments with friends.

**Making Discord your place to talk**
In listening to your feedback, we heard that you want Discord to be more welcoming, more inclusive, and more trustworthy. As you’ve used Discord for more than gaming, our branding didn’t keep up, and the way we talked about ourselves made it harder for you to bring your broader community onto Discord.

Today, we want to show you some of what we’ve been working on as a start:

**We’re launching a new website with a new tagline: Your place to talk.**

- We’ve streamlined the new user onboarding experience and added server video and server templates, so it’s easier than ever to bring friends to your Discord home.
- We’ve fixed hundreds of bugs, and we’ve cleaned up the more obscure gaming references within the app to make it more welcoming, while still making sure not to take ourselves too seriously.
- We launched a Safety Center so everyone can understand our rules and the tools at your disposal to protect yourself from content or interactions you don’t want.
- And as always, we’re committed to making reliability and performance our top priority. We’ve increased our voice & video capacity by 200% and are now investing more than ever into keeping Discord at the quality you expect.

**Thank you**

We deeply thank all of you for supporting us to get where we are. We’re thrilled to be able to take the magic of online games and bring it to the rest of the world: the power to create belonging. This is what Stan and I were doing when we were teenagers sitting at home playing games, and it’s why we created Discord.

And we’re excited to work with you to continue to improve Discord. As always, let us know your thoughts and suggestions by hitting us up on Twitter at @Discord, @jasoncitron and @svishnevskiy.

Jason & Stan

**Comment by mark-a-wilson** [comment]
Closing this Epic to redefine at a later time .... have added the feature idea to the MIRO Roadmap board and linked to this Issue.
