### ISSUE TITLE
Make "Digital Marketplace" item more prominent in list of menu items 

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#1002]
We know from web analytics that a vast majority of users who hit digital.gov.bc.ca are simply trying to get to digital.gov.bc.ca/marketplace. We want to make sure that users who land on the homepage can quickly see their path to Marketplace.

We previously were using an external link icon next to the Marketplace link in the nav menu - to indicate to users that they would be going to a separate, standalone website/application. In an accessibility audit from GDX, we were told that the icon should not be used because the user still stays within the same domain (digital.gov.bc.ca) (see #902). Despite this, we think that adding the icon back in will make the link more noticeable for users which is a good thing.

Further, we have recently hosted the standalone Digital Trust WP site at digital.gov.bc.ca/digital-trust, but we have not linked to/featured that product anywhere on our pages. 

**Acceptance Criteria**
1. Add Digital Trust to nav menu as the 2nd last item, linked to digital.gov.bc.ca/digital-trust 
2. Add the external link icon to both the Digital Trust and Digital Marketplace nav items.

**Comment by mark-a-wilson** [comment]
![marketplace](https://user-images.githubusercontent.com/16946297/151263682-a4d0512f-6447-445e-bc10-20a3ed36b583.gif)
