### ISSUE TITLE
[CONTENT] Case Studies Page

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#101]
Target audience: BCPS employee

Desired outcome: understand how digital approaches get results and see what other programs are applying these practices to they can make connections to learn more

#### Acceptance Criteria

- Show the case studies that currently exist on the site and add one new one
- Include the case studies that already exist on the site
- Provide a short description of what someone will find on this page

**Comment by mark-a-wilson** [comment]
Content for two existing case studies can be scraped from here:
- [Helping farmers understand their soil](https://digital.gov.bc.ca/2019/09/20/helping-farmers-understand-their-soil/)
- [Transforming the Medical Services Plan](https://digital.gov.bc.ca/2019/09/20/transforming-the-medical-services-plan/)

Content for new case study can be found here:
- [Mines Digital Service](https://docs.google.com/document/d/1AqiM380Ln9g9-gf1-bTYWjPexpQyUoL6/edit#)

Proposed tagline for the top of the page (short description of what someone will find here):
"Learn how digital approaches are getting results here in British Columbia."

**Comment by mark-a-wilson** [comment]
Closing this Issue per my [suggested changes to content approval process](https://github.com/bcgov/digital.gov.bc.ca/issues/82#issuecomment-651270433)
