### ISSUE TITLE
Add new "Communities" Page Card for "Human-Centered Design Community"

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#1010]
Client request from Martha Edwards to add a new card to the "Communities" webpage.

This card would be for the "Human-Centered Design Community".

**Comment by bdolor** [comment]
- what are the roles/access controls for new communities?
- what is the process/documentation for onboarding new users?

**Comment by bdolor** [comment]
- role created in test and prod database, permissions added, user registration link sent off.
