### ISSUE TITLE
Case studies page (Design)

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#102]
This page should feel like a book store. What enticing story might a user read? Also like a book store, we should be able to categorize or signal what kind of experience a user will get from picking up a story to read.

Acceptance Criteria:

- Show the case studies that currently exist
- Feature one case study (with introductory text) that encourages the user to click and read
- Each story should have an image

**Comment by mark-a-wilson** [comment]
@singhinderdeep 

Content (with exceptions noted below) ready for you to create wireframes:

Content for two existing case studies can be scraped from here:
- [Helping farmers understand their soil](https://digital.gov.bc.ca/2019/09/20/helping-farmers-understand-their-soil/)
- [Transforming the Medical Services Plan](https://digital.gov.bc.ca/2019/09/20/transforming-the-medical-services-plan/)

Content for new case study can be found here:
- [Mines Digital Service](https://docs.google.com/document/d/1AqiM380Ln9g9-gf1-bTYWjPexpQyUoL6/edit#)

Proposed tagline for the top of the page (short description of what someone will find here):
"Learn how digital approaches are getting results here in British Columbia."

Only things that should be missing for you (I will upload these to the [Case Studies folder](https://drive.google.com/drive/u/2/folders/1fHtCsznXrQOy7_N3AhQGEKUIdyzDsm_3) as soon as I get them):
- Headshot for Jillian
- Feature image or two for Mines Digital Service case study

**Comment by mark-a-wilson** [comment]
Hey @singhinderdeep - I've noticed a couple of unresolved things in the wireframe. Will make comments in Figma.

**Comment by singhinderdeep** [comment]
Incorporated Mark's comments and closing this one after Mark's go ahead.
