### ISSUE TITLE
As a BCPS Employee, I understand the expectations for and ways to work in the open

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#109]
Acceptance Criteria

- Reference Digital Principles
- Link to stories that convey people's experience working in the open
- Describe the benefits of working in the open
- Example: the various ways GitHub is being used to work in the open
- Link to Information Management Policies

**Comment by mark-a-wilson** [comment]
Closing this stale epic. Have copied this feature idea to the MIRO Roadmap board. Can recreate when necessary.
