### ISSUE TITLE
Send DRAFT PIA to our privacy officer

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#110]

**Comment by HeatherRemacle** [comment]
We'll work with our Privacy Officer to complete a PIA for the product. We don't anticipate any significant impacts.

**Comment by HeatherRemacle** [comment]
Attach GDX analytics PIA?

**Comment by mark-a-wilson** [comment]
I will create a first draft baed on the PIA we finished for the new BCDevExchange website.

**Comment by mark-a-wilson** [comment]
Emailed Roxanna Deaghan [this first draft of PIA](https://teams.microsoft.com/l/file/672722D8-C303-40C4-8574-E1720216FFAF?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F00109-digital.gov.bc.ca%2FShared%20Documents%2Fdigital.gov.bc.ca%2FPIA%2FPIA_digital.gov.bc.ca_MW%20Draft.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F00109-digital.gov.bc.ca&serviceName=teams&threadId=19:f78c23767e214080840d1b7e37bd91d7@thread.tacv2&groupId=f56865b7-57f7-419c-903d-0611fc8b3b54).

**Comment by mark-a-wilson** [comment]
Rather than leave this in 'Blocked' until our privacy officer gets back to us, marking this as Closed as we have done our initial first part. 

As new tasks arise related to getting a signed PIA, we can add them to the Backlog.
