### ISSUE TITLE
First draft of STRA

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#111]
Things that will need an STRA:

- strapi and local auth
- digital.gov.bc.ca front end

**Comment by HeatherRemacle** [comment]
Let's get the document drafted with the information we can. 

DoD is that we have circled the parts that we need to do more work or research on, but the basic info should be completed.

**Comment by HeatherRemacle** [comment]
@Dianadec realizing that this is an Epic that will span sprints... so makes sense to estimate the tickets. I think there might be a process step contemplated here... which includes identifying which EPICs are user stories we can get done in a sprint (the goal every time), and some which will just required a longer slog. 

Maybe there could be a label for the multi-sprint EPICs, enabling us to then estimate those tickets within?

**Comment by Dianadec** [comment]
@HeatherRemacle Is there a way to categorize items as a User Story on ZenHub? That way, we only use the EPICS label for the larger pieces of work?

**Comment by patricksimonian** [comment]
@Dianadec i'm going to have a chat with Nick in regards to setting the stra process

**Comment by Dianadec** [comment]
A STRA can be initiated by emailing SecurityandPrivacy.Citz@gov.bc.ca with the following information:
•	Business Owner: First and Last Name 
•	Who's completing the STRA: First and Last Name 
•	Name of the project or information system to be assessed 
•	Brief Description of project or system
They could provide insight into whether a STRA is necessary, the requirements of the STRA, and how to get started. A STRA can require more “technical” knowledge, so I’d advise getting assistance if you’re not familiar with assessing IT risks and security.

**Comment by Dianadec** [comment]
@HeatherRemacle since this is already inside the Epic "Tech Excellence: Security...", I'm not clear as to whether you would like this card also turned into an epic, or if you want this estimated as a ticket.

Update: I send the email above to securityandprivacy.citz@gov.bc.ca yesterday to initiate the stra process.

**Comment by Dianadec** [comment]
From: CITZ Security and Privacy CITZ:EX <SecurityandPrivacy.Citz@gov.bc.ca> 
Sent: June 25, 2020 8:56 AM
To: De Cotiis, Diana CITZ:EX <Diana.DeCotiis@gov.bc.ca>
Subject: RE: STRA - digital.gov.bc.ca

Hi Diana.

Thank you for the STRA request.  Due to current STRA workload, it will take us two weeks to review and schedule this STRA.  We will provide you a update by Friday, July 10.  If you have any questions or are working under a tight deadline, please contact Garry Mierzuak (CITZ MISO) directly. 

Thank you,


Ariadne

**Comment by patricksimonian** [comment]
strapi docs: https://github.com/bcgov/digital.gov.bc.ca/blob/develop/docs/strapi-startup.md
react docs: https://github.com/bcgov/digital.gov.bc.ca/blob/develop/docs/react-startup.md

**Comment by Dianadec** [comment]
[https://app.zenhub.com/files/223664506/fa882d8e-14f4-4cfb-b68b-807e2425fa4d/download](https://app.zenhub.com/files/223664506/fa882d8e-14f4-4cfb-b68b-807e2425fa4d/download)

@HeatherRemacle and I will be filling this out

**Comment by Dianadec** [comment]
Questionnarie is in progress. We need the team to look at the details before submitting. We will also contact Nick from Platform team to ask for input.

**Comment by Dianadec** [comment]
@patricksimonian @thegentlemanphysicist @ryleyw @parulmishra After chatting with Nick, he identified a few things needed to add. I'm hoping I can get your help with filling in the section under Vulnerability Assessment about sonarqube/CC for the pipeline. The file is here (Exchange Lab > digital.gov.bc.ca > Files > Privacy > questionnaire doc )

For the privacy document, the other piece he said would be "about how we manage logs (i.e. are they reviewed, are they retained for the appropriate records mgmt guidelines somewhere off platform - as OCP only keeps logs for ~7 days)". Nick also suggested that ZAP be investigated next sprint and that some other teams have implemented already.

CC @HeatherRemacle

**Comment by Dianadec** [comment]
@HeatherRemacle - Patrick helped finish the questionnaire so it is here for your review prior to submitting it back to Ari: (Exchange Lab > digital.gov.bc.ca > Files > Privacy > questionnaire doc )

**Comment by mark-a-wilson** [comment]
Patrick has done initial penetration test (results good) and has completed the doc. Will send to our MISO.
