### ISSUE TITLE
Cloud early adopter program

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#115]
There is work underway to enable BC Public Service teams to use secure commercial private cloud options for hosting their applications. As this comes to fruition, we will need to inform and support teams that might benefit from this service.

The use of this service will be guided by the hosting and application development framework (HADF), and is part of that EPIC of work.

Note that the service is only available to a select few as of the fall 2020, so that the program can be built effectively.

The action that others, who are not actively participating in the pilot, can take is to participate in a client reference group. This will enable them to be aware of the real time learning, and then be ready when the program is available broadly.

We need to contemplate the existing secure cloud content on the web.

# Acceptance Criteria (TBC)

- [ ] A dedicated web page linked from Products and Services that describes the requirements and pre-conditions for participating in the program
- [ ] There is a way to contact the program (Cloud inbox)
- [ ] There is a link from HADF
- [ ] There is a way to discern the capacity of the program, or the current ability to engage with it (intake window?)
- [ ] An update about the new program is communicated through the Digital.gov release notes blog (TBC)

**Comment by mark-a-wilson** [comment]
Stale task. Have added Epic #225 — Content about Application Hosting — to the MIRO Roadmap board as a potential feature.
