### ISSUE TITLE
How to connect with the Digital Delivery Network (Community)

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#118]
## User Stories
- As a digital delivery team member, I can connect to the community of people working on digital products
- As someone interested in building my digital capabilities, I can connect to relevant communities of practice

## Context

This page should help visitors feel welcome to engage with the **digital delivery network.** People who are at all stages of learning and contributing should know what channels and groups they can engage in to achieve a variety of outcomes, including:

- understanding government direction and advancements on digital approaches
- learning digital competencies, such as data literacy, DevOps, scrum master practices, etc.
- discovering digital delivery teams and how to connect with them to receive insights about business capabilities they are building or technical capabilities and components they have experience with that they can share (sharing is part of our way of working!)
- Contributing their experience, products, code or efforts to improve the products, services, standards and content that the digital delivery network is building to enable broader change and adoption

Note that we have a variety of channels in different digital spaces with varying levels of access.. so  we will nee to make this current state obvious (i.e. @work groups are only accessible internally)

We may include broader ecosystem connections as well, including GCCollab - hosted by the Federal government.

Let's make sure the images and the feel of the page illustrates a warm welcome :)

## Acceptance Criteria (TBD)

- [ ] Meet with key community convenors to test early content and design prototypes
- [ ] Apply research findings to designs/technical considerations (add tickets to backlog)
- [ ] Build page(s)

**Comment by HeatherRemacle** [comment]
@singhinderdeep Can you please create a ticket or two for content and design on this? There is a content page, but I'm having trouble accessing it from my work computer right now... 

cc @mark-a-wilson

**Comment by Dianadec** [comment]
Need to create a dev ticket.

**Comment by mark-a-wilson** [comment]
Closing this Epic and will recompose later.
