### ISSUE TITLE
Illustrate high level roadmap

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#12]
## Problem

Where are we going? What kinds of things will we solve for in the short term and the long term?

## Outcomes

- The team is oriented around high level goals and an order of events
- Executive understand and can endorse the work of the team
- Alliance team members and stakeholders can see what value is in it for them, and when and how they might contribute

**Comment by Dianadec** [comment]
Also found this example from range, @HeatherRemacle https://miro.com/app/board/o9J_kzhjVKg=/?moveToWidget=3074457346030271451
