### ISSUE TITLE
Setup DNS routing from digital.gov.bc.ca to Openshift

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/digital.gov.bc.ca#121]
I actually have no clue how to start this process. I do know that this is an istore order. @lukegonis has done this process for developer.gov.bc.ca so I'll pick his brain on it. 

My assumptions for acceptance criteria is that:

- Accessing digital.gov.bc.ca takes you to the openshift app

**Comment by parulmishra** [comment]
The iStore request has been placed for the new SSL certificate for https://digital.gov.bc.ca/
Ticket info here: https://imbsd.gov.bc.ca/Ticket/54692

**Comment by HeatherRemacle** [comment]
Next step is to go live!
