### ISSUE TITLE
I can find who can help me achieve my digital delivery goals

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#132]
We are hearing from users that they need to know who they can connect with to get specific support to deliver a service. In some cases they know what they need, but cannot find the help. In other cases, they may not know what they need, or how to apply the new digital principles so that they take an improved approach over their previous experience.

The "resources" and "products and services" pages are meant to provide some of these insights, but do not adequately meet the users needs.

We are going to examine some new designs and languags that will enable users to:

- Discover who can help them achieve a goal
- Know what is required of them to access help (e.g. paid or not)

**Comment by mark-a-wilson** [comment]
This needs to be defined a lot more. This idea will come up in future crafting of features.
