### ISSUE TITLE
Code out the collaboration tools page

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/digital.gov.bc.ca#137]
#### Description of Task 

- Creating a new react page for the collaboration tools. Here is the og version https://digital.gov.bc.ca/communication-platforms/#

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- reference content from https://digital.gov.bc.ca/communication-platforms/#
- styling based on design system needs to be applied

#### Definition of Done

- [ ] All tests (unit/functional/security/code cov.) pass
- [x] Code review has been done
- [x] Pipeline builds
- [ ] PO signs off on the build

**Comment by thegentlemanphysicist** [comment]
It is a static page so there isn't any logic to test at the moment.

**Comment by thegentlemanphysicist** [comment]
change url,
add title to the page
