### ISSUE TITLE
As an author of a standard or practice, I can publish related content on Digital.gov.bc.ca

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#140]
Standards and guides for delivering excellent digital services should be:

- accessible and easy to find
- relevant and current
- linked to other content that might support understanding how  and when to apply it (e.g. case studies, agile development journey)

**For user research:**
The Digital.gov.bc.ca website may include content authoring capabilities, such that non-technical talent (subject matter experts) will be able to create and update basic content about standards and guides. This will require:

- Administrative access to the publishing platform
- An ability to author/draft basic content (text, images, video, files) within a particular content construct (template)
- An ability to place content in a "ready to publish" state
- An ability for a site owner to modify and publish content
- An ability to "tag" content with topics or categories that can be referenced elsewhere

Otherwise, the content may reside elsewhere and be linked to

**Comment by mark-a-wilson** [comment]
Stale epic. Have expressed this feature idea as "Owners of a Standard or Practice can publish their own content" and added it to the feature wishlist on the MIRO Roadmap board (linked here).
