### ISSUE TITLE
Code a playbook to clean up any artifacts from dev instances of PR deploys

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/digital.gov.bc.ca#148]
#### Description of Task 

- The workflow for getting code into production leaves artifacts in dev that need to be cleaned up. 
- Create a playbook to clean up the dev artifacts

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- All artifacts for a react deployment are deleted in the dev namespace

#### Definition of Done

- [ ] Code review has been done

**Comment by bdolor** [comment]
closing. By all accounts, it's done. https://github.com/bcgov/digital.gov.bc.ca/blob/develop/ansible/clean_up_react_deployment.yaml
