### ISSUE TITLE
Decide on website tech stack

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#15]
### Problem

The current website is hosted on Wordpress and does not support the breadth of development we are considering for this product roadmap.

The user research indicates that we will be publishing content regularly, and will be broadening the content producers beyond our development team. As such, a content management system (CMS) is being considered.

We need to evaluate reasonable options and decide which stack to start developing in.

### Acceptance Criteria

- Confirm assumptions that the current BCGov website, hosted on CMSlite does not meet user needs, stakeholder expectations, and future potential integrations and functions (e.g. dynamic content)
- Engage Gov 4.0 team for their experience and views
- Consider Opensource, headless CMS options that fit the BCDevExchange Guidance for low risk tech option evaluation
- Engage Exchange Lab community of developer talent for their experience and views
- Consider other jurisdictions' websites, particularly Canada's Digital Service and New South Wales, particularly regarding dynamic features such as dashboards.

**Comment by HeatherRemacle** [comment]
Team, you may want to break this down into multiple issues based on my acceptance criteria :)

**Comment by patricksimonian** [comment]
I'll make  a seperate github issue for engaging with the gov 4.0 and cmslite team

**Comment by HeatherRemacle** [comment]
For Parul to consider prior to marking done (ensure team is happy with tech stack).

**Comment by thegentlemanphysicist** [comment]
Parul says it's okay!
