### ISSUE TITLE
grid and alignment

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#151]
@singhinderdeep , @ryleyw , @thegentlemanphysicist — let's talk 🤓

In terms of responsive grid, we'd like to realize something like [Bootstrap](https://getbootstrap.com/docs/4.5/layout/grid/#grid-options).

Independent of this, specifically for **paragraphs**, for better readability, we'd like a `max-width: 960px`, still left aligned. This will mean in some cases on larger displays that there is much more white space on the right than the left.

**Comment by thegentlemanphysicist** [comment]
The grid on the products and services page should be working now


https://digital-gov-frontend-pr-197-xdwiwd-dev.pathfinder.gov.bc.ca/products-services
