### ISSUE TITLE
Card Sort for Info Architecture

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#16]
We have a draft information architecture that was put together by the PO and a few key stakeholders. We want to improve on or validate this.

We also want to prioritize the content so that we can build the backlog.

https://www.usability.gov/how-to-and-tools/methods/card-sorting.html 

### Acceptance Criteria
- Include the Alliance Team
- Document the results for ongoing reference

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - The description says "We have a draft information architecture" — what is that referring to?

**Comment by mark-a-wilson** [comment]
To use [OptimalSort](https://www.optimalworkshop.com/optimalsort/), we're limited to **30 cards** on a free account, or we'll have to pay $200 US for a month for 1 login.  

I found another free tool called [Proven By Users](https://www.provenbyusers.com) which may allow more cards on the free plan.

**Comment by singhinderdeep** [comment]
Will need the exact website content before working on the IA

**Comment by mark-a-wilson** [comment]
Yes, Heather confirmed today that [this](https://miro.com/app/board/o9J_kunzlMY=/?moveToWidget=3074457347341532704&cot=13) is what she was referring to, and I think we all agreed that it's more the source for the core content we'll create than it is an "information architecture."

**Comment by mark-a-wilson** [comment]
An IA exercise is likely in our future, but this is a stale task.
