### ISSUE TITLE
Decide on Storybook CSS Framework Implementation

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#165]
Discuss the viability and value of adding Storybook to our CSS stack.  Is the value added to the project worth the tech debt of new team members learning another tool?

**Comment by thegentlemanphysicist** [comment]
@patricksimonian Thoughts

**Comment by HeatherRemacle** [comment]
We've decided to move forward with this tool at this time.  IF the sight is on a path to growing quickly, we may revisit.
