### ISSUE TITLE
Definition of Ready

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#17]
As a team, we can claim that a ticket is ready, so that we can get to work.

Some elements to consider including:
- There are no outstanding questions stopping the team from getting started.
- Performance criteria are defined where necessary.
- Dependencies are considered.
- Person who will accept the user story (test the product) is identified (usually the PO)

### References
https://www.scruminc.com/definition-of-ready/

### Acceptance Criteria

- The team has discussed the importance of ready
- The team discusses and agrees on the definition (shares experience of when this does and does not work)
- The definition is documented for reference
- Included in  Issue template

**Comment by Dianadec** [comment]
To include in DOR: Feature has been estimated
