### ISSUE TITLE
Case Study- Css fix

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#173]
Need to fix the css as per @mark-a-wilson comments for the PR https://github.com/bcgov/digital.gov.bc.ca/pull/162
https://drive.google.com/file/d/1huq4pcKhxb1WNEA1z2_A_pGDP8S6hsI5/view?usp=sharing

**Comment by mark-a-wilson** [comment]
Per #171, this looks good now on desktop. Can close this issue.
