### ISSUE TITLE
Definition of done

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#18]
### Acceptance Criteria
- team needs to define done
- document for all to reference

https://www.scrum.org/resources/blog/done-understanding-definition-done

**Comment by Dianadec** [comment]
Perhaps this documentation can be added to MS Teams channel digital.gov.bc.ca > Documentation & Links

**Comment by thegentlemanphysicist** [comment]
On coding tickets I would recommend 'done' as the software is successfully merged into dev branch.
This means that 

1. All tests pass.
2. Code review has been done.
3. Pipeline builds
4. PO signs off on the build

Any thoughts @patricksimonian and @parulmishra ?

**Comment by mark-a-wilson** [comment]
@Dianadec

For team discussion/agreement/clarity - I've created [a spot on our How We Work MIRO board](https://miro.com/app/board/o9J_kt888P4=/?moveToWidget=3074457347976477472&cot=13) where we can all discuss and finalize.

We will need multiple DODs .... there will be different types of tasks that each require their own DOD. 

If we can finalize them [on MIRO](https://miro.com/app/board/o9J_kt888P4=/?moveToWidget=3074457347976477472&cot=13), we can then make an Issue Template for each type ( @patricksimonian is probably a pro at that). Then, when we go to create a new Issue/task, we can select the type of task it is and the appropriate DOD will auto-populate in the description.

**Comment by patricksimonian** [comment]
@thegentlemanphysicist 

Depending on how we choose to do the workflow of the application, ie feature based releases with flags, vs schedules released. I think PO sign off can become a bottle neck. Especially on small issues  like UI/UX fixes and bugs. I'm totally down for evolving the DOD as the team becomes more experiences working together.

**Comment by Dianadec** [comment]
https://miro.com/app/board/o9J_kt888P4=/?moveToWidget=3074457347976477472&cot=13

This has also been documented in MS Teams > digital.gov.bc.ca > "Documentation & Links"


Definition of Done: (updates & comments regarding DOD are here: https://miro.com/app/board/o9J_kt888P4=/?moveToWidget=3074457347976477472&cot=13)
Code:
- All tests (unit/functional/security/code cov.) pass.
- Code review has been done.
- Pipeline builds.
- PO signs off on the build
Content:
- A content template has been completed on Google Drive.
- Content has been reviewed by a third person (team member or not) who was not involved in the writing.
- Link to Content Template is shared in the Issue
- Product Owner has been tagged in the ticket to review/approve (if net new content)
