### ISSUE TITLE
CSS Bug: Mobile Responsiveness has extra whitespacing on smaller screen widths

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/digital.gov.bc.ca#182]
#### Description of Task 

- Adjust CSS to fix the white spacing

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- CSS behaves on smaller screens

#### Definition of Done

- [ ] Code review has been done
- [ ] Pipeline builds

![Screen Shot 2020-07-22 at 10.04.17 AM.png](https://images.zenhubusercontent.com/5c2e50794feb4829c0135179/0273fd4b-7fb6-4efe-9d0b-42b9c0e8b72c)

**Comment by mark-a-wilson** [comment]
Obsolete now. Spacing is much better with design in its current state.
