### ISSUE TITLE
Communities Page - Content

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#183]
#### Audience (_Who is this content for?_)
BCPS Employees

#### Desired outcome (_What do we want this content to help the reader understand or do?_):
A visitor to this page should feel welcome to engage with the digital delivery network and know what all groups/channels are available for them to engage in.

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- Should mention all the groups/channels available and how to engage with them.
- Should mention the events/learning programs to enable them to build their capabilities.

#### Definition of Done

- [x] [Content template](https://docs.google.com/document/d/1a79sMDxUlwfYkDcUoUrLsFkCpiiapDhF1H333aFrdD0/edit) completed in Google Drive 
- [ ] Content has been reviewed by someone other than the writer(s) (another team member, or a government employee outside our team) 
- [ ] Content has been approved for publication by Product Owner

**Comment by Dianadec** [comment]
Heather's Recommendation: Look at @work groups such as digital gov, Behavioural Insights Group (BIG), etc. Also ask Ari to help with that research.

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - please see content draft for this.

In particular, let me know what you think about: 

1. excluding Learning/Courses/Events from this page 
2. presenting these in an alphabetical accordion vs. traditional long page of content with cards 

cc. @singhinderdeep
