### ISSUE TITLE
Communities Page Design

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#184]
#### Description of Task
Design the communities page 

#### Definition of Done

- [ ] Design has been checked with BC design standards from the Design System
- [ ] Design has been peer reviewed
- [ ] Design has been approved by PO

**Comment by mark-a-wilson** [comment]
@singhinderdeep: 

We're good to go with the alphabetical accordion design for the content for this page. 

To save time, perhaps your wireframe could simply show one of the headings with the accordion expanded, and all the rest closed?

For the header/banner background image, you could try [this photo](https://drive.google.com/file/d/1AcME05QVrqbqRaZaW31UJjyGonCf-iA6/view?usp=sharing)?

**Comment by singhinderdeep** [comment]
Incorporated Heather's comments and closing this as per her sign-off in Figma
