### ISSUE TITLE
Implement Code Climate

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#185]
The team has recently learned from the community that https://codeclimate.com/blog/launching-today-security-monitor-by-code-climate/ is an effective way to implement secure code. We're considering other options such as sonar cube as well.

"Security Monitor regularly scans your Rails apps and lets your team know as soon as new potential vulnerabilities are found. It keeps your app and data safe by catching common security issues code before they reach production."

https://docs.codeclimate.com/docs/getting-started-with-code-climate

**Comment by Dianadec** [comment]
Document findings in github: CC vs Sonarqube
