### ISSUE TITLE
Go Live / Release 1

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#187]
#### Value / Outcome / Why are we doing this?
We (and others) have been waiting a long time for us to go live with the new site! 

#### Acceptance Criteria
- [x] Our product is live at digital.gov.bc.ca! 🍾🥳

**Comment by HeatherRemacle** [comment]
@thegentlemanphysicist @parulmishra to create tickets for this

**Comment by mark-a-wilson** [comment]
I believe this EPIC could be superseded by #299?

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist -- you did it! Thanks for all of your work to get us over this hurdle. Finally closing this one. 💪🎉
