### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#189]
#### Description of Task
Design the blog page

#### Definition of Done

- [ ] Design has been checked with BC design standards from the Design System
- [ ] Design has been peer reviewed
- [ ] Design has been approved by PO

**Comment by HeatherRemacle** [comment]
@singhinderdeep I've made comments for you to consider now. Looking great!

Can you confirm the other check boxes in the definition of done have been met for this ticket?
