### ISSUE TITLE
Add Digital Marketplace link to WP digital.gov site

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#19]
Prior to launching the Digital.gov site, we need to make the link to the marketplace visible on WP.

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist - I'd suggest we just try to achieve this:

![marketplace-link.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/4d84fdfa-573a-439a-bf97-2bc7510b21ac)

**Comment by HeatherRemacle** [comment]
Agree

Heather Remacle

A/Director of Delivery
BCDevExchange at the Exchange Lab (Formerly the CSI Lab)
Mobile: 250 208-6049
Sign up for our Newsletter<http://eepurl.com/gCpvVP>

**Comment by mark-a-wilson** [comment]
OK, I don't think the above (having the new nav item link straight to **/marketplace**) is achievable through the WordPress CMS. The only way to create a new item in the nav is to create a new page and define its order (5). 

Going to try that now.

**Comment by HeatherRemacle** [comment]
Maybe that page has a few lines of text announcing the marketplace and describing that it is now distinct from the BCDevExchange.

I wonder too about clarifying what the marketplace is in comparison to other functions that tend to confuse people… BCBid and Procurement Concierge. Thoughts?


Heather Remacle

A/Director of Delivery
BCDevExchange at the Exchange Lab (Formerly the CSI Lab)
Mobile: 250 208-6049
Sign up for our Newsletter<http://eepurl.com/gCpvVP>

**Comment by mark-a-wilson** [comment]
As discussed, over to you @thegentlemanphysicist.

**Comment by thegentlemanphysicist** [comment]
Donzo, with the external link embeded

**Comment by HeatherRemacle** [comment]
Meets notional definition of done:

1.	All tests pass.
2.	Code review has been done.
3.	Pipeline builds
4.	PO signs off on the build
