### ISSUE TITLE
fixed height cards cause problems

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#192]
Cards are currently using a fixed height which causes problems such as non-uniform spacing, hidden content, and overlapping of content as soon as windows are resized. For example: 

![fixed-height-card-2](https://user-images.githubusercontent.com/16946297/88571333-59920b00-cff2-11ea-84af-3cd34533b2de.png)

![fixed-height-card-1](https://user-images.githubusercontent.com/16946297/88571324-55fe8400-cff2-11ea-8c82-f3e49834b55a.png)

Not sure how we want to address, but our cards will need to be responsive. I'm familiar with using Bootstrap to achieve this through the use of **[card-groups](https://getbootstrap.com/docs/4.5/components/card/#card-groups)** or **[card-decks](https://getbootstrap.com/docs/4.5/components/card/#card-decks)**.  They allow you to get cards with varying amounts of content to be of the same height.

**Comment by mark-a-wilson** [comment]
Card link on Video Communication Platforms is also currently obscured (https://digital-gov-frontend-pr-199-xdwiwd-dev.pathfinder.gov.bc.ca/resources):

![Screen Shot 2020-09-04 at 10 55 34 AM](https://user-images.githubusercontent.com/16946297/92271886-6d584900-ee9d-11ea-8f8d-c9da6d4a3b76.png)

**Comment by HeatherRemacle** [comment]
@thegentlemanphysicist  to check if this is done

**Comment by mark-a-wilson** [comment]
From what I see, #315 fixes this issue.  We still have other responsiveness problems (which we'll create discreet issues for), but this particular issue—overlapping of content—seems to be fixed now.

**Comment by parulmishra** [comment]
Confirmed with @mark-a-wilson that this is already resolved with PR#315
