### ISSUE TITLE
Bug: Deploying to test and prod

### ISSUE THREAD

**Issue by Dianadec** [bcgov/digital.gov.bc.ca#200]
Ryley and Jon found they are getting an error message that says: Can't find the image tag number. (PR-[number])

**Comment by HeatherRemacle** [comment]
@ryleyw  - if you happen to get through the video tools card image bug, and want to dig into this some more, that's probably a good way to close out this sprint. 

I'd suggest reaching out the RocketChat community, in this channel: https://chat.pathfinder.gov.bc.ca/channel/devops-how-to

Ping me if you need help with this.

**Comment by HeatherRemacle** [comment]
@ryleyw  - @parulmishra has offered to help with this too if you get stuck. Might be worth working together a bit.

**Comment by ryleyw** [comment]
Seems to be working again with no change on my end, perhaps something on the openshift side of things got updated. Closing as now test and prod reflect the changes of pr 199

**Comment by ryleyw** [comment]
https://digital-gov-frontend-prod-xdwiwd-prod.pathfinder.gov.bc.ca/
