### ISSUE TITLE
Code the Communities Page

### ISSUE THREAD

**Issue by Dianadec** [bcgov/digital.gov.bc.ca#206]
#### Description of Task 

- Code the communities page as a static react page

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- Applies the designs 
- Loads properly
- URL matches site structure (site map on the Roadmap) - sits at top of structure

#### Definition of Done

- [ ] All tests (unit/functional/security/code cov/accessibility) pass
- [ ] Code review has been done
- [ ] Pipeline builds
- [ ] PO signs off on the build

**Comment by mark-a-wilson** [comment]
Closing this Epic and will recompose later.
