### ISSUE TITLE
Create the content model for a basic static page

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#207]
#### Description of Task 

This proves out the function of Strapi and React front end running together, prior to going to prod.

- Designer and developer will work together to create the content model for the basic page (Communities)
- Developer will create the content model and onboard the team to using it.
- Code deploys to Dev

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- Document the process for creating the content model
- Enable the team to generate a page

#### Definition of Done

- [ ] All tests (unit/functional/security/code cov.) pass
- [ ] Code review has been done
- [ ] Pipeline builds
- [ ] PO signs off on the build

**Comment by HeatherRemacle** [comment]
This ticket is being shrunk to focus on making Strapi function. @thegentlemanphysicist and @parulmishra are working on creating tickets for going to prod inclusive of database persistence.

**Comment by thegentlemanphysicist** [comment]
https://digital-gov-frontend-pr-305-xdwiwd-dev.pathfinder.gov.bc.ca/guides
This will be where the guides page shows up, I just need to deploy strapi to dev as well before you can try out making a guide
