### ISSUE TITLE
establish max-width for paragraphs

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#211]
To make sections with a lot of copy (e.g. Case Study pages, Products & Services page, Digital Framework page) more readable, I suggest we implement something like `p { max-width: 960px }`

Take queue from the  Digital Principles and fix:
- Products and services
- Digital Framework
- Case Studies (all three)

**Comment by HeatherRemacle** [comment]
@mark-a-wilson ... apologies - did we agree to close this one? I think it is addressed via other tickets.

**Comment by mark-a-wilson** [comment]
Yes, think this is looking OK currently. I will keep an eye on paragraph width when #359 is being done. I think we can close this Issue.
