### ISSUE TITLE
Spacing between sections on Digital framework page is awkward, text too wide

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#215]
![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/21f6a02b-9dbb-471f-94ea-a6903d3fa1f2)

The sections have inconsistent spacing and the content is too wide across the page. Please mimic the existing site spacing.

https://digital.gov.bc.ca/digital-transformation/

**Comment by ryleyw** [comment]
https://digital-gov-frontend-pr-199-xdwiwd-dev.pathfinder.gov.bc.ca/

**Comment by HeatherRemacle** [comment]
This still isn't looking right. Here is what I see:

![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/1f895d77-c9b8-48fe-a754-dc60f0fb43e9)
![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/baf69021-4988-46da-a728-f6883dce9f3a)

@singhinderdeep  @ryleyw

**Comment by HeatherRemacle** [comment]
Hey @ryleyw - my old eyes can't find the latest deployment link... any chance you can post it here? (I don't see a PR with this ticket number on it)
