### ISSUE TITLE
Draft some new headlines for the homepage - for team discussion

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#22]
### User story

As a visitor to digital.gov.bc.ca, I want to be able to quickly understand what this site is and what I can expect to find or do here.

The current headline on the homepage is very rhetorical:

![headline.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/29a207f4-4e22-43df-9887-e08941f41f72)

I'd suggest we change it into a statement about what the site is and what people can do here. 

### Acceptance Criteria

- [ ] Product owner is satisfied that the headline accurately summarizes what the digital.gov.bc.ca site is / what users can expect from it

### Definition of Done

- [x] At least two homepage headlines are mocked up in a wireframe and posted on the [Prototypes MIRO board](https://miro.com/app/board/o9J_kslEIZ4=/?moveToWidget=3074457347957445766&cot=13)

**Comment by mark-a-wilson** [comment]
https://miro.com/app/board/o9J_kslEIZ4=/?moveToWidget=3074457347957445766&cot=13

**Comment by mark-a-wilson** [comment]
I have posted a few headlines [here](https://miro.com/app/board/o9J_kslEIZ4=/?moveToWidget=3074457347957445766&cot=13) on the Prototypes MIRO board.

**Comment by HeatherRemacle** [comment]
Hey @mark-a-wilson - I have commented on those. Thanks for drafting! Let me know if my comments resonate with your user research and plain language approach. https://miro.com/app/board/o9J_kslEIZ4=/?moveToWidget=3074457347957487359&cot=13

**Comment by HeatherRemacle** [comment]
I think we have a winner: Learn how the Government of British Columbia is building teams and using modern technology to deliver better services.
