### ISSUE TITLE
COVID-19 Digital Response Unit Link incorrect

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#224]
This content on the products and services page  is incorrect, given that we do not yet have a DRU page ready to publish.
![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/d110192b-2b60-46a6-9bd2-2e9c06c52409)

Please update text to read: 

If you are facing an urgent service delivery challenge due to COVID-19, connect with the Digital Response Unit through the [Exchange Lab](mailto:exchangelab@gov.bc.ca), a community of digital experts who are working together to address urgent challenges.

**Comment by SoLetsCode** [comment]
This is Derek, I can take this issue on and will follow the contributing guidelines.

**Comment by ryleyw** [comment]
https://digital-gov-frontend-pr-199-xdwiwd-dev.pathfinder.gov.bc.ca/
