### ISSUE TITLE
Application Hosting

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#225]
## User Stories:

- As a Product Owner, I can can make informed decisions about the hosting and application development approach my team should take to solve a service delivery problem

## Context

This Epic includes referencing any part of the Hosting and Application Development Framework that might provide definitive orientation, and specifically:

- When and how to use public cloud
- When and how to use the  Kamloops hosted cloud (pathfinder platform)
- When to use traditional infrastructure

**Comment by mark-a-wilson** [comment]
Stale task. Have added this Epic — Content about Application Hosting — to the MIRO Roadmap board as a potential feature.
