### ISSUE TITLE
Provide skip navigation link on each page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#240]
Reference: [WCAG 2.4.1 - Bypass Blocks](https://www.w3.org/TR/WCAG21/#bypass-blocks)

### The Problem

To meet this standard, we need to provide keyboard and screen reader users a way to bypass the blocks of content that are repeated on all pages (e.g. the header, nav, breadcrumb), that come before the main content of the page. 

This is usually referred to as "skip navigation".

### For Discussion
[This article](https://webaim.org/techniques/skipnav/) discusses different techniques for achieving skip navigation. It seems to me that the recommended/most promising technique is to provide a skip navigation link on each page and make it invisible (see [this article on Invisible Content Just for Screen Reader Users](https://webaim.org/techniques/css/invisiblecontent/)).

### Acceptance Criteria
When landing on a page, users using keyboard navigation or a screen reader are presented with a link directly after the site logo in the header that enables them to bypass the nav menu and skip directly to the main content of the page (the `<h1>`). 

Can we try to achieve as close to what is done on gov.bc.ca as possible? (The link becomes visible when using a screen reader tool.) 

![skip-to-main-content](https://user-images.githubusercontent.com/16946297/94717295-fc257d80-0304-11eb-9fb1-2035aa4e67ff.png)

- [ ] Link text should read "Skip to main content" (`<a>Skip to main content</a>`)
- [ ] Link should use same CSS styles as on gov.bc.ca
- [ ] Link is invisible to sighted users, but becomes visible using keyboard navigation/screen reader by virtue of `:focus`. How gov.bc.ca achieves this is:

```
<div id="access">
   <a>Skip to main content</a>
</div>

#access a {
   margin: 5px 0 0 -5000px;
   width: 120px;
   padding: 5px;
   position: absolute;
   top: 0;
   color: #fcba19;
}

#access a:focus {
  margin-left: 0;
}

```

- [ ] For screen reader users, the link presents directly after the site brand (British Columbia logo + "Digital Government")
- [ ] Link takes the user to the `<h1>` on the page

### Definition of Done
- [ ] All tests (unit/functional/security/code cov.) pass
- [ ] Code review has been done
- [ ] Pipeline builds
- [ ] PO signs off on the build

**Comment by thegentlemanphysicist** [comment]
https://digital-gov-frontend-pr-348-xdwiwd-dev.pathfinder.gov.bc.ca/
