### ISSUE TITLE
Remove alt text from card images

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#241]
Reference: [WCAG 1.1.1 - Non-text Content](https://www.w3.org/TR/WCAG21/#non-text-content)

### The Problem
The images on the Community and Case Studies cards on the homepage (and there are probably more card images across the site) contain `alt="example"'. When a keyboard / screen reader user comes across this image, the screen reader says, "example image". 

Per the standard, images that are decorative only (i.e. the image is not necessary to convey content—the cards have a title) should use null alt text (`alt=""`). 

### Acceptance Criteria
All alt text on card images **across all pages** have been replaced with `alt=""`. 

### Definition of Done
- [ ] All tests (unit/functional/security/code cov.) pass
- [ ] Code review has been done
- [ ] Pipeline builds
- [x] PO signs off on the build

**Comment by thegentlemanphysicist** [comment]
The change is implemented on the following branch
https://digital-gov-frontend-pr-296-xdwiwd-dev.pathfinder.gov.bc.ca/case-studies

**Comment by nmathava** [comment]
Blocked due to ticket number 298. Occasional help needed from Patrick
