### ISSUE TITLE
Tech spike: Strapi

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#25]
Headless CMS backend under consideration.

Acceptance criteria

- can it be integrated with keycloak (question to be answered)
- can it be integrated with HA postgres or HA Mongodb  (question to be answered)
- can a dev get strapi running (demo)
- the dev should demonstrate publishing something on strapi

**Comment by thegentlemanphysicist** [comment]
Answer to Mongo:  yes, mongo can be attactched as a database

**Comment by HeatherRemacle** [comment]
Note that headless CMS implementation is new to the BCPS (as far as we are aware - there isn't a project on Openshift that uses headless CMS).

The team is doing more outreach in the community to see what other learning has been done. This might be a pathfinder initiative.

**Comment by thegentlemanphysicist** [comment]
Answer to using keycloak:  yes it can be implemented see this pr
https://github.com/strapi/strapi/pull/3161
There is also a strapi example on adding new providers to the system.
