### ISSUE TITLE
Empty link detected where invisible breadcrumb would display

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#253]
When using the [WAVE evaluator tool](https://wave.webaim.org) in Safari, the tools detects an empty link in the place where the breadcrumb would display the title of the page: 

![image](https://user-images.githubusercontent.com/16946297/90835187-c7370b80-e300-11ea-8cfc-3e8006ada0ee.png)

```
<li class="listOption">
  <a href="/data"></a>
</li>
```

This is NOT detected when using the WAVE plugin in Chrome.

Investigate — may not need to do anything here.

**Comment by thegentlemanphysicist** [comment]
There is also a console error for not providing a key to the breadcrumbs elements that I will be fixing with this ticket

**Comment by thegentlemanphysicist** [comment]
Realized there was still a problem on the guides/communication-platforms pages. needs further investigation

**Comment by mark-a-wilson** [comment]
From examining [this deployment](https://digital-gov-frontend-pr-368-xdwiwd-dev.pathfinder.gov.bc.ca/) with VoiceOver on Safari, and the WAVE evaluator tool, I can confirm this Issue has been fixed by #368.
