### ISSUE TITLE
Code content about the Digital Academy

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#267]
This page is dependent on inputs from the New Digital Academy Director. 

Acceptance Criteria are pending.

**Comment by mark-a-wilson** [comment]
See #321 & #344. Following up with Derek again on Oct 22.

For discussion: 
* Do we want to "hard code" content for the Digital Academy first? Or do we want to tackle this EPIC as defined in #344 (EPIC completed when Derek can manage his own content via Strapi)?

**Comment by mark-a-wilson** [comment]
Stale task.
