### ISSUE TITLE
Implement web analytics on project

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#27]
We are deploying GDX Analytics Service. 

## Instructions: 

**Copy  the JavaScript tracker "Standalone vA.2.10.2" in the attached txt file into the head of your test/dev site. 
Don't move this to your production site as the tracker connects to our test pipeline and it could cause issues. **

- Text file is stored in MS Teams files ("Internal DevOps working files")

# AC

- [ ]  When this has been installed in your test/dev environment please let Brendan know along with the URL of the site. (There is some testing required before we can proceed with the installation process.)
- [ ] When this is complete, Brendan will send you a small update to connect the tracking script to our production pipeline. 
- [ ] Confirm the analytics are running smooth

**Comment by rumoncarter** [comment]
It would be great / ideal to deploy @danpollock & co. to this.

**Comment by danpollock** [comment]
@thegentlemanphysicist , @rumoncarter : Web analytics is already set up using the GDX Analytics service. The Service Design Team are the account holders at present.

**Comment by ryleyw** [comment]
Researching atm

**Comment by BJenning** [comment]
@HeatherRemacle, @thegentlemanphysicist, @rumoncarter: We are rolling out an important Javascript update to the tracker. In early September, Google will be releasing an update to Chrome that will enforce stricter cookie policy settings that will interfere with some aspects of Snowplow tracking. We expect other major browsers to follow soon after. (For tech details, see https://www.chromestatus.com/feature/5633521622188032) 

Ive attached a copy of the updated tracking script. The installation instructions haven't changed for the updated version. Please let me know if you have any questions or concerns.

[Snowplow_Javascript_Standalone_vE2.14.0.txt](https://github.com/bcgov/digital.gov.bc.ca/files/5031670/Snowplow_Javascript_Standalone_vE2.14.0.txt)
