### ISSUE TITLE
Extra space between the nav bar and hero section on all three case studies pages

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#271]
Please remove the extra spacing between the nav bar and hero section on all three case studies pages. 
<img width="1665" alt="Screen Shot 2020-08-27 at 1 38 26 PM" src="https://user-images.githubusercontent.com/61562375/91494045-1505c380-e86d-11ea-8041-8427f9206105.png">

**Comment by thegentlemanphysicist** [comment]
I am unable to reproduce this on my computer with current develop branch

**Comment by thegentlemanphysicist** [comment]
This was a pretty hefty refactor of the code. Despite being such a 'small' change
https://digital-gov-frontend-pr-325-xdwiwd-dev.pathfinder.gov.bc.ca/
