### ISSUE TITLE
clean up inconsistent link styles

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#279]
Reference: [WCAG 1.4.1 - Use of Color](https://www.w3.org/TR/WCAG21/#use-of-color)

### The Problem

Per the Accessibility standard above, **color** alone shouldn't be the only element to convey the difference between _linked_ and _regular_ text. This is why gov.bc.ca uses underline in addition to color.

In some cases, we have implemented the [styles for links dictated on the Design System](https://developer.gov.bc.ca/Design-System/Links#css), however in some cases we have not. 

> _**An aside:** by perusing the DevHub (even the links on the Design System Links page itself! 🤦‍♂️), you'll see there is inconsistency._

### Acceptance Criteria

The following links should all use these styles: 

```
a {
  color: #1a5a96;
  text-decoration: underline;
}

a:hover {
  text-decoration: none;
  color: blue;
}
```

- [x] Links on white cards 
- [x] Links under **Our Priorities** on the **Digital Framework** page
- [x] Inline links on the **Digital Principles** page
- [x] Standalone links (under Technical, Privacy, Security, and For Designers headings) on the **Resources** page
- [x] Linked headings under **Video Communication Options** heading on the **Video Communication Platforms** page. (**Please note also:** these headings are not picking up `font-family: 'BC Sans'`.)

Suggestion: If we can, let's do away with all the individual classes for links (e.g. `productCardLink`, `resourceLink`, etc.)

### Definition of Done
- [ ] All tests (unit/functional/security/code cov.) pass
- [ ] Code review has been done
- [ ] Pipeline builds
- [ ] PO signs off on the build

**Comment by SoLetsCode** [comment]
Hi again, I would like to take on this issue :)

**Comment by mark-a-wilson** [comment]
Thanks, @SoLetsCode. @thegentlemanphysicist , @parulmishra - could you reach out here and advise on how you'd like them to submit a PR? Or that this isn't a good time to manage an outside contribution? Thanks.

**Comment by SoLetsCode** [comment]
I've been following the contribution guidelines forking the repo -> creating a branch with issue-number -> pull request. Open to your suggestions though.

**Comment by thegentlemanphysicist** [comment]
https://digital-gov-frontend-pr-364-xdwiwd-dev.pathfinder.gov.bc.ca/
