### ISSUE TITLE
Design for updates to Digital Framework page

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#288]
Need to visit other jurisdiction websites specifically NZ one and explore some design patterns which could be used to design for any updates to the Digital Framework page.

See [Figma file](https://www.figma.com/file/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=0%3A1)

This task is dependent on #287 being complete before this can be completed.

#### Acceptance Criteria
- [x] Priority actions are displayed as cards or accordion with the title of the action
- [x] Each priority action has a label or tag: (To be started, Started, Ongoing, or Complete)
- [x] Card expands/collapses (like an accordion) to reveal/hide detailed content

**Comment by mark-a-wilson** [comment]
@singhinderdeep - please see [this comment](https://github.com/bcgov/digital.gov.bc.ca/issues/287#issuecomment-687332308)

**Comment by mark-a-wilson** [comment]
Full content for this page should be coming from Kim Fri, Sep 18.

Putting this back In Progress, as I'm going to add some of my ideas to the Figma file.

**Comment by mark-a-wilson** [comment]
Kim Zinke really likes the layout of this page: https://www.digital.govt.nz/digital-government/strategy/strategy-summary/strategy-programme-of-work/

We are incorporating ideas from it in our design.

**Comment by mark-a-wilson** [comment]
Putting this in Blocked as we will not be sure that designs have covered everything until we receive final approved content from Kim (#287). 

@HeatherRemacle - if you'd like to look at the designs, see the bottom of the [Figma file](https://www.figma.com/file/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=0%3A1) -- we think we'll probably be going with the minimal accordion design on the far right. (BTW we talked through this design with @thegentlemanphysicist and it's all doable from the Strapi perspective.)

**Comment by mark-a-wilson** [comment]
Created [this clickable mockup](https://www.figma.com/proto/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=2410%3A1282&viewport=152%2C15%2C0.015625&scaling=scale-down-width) for Danny and Kim to show our design ideas so far for the content Kim has provided.

**Comment by mark-a-wilson** [comment]
Working on additions to the clickable mockup based on new layer of "Backgrounder" content from Kim.

**Comment by mark-a-wilson** [comment]
Making a few more tweaks per Kim's request

**Comment by HeatherRemacle** [comment]
This looks REALLY fantastic! 

And... I recently read in a thread involving our GDX friends that accordions are generally NOT accessible... so my bad for suggesting we go that direction. Unless we can figure out a way around it?

Otherwise, I might suggest we go with the slightly more busy basic "card" approach that has some top level info.. i.e. the summary text, or my fav, the problem statement. We should check with Kim on her teams' preference though.

**Comment by mark-a-wilson** [comment]
Maybe this is a good opportunity for us to learn how to make an accessible accordion? 

Here are some resources I've found with a quick search: 

> [Example of use of accordion on gov.bc.ca > PharmaCare](https://www2.gov.bc.ca/gov/content/health/health-drug-coverage/pharmacare-for-bc-residents) (scroll to bottom of page)

> [Article on gov about creating web accordions in CMS Lite](https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/web-content-development-guides/cms-lite-manual/ui-guidelines/text-editor/accordions)

> [WAI-Aria example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html)

> [Article on how to make accordions accessible](http://web-accessibility.carnegiemuseums.org/code/accordions/)

**Comment by mark-a-wilson** [comment]
Gonna close this as I haven't got any more requests for changes.
