### ISSUE TITLE
Create user stories for the Government Executive / Organizational Leader persona

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#29]
### User Story

As a Designer/content creator, I need a set of user stories for the Government Executive persona so that I can understand what we are trying to enable that user to do on the website with our first release, and can begin to gather and write content to meet those goals. 

### Definition of Done

- [x] A complete set of user stories are written that capture, to the best of the assignee's knowledge, the complete suite of what the Product Owner wants to provide for this persona in our first release. 
- [x] The users stories are added to the [Value Proposition MIRO board](https://miro.com/app/board/o9J_kspTqGY=/?moveToWidget=3074457347900654295&cot=13) so that the team can see them, comment, and revise.

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - I composed the user stories based on my interpretation of the [WHY, WHAT, HOW content] (https://miro.com/app/board/o9J_kunzlMY=/?moveToWidget=3074457347341532704&cot=13) you drafted and the [Vision and Governance](https://miro.com/app/board/o9J_kytFRlg=/?moveToWidget=3074457346395604889&cot=13) frame of the INTERNAL Lab Impact Map board.

Let me know what you think, they are [here](https://miro.com/app/board/o9J_kspTqGY=/?moveToWidget=3074457347900654295&cot=13). 

Each user story that you endorse will convert nicely into a piece of content that can be sourced or written - and we'll know exactly what we're trying to achieve with it.

**Comment by HeatherRemacle** [comment]
@mark-a-wilson I have reviewed and coloured green the user stories I think we should focus on. Added one for COVID-19.
