### ISSUE TITLE
Be ready to go live with Release 1

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#299]
This overarching Epic ties together the user story Epics that include the features we expect to have available by Release 1, due the first week of October.

It also includes stray tickets that are required for us to resolve technical debt or issues that would prevent users from having a good experience on the site.

# Definition of Done for this Release:

- All existing content on the current Digital.gov.bc.ca site is included, with improvements to the user experience in terms of navigation and context setting. 
- The site passes accessibility tests, style guide, and models best practices
- Analytics are installed and working
- The pipeline for publishing code through Openshift to the platform is working (Ansible scripts are functioning)
- Automated tests to ensure code does not fail.
- Code Climate gives a passing grade for code quality
- The site passes STRA and PIA requirements
- There is sign-off by product sponsors and Digital Framework governance, such that they understand the current state of the site, and our future roadmap, before we embark on work related to Release 2.

# Not in this Release

- Functional Strapi deployment
- Process and governance for contributors of code and content
- Actioning user research from the last sprint

**Comment by mark-a-wilson** [comment]
Based on the status of the Issues attached to this Epic, this Epic is completed. (I retitled it.)
