### ISSUE TITLE
Add Team to ZenHub

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#3]
Ensure  everyone on the team has a github account in the BCGov org and add them to this team

**Comment by Dianadec** [comment]
Everyone has been added to have direct access to the repo digital.gov.bc.ca. 

DIRECT ACCESS
10 have access to this repository. 8 members. _2 outside collaborators_ (I asked @patricksimonian to grant Dea and Inderdeep access to bcgov).

Do we also need to create a TEAM? Access can be seen in github bcgov / digital.gov.bc.ca > settings > manage access

**Comment by patricksimonian** [comment]
dea and inderdeep have been invited by email :) 

As far as a github TEAM, it is not necessary for them to work. We will just need to add them as collaborators to the digital.gov repo(s)

**Comment by patricksimonian** [comment]
@Dianadec dea and inderdeep are now apart of the bcgov org, can we close this issue?
