### ISSUE TITLE
Get the digital.gov WP site archived 

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#311]
GDX team likely needs 2-3 days for a database dump for this.

**Make sure the digital marketplace link still works**
https://digital.gov.bc.ca/marketplace
And that our digital site can still navigate there

**Comment by mark-a-wilson** [comment]
Switched the EPIC that this is mapped to from #187 to #299.

**Comment by mark-a-wilson** [comment]
Removing this from the ["Turn on the site" Epic](https://github.com/bcgov/digital.gov.bc.ca/issues/109) as, to my understanding, this doesn't need to be completed in order for us to turn on the new site. Correct me if I'm wrong.

**Comment by mark-a-wilson** [comment]
Steve Howard says this about our options:

![image.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/3d0b2ca1-5bfc-48a3-8356-43cadf857b6f)

**Comment by mark-a-wilson** [comment]
Sent request to Steve Howard March 10 to archive per option 2 above.

**Comment by mark-a-wilson** [comment]
WP site is now archived at https://test.workingforyou.gov.bc.ca/digital. (You must be on VPN / BCNGN to access.)
