### ISSUE TITLE
Git Configuration

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#314]
This epic encompasses all things git.

- Managing permissions
- Configuring the checks that block merging into dev and master ( for example not allowing a merge into develop it the merging branch is not up to date.  This is currently a problem)
- Adding checks to make sure the app successfully deploys before allowing code to be merged.
- Potentially creating git hooks that trigger builds in the pipeline.  (these may also fall under the epic Pipeline MVP)
- Building docs in git, including git pages.
- Configuration of Zenhub
Duration of epic:
This epic will most likely be part of the project for it's lifetime. With a gradual fall off as the dev team hits it's stride.  As long as active development is taking place there could conceivably be tasks involved in git conguration.

**Comment by mark-a-wilson** [comment]
Closing this stale epic. Can create new bite-sized Epics (features) related to Git in future as necessary.
