### ISSUE TITLE
Actively move styling out of css to styled components card.css

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#319]
We have adopted 'styled-components' as a new css framework, however there are many css files that are still being used.

AC: 
- replace all instances of card.css with styled components
- delete the card.css file
- add 5 tests to insure code quality
- create a list of all places cards used in the site. (to assist with QA)
- have thorough QA done on all places 'cards' used in the site

**Comment by mark-a-wilson** [comment]
This should be done in concert with #320
