### ISSUE TITLE
Fix formatting issues with horizontal cards

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#320]
This is how it is
![Screen Shot 2020-09-17 at 11.19.47 AM.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/1c890bc7-3126-45f6-a888-e748dc05fc72)

This is how it should be
![VC.jpg](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/1658bdc8-5275-4016-bd6b-9ad42995a98a)

**Comment by mark-a-wilson** [comment]
This should be done in concert with #319

**Comment by mark-a-wilson** [comment]
As Inderdeep originally pointed out, we still have a few issues with horizontal image cards:

- [ ] Text wrapping and link being hidden:

![horizontal-card-text-wrapping-link-lost-1](https://user-images.githubusercontent.com/16946297/96904367-ddba2a00-144b-11eb-86cc-cc08e37634aa.png)

![horizontal-card-text-wrapping-link-lost-2](https://user-images.githubusercontent.com/16946297/96904374-e14db100-144b-11eb-8ef3-8e03153aaa9d.png)

- [ ] Font size and padding when horizontal card wraps on small displays:

![horizontal-card-font-size-and-padding](https://user-images.githubusercontent.com/16946297/96904440-fb878f00-144b-11eb-9afa-5b28b8ad0074.png)
