### ISSUE TITLE
Only trigger dev builds when PRs to develop are opened

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#324]
Currently opening a PR to any branch attempts to build a deployment in develop.  

- This is not desirable when a PR from develop to Master is opened.  
- Similarly there is a check that requires a successful deployment to develop before merging any PR.

A.C. 
- Only require a successful build on PRs to develop
- Only trigger a dev build on PRs to develop

**Comment by mark-a-wilson** [comment]
Discussed and we don't think this is necessary (for now, anyway)
