### ISSUE TITLE
Dashboard access for Web Analytics

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#326]
This is to ensure that we get the dashboard access for web analytics.

**Comment by mark-a-wilson** [comment]
@parulmishra - 

Brendan sent the access for the Dashboard. 

It's at https://intranet.qa.gov.bc.ca/analytics/digital-government, and there are limited licenses, so Heather, Inderdeep, Danny Pizarro and I have access.
