### ISSUE TITLE
Replace Homepage image, scale properly with resize

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#330]
Current Home page image does not scale on properly on very large screens.
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5e66cb541c5fcd60e21b8c1a/044f9089-433a-49a7-83cc-8c78c31b5829)

This shouldn't look like this on large screens.  Consult @singhinderdeep on desired behaviour

Also, we want to respond to feedback that people do not love the image - test a new one.

**Comment by mark-a-wilson** [comment]
This one can be closed as we have already replaced the homepage banner with Inderdeep's nice illustration.
