### ISSUE TITLE
Improve build speed of react image by refactoring the image

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#331]
Currently the build time of the react image is on the order of 30 minutes. 
This is excessively long.  Approximately half the build time involves installing Cypress on the image.  
is it possible use a different base image for the react project?  Perhaps one that already has many of the packages installed reducing the amount modules that need to be installed.
AC:
- Time current pipeline build time.
- Identify and implement one image build speed improvement.
- Improve build time by at least 10% (arbitrarily picked by jon)

**Comment by bdolor** [comment]
closing. build time has improved (< 13 mins), base image updated and production flags set for dependency installs (no cypress) in https://github.com/bcgov/digital.gov.bc.ca/pull/1032
