### ISSUE TITLE
create a 404 page for incorrect site urls

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#333]
Currently we do not handle incorrect site urls.  We should have a page for that.  I created a place holder for incorrect case study links, but it would be nice to have an official one to link to.  

See `/case-studies/fake-study`.

Dependency: #358

**Comment by thegentlemanphysicist** [comment]
@HeatherRemacle  suggested this be under the epic 'go live'

**Comment by HeatherRemacle** [comment]
The text appears to need some spacing or bullets where I have highlighted:
![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/e789cb47-36ed-444c-8db6-1fd0b25bd4b4)
