### ISSUE TITLE
Design Illustration for Digital Principles

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#336]
Design Illustration for Digital Principles

**Comment by singhinderdeep** [comment]
![Asset 2@4x.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/80cc5060-4d9a-41b8-a0d3-7920c3903182)

**Comment by HeatherRemacle** [comment]
@singhinderdeep I like this graphic, but I'm not certain it gives any reference to principles... not that it is easy to do. I think this could be adapted a bit to provide some other imagry.

Images that make me think of principles, which are useful to enable people to aspire to some better state, include:

- Stairs going up (change in some progressive direction)
- Sign posts (maybe with digital principle related icons on them)
- A brain, or thought bubbles... illustrating that the principles lead to a mindset that leads to results (could layer on thoughts in this image from the person, relating to some of the principles somehow)

For quick reference of the principles: https://github.com/bcgov/digital-principles

**Comment by singhinderdeep** [comment]
@HeatherRemacle yeah it's tricky to visually depict words like framework, principles etc. Not really sure about stairs or thought bubbles but sign post might work. But then icons for related terms might be tricky again. Will try something with the sign post and see if it works.

**Comment by singhinderdeep** [comment]
@HeatherRemacle for the sign post, do you mean just a sign post or you want a person standing next to it as well? Also, with just a sign post we might not have the reference to word Digital

**Comment by singhinderdeep** [comment]
@HeatherRemacle do you mean something like this for the sign post thing?

![Asset 4@4x.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/01a9b53f-426e-49b7-8d0e-0f08908d9f2f)

**Comment by HeatherRemacle** [comment]
Can you integrate the sign post with the original image somehow, @singhinderdeep?

**Comment by singhinderdeep** [comment]
@HeatherRemacle Does this work?

![principles.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/5f9c8769-dc59-41ae-9023-0d2aa557f332)

**Comment by singhinderdeep** [comment]
@HeatherRemacle Does this work?

![Asset 7@4x.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/237ec6bc-ffbf-4786-99c5-92424bda787e)

**Comment by HeatherRemacle** [comment]
Love it.

**Comment by singhinderdeep** [comment]
Got Heather's approval. Closing this.
