### ISSUE TITLE
Design Illustration for Resources

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#337]
Design Illustration for Resources

**Comment by singhinderdeep** [comment]
@HeatherRemacle up for your feedback

![Resources@4x.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/d30cb967-86c2-4ffd-a18d-9d6e9b022b90)

**Comment by HeatherRemacle** [comment]
Neat. I like this one. Good to go @singhinderdeep
