### ISSUE TITLE
Design Illustration for Community

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#338]
Design Illustration for Community

**Comment by singhinderdeep** [comment]
@HeatherRemacle I know you mentioned a couple of things for the community illustration, but guess having more than one ideas might complicate it. So, tried the illustration below. Have tried to include more diversified characters in the illustrations. Let me know your thoughts on this. 

![Community.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/7e68ac42-dbfd-44b0-b44b-a0af2bcbef63)

**Comment by HeatherRemacle** [comment]
Great work - moving this to done :)
