### ISSUE TITLE
Design Illustration for Case Studies

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#339]
Design Illustration for Case Studies

**Comment by singhinderdeep** [comment]
@HeatherRemacle Up for your review
![Asset 9@4x.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/c8a4a0a0-1d5d-4634-9c84-568b3b93db57)

**Comment by HeatherRemacle** [comment]
I like how excited this person is :) What if we had a magnifying glass above the file folder? I feel like this image says: "Yay, I completed something!" Which is relevant to the team we are profiling. And I think we want to signal that there is something cool to see here... do you thing a magnifying glass could work?

**Comment by singhinderdeep** [comment]
@HeatherRemacle I like how you find something positive in the illustrations to mention as the first thing in every comment :) 
Does this work?

![Asset 12@4x.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/a6c74085-f30c-4ee8-9c0c-59fd6eb99f4e)

**Comment by HeatherRemacle** [comment]
Looks great!

**Comment by singhinderdeep** [comment]
Approved by Heather. Moving to closed.
