### ISSUE TITLE
[CONTENT] Homepage

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#34]
[Content Template >](https://docs.google.com/document/d/1quyfg3RgWoR8eGBevoXAljTNce86LAKV9zXkw3eubZM/edit#) 

**Target audience** (_Who is this content for?_):  Government employee (any level/position)

**Desired outcomes** (_What do we want this content to help the reader understand or do?_): 

- Understand what “digital government” means
- Be compelled that “digital government” matters
- Be convinced that there is a call-to-action for all the Public Service here, and what that call-to-action is
- Understand who the call to action is coming from, and that their mandate is authoritative
- Understand what can be done/learned/found on this website.

#### Acceptance Criteria
- [x] Writing meets [accessibility guidelines](https://www2.gov.bc.ca/gov/content/home/accessible-government/toolkit/document-creation/writing)
- [x] Content declares what the site does that's valuable from the user's point of view
- [x] Content explains how digital.gov.bc.ca differs from other government websites
- [x] "digital government" or "digital service delivery approach" is defined somewhere
- [x] Content declares/explains why this subject matters
- [x] Content gives a call-to-action for the Public Service
- [x] Content demonstrates who the call-to-action is coming from
- [x] Content includes a teasers about **Case Studies** and **Community** 

#### Definition of Done

- [x] Content template completed in Google Drive; link included 
- [x] Content has been approved for publication by Product Owner

#### Process

* **Assignee** - In the Google Drive [Content folder](https://drive.google.com/drive/u/2/folders/1YezB6ZLpTqun9Gb8tSf3bU81vhB5MZtL), make a new document from the document called ****Content Writing Template**** (right click > Make a Copy). After 1 and 2 of DOD are complete, move Issue to the 'For PO to Review' column
* **Product Owner** - If content is approved with no revisions necessary, move Issue to the 'Closed' column. If revision required, make comments in the Google Doc and move Issue back into the 'In Progress' column, and @tag the assignee.

**Comment by mark-a-wilson** [comment]
@singhinderdeep - Could you please review my draft [here](https://drive.google.com/open?id=1quyfg3RgWoR8eGBevoXAljTNce86LAKV9zXkw3eubZM) ?

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - draft for your review [here](https://docs.google.com/document/d/1quyfg3RgWoR8eGBevoXAljTNce86LAKV9zXkw3eubZM/edit).

**Comment by HeatherRemacle** [comment]
Great work here - I've asked for one addition to the page - the reference to case studies. I think this can be a separate ticket, as well as the reference to community.

**Comment by mark-a-wilson** [comment]
Thanks for the review and direction - gonna pull this back in to In Progress to complete.

**Comment by mark-a-wilson** [comment]
Added teasers for **Community** and **Case Studies**.

**Comment by HeatherRemacle** [comment]
@mark-a-wilson I've made a few edits to the google doc and the design work by @singhinderdeep to reflect feedback from Rumon and to reduce content and duplication. Ready for a few minor edits prior to demo :)
