### ISSUE TITLE
Case Studies

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#346]
Build a library of case studies that help to illustrate how all the Digital Government resources, products and services come together to support excellent service delivery.

## Acceptance Criteria:

- We have a list of case studies that can demonstrate each of the digital principles (i.e. the case study makes explicit reference, is an exemplar, and can be tagged with a principle so that it shows up on the digital principles page and the principle can be tagged in the case study)
- Each case study is told as a story, using a format that illustrates the problem to solve, how the team decided on the approach, how/if a team was formed, any challenges they had to overcome, what results were delivered (ideally with some metrics).
- Case studies are listed on the Case studies page, which is optimized for browsing according to user research

**Comment by nmathava** [comment]
My comment

**Comment by mark-a-wilson** [comment]
Closing this stale Epic. Will redefine when the time comes.
