### ISSUE TITLE
Design Illustration for Products & Services

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#349]
Design Illustration for Products & Services

**Comment by singhinderdeep** [comment]
@HeatherRemacle how about this for Products & Services?

![Asset 13@4x.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/d61268be-b5c7-442a-be72-91ee7c5ec4b8)

**Comment by HeatherRemacle** [comment]
Yeah, I think this can work. I'd like to see what our users think of this. Let's put it in the wild.
