### ISSUE TITLE
Design 404 page UI

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#358]
Will be needed for #333.

**Comment by mark-a-wilson** [comment]
@singhinderdeep - for inspiration 🙂:
![flickr_404.jpg](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/2347b15e-0e41-44d0-9cd9-9a522d448335)

**Comment by singhinderdeep** [comment]
Inspired from NZ :) 

![404.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/0eff6690-cfa7-48b1-8115-f5a9e51ef9be)

One with illustration so hopefully will blend in better with the overall website visual theme
![405.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/9fb7f811-5cfd-41d7-a0cf-676a0f4e0628)

**Comment by mark-a-wilson** [comment]
I :heart: the second one.

**Comment by singhinderdeep** [comment]
Second that. Guess it blends well with the overall theme of the website.

**Comment by HeatherRemacle** [comment]
Haha, I like the sad 404. Design looks great. 

I wonder, @mark-a-wilson - is this page an opportunity to test your "tell us what you are looking for" field? Maybe 404 page 2.0?
