### ISSUE TITLE
Create and implement a consistent container

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#359]
### Problem
We have multiple alignment issues in different places, for example:
- BC Gov logo and nav menu move in and out of alignment with one another depending on the screen size, or "jump around" as a window is resized
- Some centered `bannerSubTitle`s still overflow the display horizontally at some screen widths (e.g. Homepage)
- Some body content rubs up against the display on the left and overflows on the right (e.g. Resources, Products & Services)  
- Fix breadcrumb spacing
This makes our site look unprofessional and should be fixed before we go live. 

### Solution
In addition to addressing these examples individually, I believe that we could/should achieve consistency in alignment by having a global `<div class="container">` element that can be used _within_ each section of the page (i.e. COVID banner; header, nav, main-content, footer) to ensure that the content of each section remains left- and right-aligned no matter the screen size.

### Acceptance Criteria
- [ ] a single **container** (name TBD) StyleComponent has been created
- [ ] The StyleComponent matches this CSS:

```
.container {
	margin-right: auto;
	margin-left: auto;
	padding: 0 15px;
	width: 100%;
}

@media screen and (min-width: 576px) {
	.container {
		max-width: 540px;
	}
}

@media screen and (min-width: 768px) {
	.container {
		max-width: 720px;
	}
}

@media screen and (min-width: 992px) {
	.container {
		max-width: 960px;
	}
}

@media screen and (min-width: 1200px) {
	.container {
		max-width: 1140px;
	}
}
```
The container StyleComponent has been inserted across all elements and pages we've created so far:
- [ ] COVID banner
- [ ] Header
- [ ] Nav
- [ ] Footer
- [ ] Home content
- [ ] Resources content
- [ ] Products & Services content
- [ ] Case Studies hub page
- [ ] Mines sase study page
- [ ] MSP case study page
- [ ] Agriculture case study page
- [ ] VIdeo Communication Platforms page
- [ ] Digital Framework page
- [ ] Digital Principles page

And
- [ ] All pages are reviewed to ensure alignment has been fixed and is consistent across pages.

Completing this Issue would also resolve #289 and #193

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist, 

In some places, we are importing and using the boilerplate `<Grid>` from **[react-flexbox-grid](https://roylee0704.github.io/react-flexbox-grid/)** (e.g. CaseStudies/cardlist.js).

Perhaps, instead of creating a custom, global container StyleComponent, we should simply ensure that the pattern of

```
<Grid>
   <Row>
      <Col>
```

is implemented within the COVID banner, the header, the nav, the main content, and the footer? 

This is the CSS for `<Grid>` (that gets rendered as `<div class="container"`):

```
@media only screen and (min-width: 576px) {
    width: 560px;
    max-width: 100%;
  }
  @media only screen and (min-width: 768px) {
    width: 752px;
    max-width: 100%;
  }
  @media only screen and (min-width: 992px) {
    width: 976px;
    max-width: 100%;
  }
  @media only screen and (min-width: 1200px) {
    width: 1184px;
    max-width: 100%;
  }
```

**Comment by HeatherRemacle** [comment]
FYI I love how much you are flexing your cross-functional coding muscle, @mark-a-wilson  :)

**Comment by mark-a-wilson** [comment]
Here's the deployment: https://digital-gov-frontend-pr-422-xdwiwd-dev.pathfinder.gov.bc.ca/products-services
