### ISSUE TITLE
Make header, nav, and body independent of COVID banner

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#360]
#### Problem

After the addition of the COVID banner, we now have some spacing problems:
* Breadcrumb is now obscured until COVID banner is dismissed:
* At certain screen widths, the position of the nav menu (when expanded) is off

As I've examined this so far, this seems to be caused because we are trying to achieve the proper spacing by defining `position:`  and `top:` for a bunch of different breakpoints instead of making (1) the COVID banner and (2) everything else independent.

I think we need to refactor so that we can eliminate the need for all of this custom `position:` styling for the header, nav, and body.

**Comment by HeatherRemacle** [comment]
@parulmishra Let me know if you want a separate ticket for this, or if it is easy to change as you are working on this ticket... I'm noticing the font for the COVID banner seems larger/more bold than the sub header in our main content. I'd like it to be smaller and/or finer.
![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/e51af06f-8dac-482e-89fe-5fae2592f353)

**Comment by mark-a-wilson** [comment]
@HeatherRemacle , @parulmishra - to Heather's comment above, I believe this won't be an issue anymore now that we have replaced the homepage banner:

![image](https://user-images.githubusercontent.com/16946297/97499364-f84c4180-192a-11eb-84e7-11dc38d5558f.png)

The reason that Heather's screenshot looks off is that we had put a style on the banner subtitle to decrease the font size at smaller screen sizes (making it then smaller than the COVID banner whose font size doesn't change.) With the styling we're using on the new banner, the subtitle stays at 19px on small screens—bigger than the 18px of the text in the COVID banner.
