### ISSUE TITLE
Install Google search console 

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#366]
Instructions from Stephanie Yurchak (who has now left GDX; our contact for this now is Ryan Janes):

> 1.	Set up a Google account for organizational use if don’t you have one already. (We can use our Lab Gsuite account)
> 2.	Sign up for Google Search Console and verify owner ship of your site [first two steps here:](https://support.google.com/webmasters/answer/9274190?hl=en)
> a.	You will want to select URL prefix property type
> 3.	Provide Restricted access rights to us, analytics.donnotreply@gov.bc.ca, within your Google Search Console.
> 
> For step 3, follow these instructions:
> •	In the navigation pane on the left hand side of the console, click on Settings;
> •	Under Property Settings in the Settings pane, click on “Users and Permissions”;
> •	At the top right hand side of the console, click on the blue “Add User” button;
> •	In the Add User panel that appears, paste the email address: analytics.donotreply@gov.bc.ca and select Permission: Restricted;
> •	Select the permission “Full” by default, and finally click “Add”;
> •	In the list of users that will appear, confirm that analytics.donotreply@gov.bc.ca appears, and the email and permission are correct.
> 
> This will give us access to load your site data from Google Search Console into Looker.
> 
> Let me know if you have any questions, or once you have completed the setup.

### Definition of Done (tasks required)
- [x] Create a Google account for Digital.Government@gov.bc.ca

🚥⚠️ The following steps won't work, I believe, until our app is running live at https://digital.gov.bc.ca:

- [ ] Log into [Google Search Console](https://search.google.com/search-console/welcome) with the Digital.Government@gov.bc.ca account (contact Mark for password) and:
    1. Add a new property for **https://digital.gov.bc.ca** using the **URL prefix** option
    2. Download the html file and upload it to the root directory; deploy to production
    3. Go back to the Google Search Console and **Finish Verification** 

- [ ] (Once verification is successful) provide Restricted Access permissions to analytics.donnotreply@gov.bc.ca per the instructions above

**Comment by HeatherRemacle** [comment]
Here is the how to: https://support.google.com/webmasters/answer/34592?hl=en&ref_topic=9268559

**Comment by mark-a-wilson** [comment]
Putting in blocked until I get admin access to Digital.Government@gov.bc.ca .... I will need that in order to create a Google account for that email address (it is not to be a personal email address; and using our G-Suite account ExchangeLab@bcdevexchange.org doesn't make sense for digital.gov.bc.ca).

**Comment by HeatherRemacle** [comment]
Let's keep this in release 1, recognizing that the sprint is notionally extended given our publishing freeze. We can officially start release 2 after the site is live and being analyzed :)

**Comment by mark-a-wilson** [comment]
With Steve Howard's help, just completed verification on the WordPress site via HTML Tag method and added GDX analytics as a User. So they should now be able to pull Google Search Console data into Looker.

We'll need to do the [verification](https://support.google.com/webmasters/answer/9008080?hl=en#zippy=) again when our product is launched.

**Comment by mark-a-wilson** [comment]
Google Search analytics are still working correctly after we have switched over to the new app. No need to do anything further here.
