### ISSUE TITLE
Refactor banner with image

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#375]
#### Current Problems:
- Position of the text with dark background changes at different screen sizes
- Aspect of image gets skewed and the image doesn't resize (becomes meaningless on smaller screens)
- Styles in **bannerWithImage.js** seem overcomplicated

I think we can make this component more responsive and simplify our code by refactoring so that `bannerWithImage` uses the `background-image` property instead of _containing_ an `<img>`.

**Comment by thegentlemanphysicist** [comment]
I noticed some merge conflicts in the PR that will hold up code review
