### ISSUE TITLE
Add Case Studies link to Navigation

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#390]
The Digital Marketplace is one of the key products that supports building teams.

It should have a link in the main navigation bar, next to products and services:
![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/2059b7cf-cd5a-48e5-884d-f4bb27c637b7)

The link should open in a new tab, as it navigates away from the main site. External link styling should be applied as well.

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - In addition to a **Marketplace** link, would you be good with adding the following to the main nav menu?

- Case Studies (we heard from research that people thought these should be emphasized more)
- Digital Framework

**Comment by mark-a-wilson** [comment]
See PR #419
