### ISSUE TITLE
Review Communities Page Design with Digital Delivery Network leads

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#397]
This should include folks that convene:
- Digital Delivery Network for COVID-19 (Rumon)
- Technology Innovation Forum (Danny)
- Data Science CoP
- Business Intelligence CoP
- Exchange Lab/Platform Services (Heather & Justin)

## Acceptance Criteria

- [ ] We have an inventory of the communities that are active, and we have clarity on what they are trying to achieve (A list and a visual map)
- [ ] We can communicate the value of each to visitors to Digital.gov.bc.ca
- [ ] There is an obvious place and way for people to connect and participate in each community that is listed

NOTE: given that there has not yet been an effort to reconcile the variety of communities, this conversation may lead to some insights that shift the operation of communities that ostensibly make up the Digital Delivery Network.

**Comment by mark-a-wilson** [comment]
So far I've turned Inder's design into **[this clickable mockup](https://www.figma.com/proto/Q4O4hvZXit7B6EPOKCEPf2/Communities-page?node-id=3%3A1494&viewport=16%252C499%252C0.015625&scaling=min-zoom)** and have sent the following request for feedback to 9 stakeholders we identified:

![Screen Shot 2020-11-13 at 1.37.38 PM.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/f7a9c2a8-c029-4d92-b950-37ab38ea1dec)

**Comment by mark-a-wilson** [comment]
I'm notating the feedback I get in **[this (protected) Google sheet](https://docs.google.com/spreadsheets/d/1OenIDij2PuBo9dHTwxE6dlOjK0d0J20SdEVymfl1q78/edit?usp=sharing)**
