### ISSUE TITLE
Spike: establish git branching and merging work flow

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#40]
- [x] Technical team has a naming convention that all agree too.

- [x]  Branch workflow:  Github workflow, pull request based, rebase based

- [x] Do we open pr's against dev?

- [x] This will be documented in the contributing.md file

**Comment by HeatherRemacle** [comment]
Perhaps this is a decent reference? https://hackernoon.com/a-branching-and-releasing-strategy-that-fits-github-flow-be1b6c48eca2 (from DevHub)

Or this: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
