### ISSUE TITLE
Wireframe Design with Team CoCo 

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#403]
### Description of Task

Develop mock-up of features based on the wireframes provided by the CoCo team.

## Acceptance Criteria

- [x] Review with CoCo designer (Lada) prior to PO review
- [x] Test with the owner of the common component illustrated in the mock-up prior to PO review
- [x] Maintain the same content width as the rest of the site
- [x] Apply the design system components where applicable

### Definition of Done
- [x] Design has been checked with BC design standards from the Design System
- [x] Design has been peer reviewed
- [x] Design has been approved by PO

**Comment by nmathava** [comment]
### Outcomes:

- [ ] Mock-up of features based on discussion with the Coco team
- [ ] Detailed illustration for the the development team on what needs to be built and to get feedback on technical feasibility 
- [ ] Executive understanding and endorsement

**Comment by mark-a-wilson** [comment]
Completed wireframes are here: https://www.figma.com/file/XPe01CLbBIUuIaUJRHGOM8/CoCo?node-id=0%3A1
