### ISSUE TITLE
Technical Review on CoCo Wireframe Design

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#404]
Determine the appropriate tech stack for the UI (consider database driven vs static options)

**Comment by nmathava** [comment]
### Acceptance Criteria:

[ ] The technical team is able to review and understand the mockup/frontend (ticket 403)
[ ] The technical team is able to able to break smaller technical tickets based on the technical feasibility

**Comment by mark-a-wilson** [comment]
This was completed via meeting on Nov 24. Wireframes were reviewed with @thegentlemanphysicist. Key decision needs to be made -- see #449.
