### ISSUE TITLE
Figure out how we will measure success of publishing CoCos

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#406]
Referring back to our Epic, the reason we are publishing some featured common components on digital.gov.bc.ca is that we have the following hypothesis:

We think that if we **feature quality common components on digital.gov.bc.ca**, with content that helps product owners assess their value/suitability, that **these components will see an increase in use**. *We’ll know we’re right when* we **track how much each featured component gets used** of a period of time and **verify whether the content on digital.gov.bc.ca played a role** in each case.

### Plan

1. For each common component that we feature on digital.gov.bc.ca, establish who is the product owner or technical lead for it 
2. Work with each lead to figure out how they can keep track of how many people use that common component and who those people are. 

3. 3 months, then 6 months, after publishing the common components, follow up with each CoCo owner to update usage numbers. Follow up with each user to determine whether the content on digital.gov.bc.ca played a role in making them aware of the component and making the decision to use it.

If it can be established that the information on digital.gov.bc.ca drives uptake of common components, then the case can be made to invest more people resources to build a fulsome catalogue.

**Comment by nmathava** [comment]
### Acceptance Criteria

[] Able to track how many people are using CoCo
[] Able to track what information is useful to people

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - See plan above. 

I'm sure we will look at Google Analytics metrics as well, but ultimately success = CoCos getting used more. 

My thinking is that measuring success for what we can take responsibility for will have to take place over many months:

- Finding product owners who are looking at the published CoCos and getting feedback on how to make the content more useful
- Working with the leads of each CoCo to track how much they are being adopted, and by whom, and what role our web content played in that
