### ISSUE TITLE
COVID banner has a light blue outline

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#409]
The COVID banner has a light blue outline even when the banner is in its default state. (i.e. this would be acceptable in `::focus` state). This is not present on the COVID banner on gov.bc.ca which is what we're trying to copy.

![COVID-banner-outline](https://user-images.githubusercontent.com/16946297/98012455-fa405580-1dad-11eb-9df1-c66f300a87f7.png)

**Comment by mark-a-wilson** [comment]
Jon is dealing with this in PR #417

**Comment by thegentlemanphysicist** [comment]
I don't see this on the my latest PR...

**Comment by thegentlemanphysicist** [comment]
https://digital-gov-frontend-pr-420-xdwiwd-dev.pathfinder.gov.bc.ca/

**Comment by mark-a-wilson** [comment]
Nor do I .. it must have been removed at some point along the way.
