### ISSUE TITLE
Add Marketplace link to navigation

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#424]
We want a link to the **Digital Marketplace** app to be added to the main navigation. (@HeatherRemacle - do you require this for **[Go Live: Release 1](https://github.com/bcgov/digital.gov.bc.ca/issues/299)**, or can it be added later?)

When we point our app at digital.gov.bc.ca, there might be some complication in being able to continue to run the Marketplace app at **digital.gov.bc.ca/marketplace**?  If so, @thegentlemanphysicist or @parulmishra -- can you please create a ticket to define what work needs to be done there?

#### Acceptance Criteria
- [ ] navbar contains a link (put it as the last item) titled **Marketplace** that goes to the Digital Marketplace application.

**Comment by thegentlemanphysicist** [comment]
https://digital-gov-frontend-pr-444-xdwiwd-dev.pathfinder.gov.bc.ca/
