### ISSUE TITLE
Implement unit testing on project

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#43]
- [x] Implement choice of unit test framework locally
- [x] Implement choice of unit test framework in the pipeline

**Comment by patricksimonian** [comment]
react-scripts utilizes jest automatically. I'd suggest using that in conjunction with @testing-library/react instead of enzyme.

**Comment by ryleyw** [comment]
Possible implementations in:

infocard.js
breadcrumbs.js
navbar.js

**Comment by ryleyw** [comment]
https://jestjs.io/docs/en/tutorial-react

Following this guide, I think it's best if we create an epic for this ticket, as there will be a lot of unit tests to make for different components, multiple tickets will help track better

**Comment by ryleyw** [comment]
Making a functional example test that tests a function before this ticket is completed
