### ISSUE TITLE
Add Hosting and Application and Development Strategy Document

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#438]
#### Value / Outcome / Why are we doing this?
The new Hosting and Application Development Strategy is an important document that people are hearing about and should be easily found on digital.gov.bc.ca.

#### Notes
- The Strategy is in PDF form — it can be found and downloaded [here on Sharepoint](https://bcgov-my.sharepoint.com/personal/mac_campbell_gov_bc_ca/Documents/Microsoft%20Teams%20Chat%20Files/Hosting%20and%20Application%20Development%20Strategy.pdf)
- Mark has already added the document to the WordPress site on the Standards and Guides page.

#### Acceptance Criteria
- [ ] A link to the HADS PDF document is added to digital.gov.bc.ca in a logical place
- [ ] The PDF is embedded in our site and the link goes to a URL that is within the digital.gov.bc.ca domain (i.e. it doesn't just send the user to the Sharepoint link above)

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist — I was going to start into submitting a PR for this, but I realized I'll need your guidance how/where to add a PDF document in the folder structure, and add a link to the PDF from a card on the Resources page.

**Comment by mark-a-wilson** [comment]
Closing this issue as the HADS document has been pulled from digital.gov.bc.ca for further approvals. Will re-identify as a need when the time comes.
