### ISSUE TITLE
HorizontalContainer's left and right padding are asymmetrical!

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#439]
For whatever historical reasons, our main page container ("`HorizontalContainer`") has some weird defined styles, and they are asymmetrical:

![Screen Shot 2020-11-19 at 4 07 01 PM](https://user-images.githubusercontent.com/16946297/99739533-d6edf980-2a81-11eb-9200-5023df13af73.png)

```
const HorizontalContainer = styled(Grid).attrs({
  className: 'horizontalAlignment',
})`
  margin: auto;
  max-width: 1065px;
  padding-left: 30px;
  padding-right: 20px;
  z-index: -2;
  @media screen and (min-width: 800px) {
    padding-left: 107px;
  }
  @media screen and (max-width: 800px) {
    padding-left: 15px;
  }
`;
```

Though the results, visually, are acceptable, it just kinda bugs me knowing these weird styles exist.

Here are the widths that some of our closest products use:

gov.bc.ca:

```
.container {
	width: 100%;
}

@media (min-width: 768px) {
	.container {
		width: 750px;
	}
}

@media (min-width: 992px) {
	.container {
		width: 970px;
	}
}

@media (min-width: 1200px) {
	.container {
		width: 1170px;
	}
}
```

Digital Marketplace:
```
.container {
	width: 100%;
}
@media (min-width: 576px) {
	.container {
		max-width: 720px;
	}
}
@media (min-width: 1100px) {
	.container {
		max-width: 960px;
	}
}
@media (min-width: 1200px) {
	.container {
		max-width: 1140px;
	}
}

```

**Comment by mark-a-wilson** [comment]
@HeatherRemacle, I have submitted #440 to address this.

Could you please compare these two deployments and let me know if you agree that PR 440 is an improvement?

1. [PR 422](https://digital-gov-frontend-pr-422-xdwiwd-dev.pathfinder.gov.bc.ca) (most recent work)
2. PR 440

**Comment by HeatherRemacle** [comment]
@mark-a-wilson I'm somewhat inclined towards the version that feels less zoomed in - which is 442. I guess I like having a bit more white space and seeing more of the content at once.

I suppose, to have the padding be equal on either side and not feel like we are zooming in, we could increase the padding on the right while also reducing on the left? Am I understanding that right?

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - thanks for reviewing. That's fine, if you're happy with the narrower display, 442, I'll just close this PR for now and we can look at making the left and right padding equal down the road if we identify it as a need.
