### ISSUE TITLE
Implement integration test framework

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#44]
We need to do some research to determine what framework to use.

- [ ] Implement choice of integration test framework locally
- [ ] Implement choice of integration test framework in the pipeline

**Comment by patricksimonian** [comment]
again integration tests can be accomplished with Jest if needed. I think theres a further discussion on the merit of testing integratioins between UI components or even utils that influence UI changes.

**Comment by nmathava** [comment]
Confirm whether we already have a test framework in place that is sufficient

**Comment by HeatherRemacle** [comment]
Cypress can handle the level of testing we need to achieve for this product. Consider this done.
