### ISSUE TITLE
Implement browser automation test framework

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#45]
- [x] Implement choice of browser automation test framework locally
- [ ] Implement choice of  browser automation test framework in the pipeline

Blocked by ticket 42

**Comment by HeatherRemacle** [comment]
@parulmishra - thanks for making great progress on this and for digging into options. Can you point me in the direction of where  you'll post your documentation and learnings? Perhaps chat with @Dianadec if you're not sure the best place to put documentation (we're still refining this).

**Comment by Dianadec** [comment]
Documenting code is best on github, whereas Miro board will link to other things we produce. So content is ideally github - export to frames. @parulmishra
