### ISSUE TITLE
Implement CoCo's home Page

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#456]
This page lists the CoCos.

![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/88cd0af5-06c8-41c3-b68b-cf1b9202a03e)

**Comment by thegentlemanphysicist** [comment]
Currently an issue in the pipeline, need to investigate locally

**Comment by thegentlemanphysicist** [comment]
Testing notes : 
The feature is live here:
https://digital-gov-frontend-pr-516-xdwiwd-dev.pathfinder.gov.bc.ca/cocos
With Strapi backend here:
https://strapi-pr-516-xdwiwd-dev.pathfinder.gov.bc.ca/admin

**Comment by thegentlemanphysicist** [comment]
Potential bug found by Nan: 
The strapi admin can delete required component fields in the coco (i.e. why should I use this).  Attempting to save the strapi state causes a server error, but no messaging to the user. To prevent this, the reset button should be disabled on this field, or a clear error should be displayed.
@thegentlemanphysicist  Will try to fix this, and failing that create a ticket for future work.

**Comment by thegentlemanphysicist** [comment]
@mark-a-wilson The one thing I realized we need to confirm is if the contact information e-mail and phone number is accurate for the coco's project

**Comment by singhinderdeep** [comment]
Before the site goes live, need to confirm if the support contact info "CommonComponents@gov.bc.ca or 250-777-7777" is genuine or just a placeholder.

**Comment by mark-a-wilson** [comment]
Decision was:
- [ ] Make the email address Digital.Government@gov.bc.ca
- [ ] Remove the phone number
