### ISSUE TITLE
Creating a working agreement for devs

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#47]
- How does the branch name looks like
-  How many reviews are required for approving a PR
-  Commit code regularly and push at the end of the day if possible
-  Gate through PR reviews

**Comment by HeatherRemacle** [comment]
Perhaps this is a decent reference? https://hackernoon.com/a-branching-and-releasing-strategy-that-fits-github-flow-be1b6c48eca2 (from DevHub)
