### ISSUE TITLE
Create a request to delete old namespaces once migrated successfully to OCP4

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#474]
https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+mitovskaol%2C+ShellyXueHan%2C+patricksimonian&labels=openshift-project-set%2C+pending&template=openshift_project_request.md&title=

**Comment by parulmishra** [comment]
Dependent on issue https://app.zenhub.com/workspaces/digitalgovbcca-5c586bed93a5605cab276e9c/issues/bcgov/digital.gov.bc.ca/548

**Comment by mark-a-wilson** [comment]
Done. https://github.com/BCDevOps/devops-requests/issues/849
