### ISSUE TITLE
CoCos Content Types

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#476]
Ticket estimate based on assumption that the CoCo metrics are **NOT** included, **OR** that they are manually added to the strapi database.

Based on the design of the CoCo library, there are data elements to structure in the MongoDB. We need to confirm what these are, how they are named, and how they relate to eachother.

1.  Which fields are required for the CoCos and which fields are optional ?
2. Which fields are single value/multiple.
2.  Is there any hidden meta data /fields that not visible to the front end ?
3.  Conversation with CoCo SME (Lada)
4. Are we always going to have single featured video ?
5. Does this include metrics?  (If not I recommend creating a new ticket for implementing metrics)

### Acceptance Criteria
- [ ] Inderdeep has tested this and it works
- [ ] There is documentation to explain how to create the content

### Definition of Done
- [ ] A user can login to Strapi admin and create (the content for) a CoCo
- [ ] Code review has been done
- [ ] All content fields present on the mockups are represented in strapi content type
- [ ] PO is able to create a CoCo in strapi in the dev namespace.
- [ ] PO signs off on the build

**Comment by thegentlemanphysicist** [comment]
Issues with the ministry drop down: how are we going to deal with changing ministries over time? What if a ministry changes name or logo or no longer exists?  How do we want to deal with legacy ministries?
