### ISSUE TITLE
Featured CoCo Page Content Type

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#477]
We will build a content type using Strapi CMS and populate a new page with  the first CoCo that is ready, useful and documented (i.e. data can be entered into our database).

The content should be referenced on the CoCos home page (we may need a separate ticket for this)

![image.png](https://images.zenhubusercontent.com/5eb1cfe9cf91c115cba78411/238b28ba-0576-4dba-9396-7d404882ade2)

**Comment by thegentlemanphysicist** [comment]
Link to coco  page
https://digital-gov-frontend-pr-533-c0cce6-dev.apps.silver.devops.gov.bc.ca/cocos/keycloak
Link to strapi admin panel
https://strapi-pr-533-c0cce6-dev.apps.silver.devops.gov.bc.ca/admin

**Comment by thegentlemanphysicist** [comment]
Merged in
