### ISSUE TITLE
Decommission the BC Dev Exchange

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#485]
In order to free up resources for the migration to Openshift 4, BC Dev Exchange must be destroyed. (!) 🧨💥 This epic outlines what needs to be done to decommission that site.

**Comment by mark-a-wilson** [comment]
This Epic was identified as needing to be done in December 2020. Since then, decision was made to migrate the site to OCP4 and leave it up for a while.
