### ISSUE TITLE
Decide what content from bcdevexchange.org must be migrated

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#486]
#### Definition of Done
- [x] Consult with Platform Services team and Exchange Lab team about what content is critical and needs to be migrated elsewhere
- [x] Create a document with screenshots to be super clear about what content needs to be migrated to digital.gov

**Comment by mark-a-wilson** [comment]
So far have talked with Olena & Justin (Platform page) -- they'll scrape content and keep it somewhere but aren't fussed about it being redeployed anywhere right now.

Ari -- thinks it is safe to copy & paste what we have on Exchange Lab and the homepage features (Podcast, Rocket.Chat, Newsletter)

Tricky piece of content to migrate will be **Learning** as it is dynamic: currently, content on the Learning page automatically stays update from EventBrite API.

**Comment by mark-a-wilson** [comment]
Have decided what content needs to be recreated and outlined this in the Acceptance Criteria on #487.
