### ISSUE TITLE
Recreate critical BCDevExchange content in digital.gov WordPress site

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#487]
#### Acceptance Criteria
@singhinderdeep, what I’m thinking we do in WordPress is:

1. Change the title of the Standards & Guides page and nav link to “Resources”
2. On the page with the cards, edit the “BCDevExchange” card to be “Exchange Lab” with a description of “The Exchange Lab helps accelerate digital delivery teams in a collaborate workspace.” 
3. This card will link to a new page that we create entitled “Exchange Lab”
4. On that single page, we incorporate all of the content below:

_With all, incorporate a few images or cards if possible/easy. If not, images can be omitted._

(From the **Exchange Lab** page)
- [ ] All of the headings, words, and links (don't bother with images unless some can be incorporated easily)

(From the **Home** page)
- [ ] Community section 
- [ ] The Exchange Podcast (don’t bother with the subscribe instructions)

(From the **Learning** page)
- [ ] Create a combined "**Courses & Events**" heading. Incorporate:
- [ ] Title, description, and ‘Register’ link for any items that are currently showing as active on bcdevexchange.org. (When remove bcdevexchange.org and these courses need to be updated on digital.gov WordPress, we’ll just update those by hand)
- [ ] Call to action to contact Ari or Dea. Provide their name, title and email address/link, but don’t bother with the photo headshot.

- [ ] Also create a **Contact Us** heading with email address of ExchangeLab@gov.bc.ca

#### Definition of Done
- [ ] Create content as outlined above in the **TEST** WordPress site
- [ ] Mark has reviewed in TEST and approved
- [ ] Recreate this in the **PROD** WordPress site and publish
- [ ] All content is migrated and live on digital.gov.bc.ca

**Comment by mark-a-wilson** [comment]
Change of plan: JL going to migrate bcdevexchange to OCP4 on our behalf. Decisions can be made later about migrating content and decommissioning the site.
