### ISSUE TITLE
Move BCDevExchange content to react/strapi site

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#488]
This issue is a placeholder/reminder for now. 

We will move content to the WordPress site before decommissioning bcdevexchange.org, but this can be done afterwards. 

When we we're ready to launch the react/strapi site, I'll make a call whether the absence of BCDevExchange content is acceptable or not.

**Comment by mark-a-wilson** [comment]
Change of plan: JL going to migrate bcdevexchange to OCP4 on our behalf. Decisions can be made later about migrating content and decommissioning the site.
