### ISSUE TITLE
Archive the bcdevexchange repo

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#489]
Indicate clearly on the BCDevExchange codebase that the project is being mothballed.

#### Definition of Done
- [ ] Add project lifecycle badge to README (Mark has submitted [this PR](https://github.com/bcgov/bcdevexchange/pull/92) for this already; it just needs to be merged.)
- [ ] Under the **About** info on the repo landing page (can be accessed by admin under Settings), change the description to: "Code for a simple website about the BCDevExchange that existed at bcdevexchange.org from 2020-21."
- [ ] Archive the repository

**Comment by mark-a-wilson** [comment]
Change of plan: JL going to migrate bcdevexchange to OCP4 on our behalf. Decisions can be made later about migrating content and decommissioning the site.
