### ISSUE TITLE
Create a Sequence/Schematic diagram 

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#49]
- Shows how the different pieces interacting 
- Will be stored in the Readme

**Comment by HeatherRemacle** [comment]
Documents are stored here: https://github.com/bcgov/digital.gov.bc.ca/tree/develop/docs

These have been started by Patrick using Miro but need to be completed.

**Comment by mark-a-wilson** [comment]
This work being done by Parul under #499
