### ISSUE TITLE
Find out what to do with the old BC Dev Exchange URL

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#490]
Currently the url https://bcdevexchange.org/ goes to the the BC Dev Exchange.  
What should happen to it once the site is decommissioned?  Since people may have the site bookmarked it may be worth keeping the url active and redirecting traffic to where the content is now hosted.

**Comment by parulmishra** [comment]
@mark-a-wilson We need to free the route https://bcdevexchange.org/ from Openshift. Also delete the SSL certs.

**Comment by mark-a-wilson** [comment]
The bcdevexchange.org domain is owned by BCDevOps. I will try to connect with Olena or Shelly or someone from the platform team to get advice on the best thing to do here.

**Comment by mark-a-wilson** [comment]
Just talked with Olena. She agreed that a redirect should be set up from bcdevexchange.org (or any pages within that domain) to the appropriate page on digital.gov.bc.ca.

The bcdevexchange.org domain is owned by BCDevOps (Platform Services team), so if Parul needs any assistance with changes to the domain, she can reach out directly to Cailey Jones.
