### ISSUE TITLE
Decomission the BCDevExchanges Openshift 3 name spaces

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#491]
Once the content on BC Dev exchange has been migrated #488 #487 and the url has been turned off 

Submit a request to the platform services team to decomission namespaces for the BCDevExchange and free up the resources.

**Comment by mark-a-wilson** [comment]
Change of plan: JL going to migrate bcdevexchange to OCP4 on our behalf. Decisions can be made later about migrating content and decommissioning the site.
