### ISSUE TITLE
Strapi spike: research how strapi handles content states.

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#498]
There is some ambiguity about how strapi handles state (drafts) of new content.  Answer the questions

- how we can make drafts of content when it's a WIP
- is it possible to migrate content from test to prod (if a new CoCo is entered in test can it be easily promoted to prod) 

This has now been implemented in pull request #506 . The draft functionality was incorporated in the 5.2 release, so once the upgrade was completed I was able to configure CoCo's to use the 'save draft before publishing'

**Comment by thegentlemanphysicist** [comment]
@mark-a-wilson  @HeatherRemacle 
The save draft functionality is now implemented in PR #506.
https://strapi-pr-506-xdwiwd-dev.pathfinder.gov.bc.ca/admin/

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist — I just tested and can confirm I was able to save a DRAFT per requirements in feature #512. I have closed #512.
