### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#499]
We are planning to improve the documentation that we have currently for digital.gov. 
for reference please look https://github.com/bcgov/PIMS/blob/dev/README.md 

Note: Also add steps for running Zapscan

**Comment by mark-a-wilson** [comment]
@nmathava - I decided to detach this from the Epic #98. That Epic is quite broad and aspirational and I don't know if we will end up tackling it or not. This ticket is much more defined and short-term, it's just about making a quality README for our code repository.

**Comment by mark-a-wilson** [comment]
Hey @parulmishra, @thegentlemanphysicist  — sticking this back in Code QA column as it looks like [the PR](https://github.com/bcgov/digital.gov.bc.ca/pull/507) needs another (approving this time) review from @thegentlemanphysicist before it can be merged. Please go ahead and merge and close this ticket when you two are happy, I don't need to review.

Hey @parulmishra - for future, if you're sticking an issue into PO to Review column, can you include a comment with a link to what/where I'm supposed to be looking? (I figured it out, it's [this PR](https://github.com/bcgov/digital.gov.bc.ca/pull/507) — but that's not obvious from opening up this ticket.) Thanks.

**Comment by parulmishra** [comment]
@mark-a-wilson PR https://github.com/bcgov/digital.gov.bc.ca/pull/507
