### ISSUE TITLE
Collect final content for all CoCos that are to be published in R2

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#500]
Once the Strapi CoCo content model is designed and implemented, we'll be ready to enter all of the CoCos content in Strapi.

#### Acceptance Criteria
- [x] Content matches the Strapi content model (#476 which has been created to match the [Wireframes in Figma](https://www.figma.com/file/XPe01CLbBIUuIaUJRHGOM8/CoCo?node-id=0%3A1)) 
- [x] Content is in a format (Word document or Figma wireframe) such that any team member can easily decipher what words to paste into which fields in the Strapi GUI
- [x] Link to where the final content is included in this ticket before closing

#### CoCos to be included in R2:
- CHEFS
- CHES
- CDOGS
- SSO
#### Definition of Done
- [x] Final content for all CoCos for R2 is complete in the format described above

**Comment by mark-a-wilson** [comment]
@singhinderdeep — I'm not sure if [this](https://docs.google.com/spreadsheets/d/1--lOko3vsCpqq_WZI1hH1ABbDxTrfdzmxe16S6A_a1U/edit#gid=0) is the current list and where the content is being collected?

Can you please communicate with Lada and edit the checklist in the issue description above (under the **CoCos to be included in R2** heading) to make it clear how many and which CoCos will be ready?

**Comment by singhinderdeep** [comment]
Figma link
https://www.figma.com/file/XPe01CLbBIUuIaUJRHGOM8/CoCo?node-id=368%3A7646
