### ISSUE TITLE
Create beautiful design for CoCos page.

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#508]
Create a design that represents the Common Components.  Like other page header designs there should be a white and grey background version if we wish to link to the CoCos page through a card (as we do with other digital.gov.bc.ca pages).
Ideally this will be uploaded to the `/images/pngIllustrations` folder of the github branch `frontend-456` so that @thegentlemanphysicist may integrate it into the CoCos page creation.

**Comment by mark-a-wilson** [comment]
![image.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/aaca3b02-1957-4ba4-9f22-d600b1d39082)

Nice one, @singhinderdeep !
