### ISSUE TITLE
Strapi Spike: Restrict upload image aspect ratio and size.

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#509]
Currently any image size and aspect ration can be uploaded to strapi by the strapi content manager as a CoCo cover image.  This will cause some issues on the CoCo page.  Ideally the content manager would be required to upload an image of a certain quality or aspect ratio to insure proper display on the frontend.  
This does not appear to be within strapi's 'out of the box functionality'.  Though there may be a way of customizing the app that allows it.
Goal of this spike:
 - Find out if this is possible.
 - If it is and can be done easily, implement it (otherwise document findings and create an implementation ticket)
 - Determine if it is worth contributing this functionality back to the strapi ecosystem. 

Useful video @thegentlemanphysicist found that may give hints to how this can be implemented:
https://www.youtube.com/watch?v=o06N-q2awQA minute 18 is where the strapi stuff starts

**Comment by thegentlemanphysicist** [comment]
It is definitely possible.  Though it will be finicky. Jon's thoughts on this:
- Implement the icon picker ticket.  The pluggin should be relatively easy to adapt from a colour picker that has been implemented by the community https://www.paulgaumer.com/blog/how-to-create-a-color-picker-plugin-for-strapi-cms
- Implement the new WYSIWIG rich text editor that I found out about today for rich text fields. https://strapi.io/documentation/developer-docs/latest/guides/registering-a-field-in-admin.html#setup
- Then once those are build and tested start working on the plugging for media library restrictions.

**Comment by mark-a-wilson** [comment]
Icon picker -- I'm supportive of implementing that when, from the design perspective, there is a need for a content manager to be able to select and icon to use somewhere in the frontend (I'm not aware of a use case for that yet?)

WYSIWIG editor -- I'm supportive of implementing that soon; it think it's a good UX improvement for content managers.

I'm not clear, though, on how these relate to the purpose of this ticket?
