### ISSUE TITLE
Spike Strapi: Create an 'icon content type'

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#510]
Currently one of our content types requires an icon as input, however that is not one of the 'out of the box strapi' content type fields.

After some research, strapi does have the fontawesome library installed, it may be possible to leverage this library to create a custom content type field for our strapi implementation that allows the strapi content managed to add an icon from a dropdown instead of uploading custom images, a much more intuitive UI for the content manager.
Outcome: answer the following questions:
 - is this feasible
 - has it been done already
 - can we contribute this back to the strapi project
 - create an implementation ticket.

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist — before you spend any time on this, I'd like to interrogate the necessity of having these icons with @singhinderdeep and Lada:

I understand that having some icons will add more visual appeal, but I wonder if it's going to be a lot of work for the content creator to find an icon that makes any sense in matching the reason that's being presented? For example, this is from the wireframe for CHEFS:
 
![Screen Shot 2021-01-12 at 11 01 48 AM](https://user-images.githubusercontent.com/16946297/104360566-1fe08e00-54c6-11eb-86c9-d62ed63d78ff.png)

I don't really see how the magnifying glass conveys the meaning of a drag-and-drop feature, of how access controls are related to money, or how the graph represents "configurable form actions"?

Is there perhaps an alternative way we could inject some iconography for visual appeal, but eliminate the work of having to make a decision?
