### ISSUE TITLE
Design the chosen feedback design pattern

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#521]
#### Description of Task

Design the chosen feedback design pattern to be used

#### Definition of Done

- [ ] Design has been checked with BC design standards from the Design System
- [ ] Design has been peer reviewed
- [ ] Design has been approved by PO

**Comment by singhinderdeep** [comment]
Link to the Figma file

https://www.figma.com/file/OA7WRajwPeijLD5PyWJpiY/Feedback?node-id=0%3A1

**Comment by mark-a-wilson** [comment]
@singhinderdeep — Thank you for analyzing other jurisdictions' examples and putting your thoughts right into the mockup file, and for making this into a clickable prototype. I feel like you've nailed the design of this! Really look forward to implementing this and seeing where it goes. I've added a link to it in the item on our Roadmap, so I hope stakeholders will happen across it and check it out too.
