### ISSUE TITLE
Implement style changes to CoCo home page

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#528]
- [ ] Update contact information Make the email address Digital.Government@gov.bc.ca Remove the phone number
- [ ] Implement design changes decided on in ticket #527.
- [ ] Update strapi content type if needed.
- [ ] Make certain the stats tags resize responsively and that @singhinderdeep approves of implementation.

**Comment by thegentlemanphysicist** [comment]
The colour scheme on status dot was unclear to user, even with the hover text added to it. There were also questions about the the colour choice being accessible.

Remove coloured dot
	
Should there be a separate 'status' tag (abandoned, maintained, Active development) on the coco card instead of a coloured dot next to the maturity tag (alpha, beta, mature)?	
		
Yes, add separate “status” tag after the maturity tag

Stats tags at the bottom:
	
Long labels like 'Subscription' can mess with the formatting and make things look crowded at certain screensizes

What if we make it a tad simpler, and the only options for this label are “Free” or “Paid?”. Then, on the detailed page the subscription service can be explained. This is just  a sneak peak to help users understand if they want to pursue investigation the CoCo, it doesn’t need to provide the full story.
	
The css can be adapted to account for this. However to do this, the developers need to have a decision on what options will need to be displayed. Specifically the cost structure and support structure.
	
Should we add hover text to the stats explaining what they are? Something like 'cost structure' 'number of teams using' 'estimated onboarding time' 'support availability'
		
Yes, lets add hover text to the stats

**Comment by singhinderdeep** [comment]
some observations related to styling 

- BC Sans bold seems a bit off (visually has less weight than the ones in Figma/other BC Gov sites)
- About typography, we are using type size in px but in other BCGov sites rem/em is being used. I am not the best judge, so will leave it to Jon but just wanted to make a note of it.
- Digital.one homepage, in the cards there needs to be space between the description text and the link.

**Comment by mark-a-wilson** [comment]
No complaints with the CoCo home page. Go ahead and close, @thegentlemanphysicist
