### ISSUE TITLE
[CONTENT] Resources page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#53]
[Content Template >](https://docs.google.com/document/d/1JMld6orNCOQfujeGt40eNT7UIgTnUlzSRcDVf_u-vpI/edit#)

**Target audience** (_Who is this content for?_):  BC Public Servants and/or contracted professionals working on digital services

**Desired outcome** (_What do we want this content to help the reader understand or do?_):  Find resources related to “digital”

#### Acceptance Criteria

- [x] Includes links to: Digital Framework, Digital Policies, Digital Principles
- [x] Includes a feature for Video Communication Platforms

#### Definition of Done

- [x] Content template completed in Google Drive; link included 
- [x] Content has been approved for publication by Product Owner

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - [Draft here](https://docs.google.com/document/d/1JMld6orNCOQfujeGt40eNT7UIgTnUlzSRcDVf_u-vpI/edit) for your review.

**Comment by HeatherRemacle** [comment]
Good stuff. This just needs user feedback.
