### ISSUE TITLE
Remove COVID banner from site

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#532]
#### Why are we doing this?
We originally created the COVID banner thinking it would be a requirement for all public-facing, gov-themed sites. But upon further discussion with GDX in January 2021, it doesn't seem to be a requirement. Gov-themed, public-facing applications are _**not**_ using the banner; it really just makes sense to be on the main site aimed at the public: gov.bc.ca. As the product owner, I'd prefer it not appear. 

#### Acceptance Criteria
- [ ] COVID banner no longer appears on the site

**Comment by thegentlemanphysicist** [comment]
This will eventually be live at:
https://digital-gov-frontend-pr-543-c0cce6-dev.apps.silver.devops.gov.bc.ca/
