### ISSUE TITLE
[CONTENT]: About us

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#54]
Target audience: People who are not familiar with the CITZ corporate services that support digital

Desired outcome: We generate familiarity and trust and clarity on who to connect with.

#### Acceptance Criteria

- Clarify where this information is coming from - what organizations.
- We're working with partners and stakeholders across the goverment, including MCIOs
- Convey the nature of the approach we take (working in the open, collaborative, always learning)
- Contact digital.gov.bc.ca
- There needs to be a way to link to the content

#### Definition of Done

- [x] [Content template](https://docs.google.com/document/d/11Dx_EL0ssbMPVwWwJ3y3cP5tR_ivLe_aB__aXSKa5Fo/edit?usp=sharing) completed 
- [x] Content has been reviewed by someone other than the writer(s) (another team member, or a government employee outside our team) 
- [x] Content has been approved for publication by Product Owner

**Comment by mark-a-wilson** [comment]
Heather said she had a clear idea in mind of what this content would contain and that she could probably draft it quickly.

**Comment by mark-a-wilson** [comment]
Just reviewed -- reads fine to me!

**Comment by mark-a-wilson** [comment]
Closing this and tagging with Sprint 2 Milestone
