### ISSUE TITLE
Card styling fix.

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#549]
Two tweeks have been requested on sight styling
- There should be a bigger space between text and links on home page cards
- BC Sans bold seems a bit off (visually has less weight than the ones in Figma/other BC Gov sites) Investigate and fix this.

**Comment by mark-a-wilson** [comment]
Marking as invalid and closing because:
- space between text and links will be superceded by #623, and
- BC Sans has been fixed now
