### ISSUE TITLE
Spike: Does strapi interpret markdown

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#55]
The chapter 12 content on github is produced in markdown.
- does strapi allow us to copy that markdown in and render it properly?
- can the react app pull that content in directly from github to the react app. (bi-pass strapi altogether)

**Comment by mark-a-wilson** [comment]
If our main aims are:

1.  Make the principles nice for users to read
2. As the principles evolve, make sure users are reading the current ones, not an older version

We could:

1. Publish the principles on a page on our site (through our CMS) 
2. Subscribe to Releases (Sara is using Releases, which you can subscribe for); when we get notified of a new release, update the content on our site

If on the other hand our aim is more to show how the principles are being developed in the open and encourage people to comment on them, we could create some content around that and then send people off to GitHub to read them.
