### ISSUE TITLE
Find out what content the CDO wants to provide about hosting

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#551]

**Comment by mark-a-wilson** [comment]
Spoke to Danny today. He has content in for approval and will share with me as soon as he can.

**Comment by mark-a-wilson** [comment]
[This is a draft](https://drive.google.com/file/d/11FwLxcR_pRMzZQoOhLaw-l-daovdPzL1/view?usp=sharing) by Mac Campbell -- it is currently making the rounds for approval including with CITZ Comms. Danny will send to us when it's ready for publication.
