### ISSUE TITLE
Add video and PDF report to Digital Framework page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#564]
#### Acceptance criteria
YouTube video embed of [this video](https://youtu.be/D4DhfV7splA) and a download link to [this PDF]( http://digital.gov.bc.ca/app/uploads/sites/552/2021/02/digital-framework-progress-report.pdf) added to the Digital Framework page in this location:

![Screen Shot 2021-02-11 at 11.36.34 AM.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/8f9bc3a7-2bcd-4794-8495-174e647f16c2)

**Comment by thegentlemanphysicist** [comment]
@mark-a-wilson This was implemented with 558

**Comment by mark-a-wilson** [comment]
Thanks, @thegentlemanphysicist  - No, the PDF won't be required if the collapsible menu (accordions) can be implemented.
