### ISSUE TITLE
Update wireframe for Digital Framework Progress page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#572]
@singhinderdeep - for more clarity for Jon, could you please make the following revisions to the wireframe/prototype:

#### Acceptance Criteria
On the [DF - PROGRESS tab](https://www.figma.com/file/bRc0nJnXsNo8KF8UCYvq12/Digital-Framework-Updates?node-id=1%3A392):
- [x] Add video embed above accordions
- [x] Remove status labels on accordions (e.g. 'Active') (I confirmed with Danny they will not be needed)

On the [Dig Principles expanded tab](https://www.figma.com/file/bRc0nJnXsNo8KF8UCYvq12/Digital-Framework-Updates?node-id=1%3A520):
- [x] Add video embed above accordions
- [x] Remove status labels on accordions
- [x] Make the STRATEGY/PROGRESS toggle match the other frame
- [x] Revise accordion body for Digital Principles to match [this content](https://digital.gov.bc.ca/digital-framework-progress/#digital-principles).  Feel free to modify the columns, boxes, shading -- but please use all of the wording verbatim.

**Comment by singhinderdeep** [comment]
Incorporated all the comments.
Plesae review the updated design here
https://www.figma.com/file/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=3625%3A24

**Comment by mark-a-wilson** [comment]
Looks great, @singhinderdeep — thanks 👍
