### ISSUE TITLE
Design index and detail pages for Communities

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#584]
@singhinderdeep,  can you have a look at [the U.S. Government treatment of this](https://digital.gov./communities/). You'll see by the Acceptance Criteria below there are some elements of this design I'd like to be included. I'm open to alternative and/or additional ideas you have.

#### Acceptance Criteria

Use [this BCDevExchange content](https://docs.google.com/document/d/1lIJRemWjZliLLu6vsph0JZmvS4QT9Y69jigb3zhQTZo/edit?usp=sharing) to mock up the detail and index page

Index page
- [x] Card layout
- [x] Each community card shows title and lead (one-sentence blurb) 
- [x] Card’s appearance changes in some way when hovered over
- [x] Full card should be active to be clicked; not just title or link on the card 

Detail page
- [x] Shows navigation back to the Index page
Includes:
- [x] Community Managers heading. One or many names can be added. No photo for now. Includes name and link to the person’s email.
- [x] Body with free text that can contain headings, text, links, images
- [x] Has placeholders for (optional, not required) links to the Community's: Rocket.Chat, Yammer, @Work, MS Teams, Website

**Comment by singhinderdeep** [comment]
@mark-a-wilson 

- For Card layout - have two versions. I have picked my preference with a tick mark on top. Feel free to change it.
- For Card’s appearance changes in some way when hovered over, have added a subtle drop shadow. See if it's ok or too subtle.
- FYI - have just done drop shadow thing for one card and not for all as for that had to duplicate that many frames. But I hope the one clarifies the intent.
- For links, two versions as well (with and without logos). My pref again depicted by the tick.

Looking for your feedback/comments

**Comment by mark-a-wilson** [comment]
@singhinderdeep -- left you a couple of comments in the Figma file to address before marking this as done. Thanks!
