### ISSUE TITLE
Create wireframe for revisions to Learning page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#598]
These requirements came out of meeting Jan 27, 2022 with Amy, Ari, Kim, Mark and Inderdeep.

Wireframe should include:
- [ ] A feature for Digital Academy with text and logo provided by Amy.
- [ ] A feature for **Digital Academy** courses that links to: https://learningcentre.gww.gov.bc.ca/learninghub/learning_partner/digital-academy/
- [ ] A feature for **Government Digital Experience** courses that links to: https://learningcentre.gww.gov.bc.ca/learninghub/learning_partner/government-digital-experience/

**Comment by mark-a-wilson** [comment]
Content for this coming soon from Justine!

**Comment by SteveChapmanBCDX** [comment]
@SteveChapmanBCDX to check in with Derek M on status.
