### ISSUE TITLE
Design the Homepage

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#60]
Design multiple design variations of Homepage

**Acceptance Criteria**

Needs to be clear
Follow the BC Gov Design Guidelines

**Comment by singhinderdeep** [comment]
Completed the mobile and desktop designs for the homepage with the approved content and following the BC Gov Design Guidelines. 

Snapshots attached to the Wireframes Frame of Miro Board https://miro.com/app/board/o9J_kslEIZ4=/

**Comment by HeatherRemacle** [comment]
Some minor changes to make - recorded in Miro.

**Comment by mark-a-wilson** [comment]
Appears we have duplication between this and #92

**Comment by HeatherRemacle** [comment]
@mark-a-wilson I believe we added #60 to complete the design with images... but I could be wrong. Either way, I'd say it is still in progress unless images are being addressed somewhere I cannot see.

**Comment by mark-a-wilson** [comment]
Oh, I see - @singhinderdeep, can you comment?

**Comment by singhinderdeep** [comment]
I believe in the call we had with Ryley, we all decided we could use a placeholder for now, since the structure and content will keep on changing, and this will be a wasted effort. Once we are sure about the structure and content, we could just drop in the relevant images. @HeatherRemacle if you are not comfortable with this, please let me know. I can work on images now.
