### ISSUE TITLE
update links on Resources page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#608]
There are a number of broken (outdated) links on the Resources page. Please find these resources on gov.bc.ca and update the following links that are currently broken:

![resources-1.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/890f28d4-a124-40d5-8591-f2171f857526)

![resources-2.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/1f82e28b-9a64-40bd-a70f-67808b4eae69)

@thegentlemanphysicist --- see this tip 👇 (Thanks, @ty2k !!)

![image](https://user-images.githubusercontent.com/16946297/110547526-e6eb2100-80e4-11eb-8ac9-40facc227ce7.png)

#### Acceptance Criteria
- [x] **Web Standards** - update title to **Web Standards & Guides**; udpdate link to: https://www2.gov.bc.ca/gov/content?id=1AA28225F41347FE9F8D0B4F1733CEFE
- [x] **CMS Lite User's Manual** - update link to: https://www2.gov.bc.ca/gov/content?id=81BBC6221D42401EBCE13D4D8945F3A3
- [x] **Content Design Guide** - update title to **Content Design & Strategy**; update link to: https://www2.gov.bc.ca/gov/content?id=D5D182EF4D9F42B5997CCB2029068B5E
- [x] **Plain Language Guide** - update title to **Plain Language Course**; update link to: https://www2.gov.bc.ca/gov/content?id=250C67AD0B954DB9B0549EED6C36BDEF
- [x] **Service Writing Guide** - update title to **Writing Services for the Web**; update link to: https://www2.gov.bc.ca/gov/content?id=B990ECA6DAB94CD0BE2C1AE7BD439ADC
- [x] **Visual Design Guide** - update link to: https://www2.gov.bc.ca/gov/content?id=A9801C7B52CE481BBD36CAD87C297142
- [x] **Web Style Guide** - update link to: https://www2.gov.bc.ca/gov/content?id=14FD003042FC422182796E84A6C343C9
- [x] **BC Gov on Github card** -- Capitalize the "H" in "GitHub"

**Comment by thegentlemanphysicist** [comment]
@mark-a-wilson For the record this ticket requires changing just about every link to a gov page on our site.  They all need to be shifted over to the GUID based thing.

**Comment by ty2k** [comment]
Hi @thegentlemanphysicist @mark-a-wilson, just to give you some more context on how pages within the Gov website are routed, this is a good read: [Human-Readable URLs - Province of British Columbia](https://www2.gov.bc.ca/gov/content?id=D248756D685C4B22B54B902608C8FC90)

Basically, the human-readable URLs ("HRUs") can be changed by the owners of that content within CMS Lite as pages are re-arranged in the information architecture. As you experienced with the Web Standards & Guides content, big swaths of pages can all change at once sometimes (it actually only takes a click and drag action in the UI to do this). There is no provision for redirecting HRUs that change in the current system.

The GUID permalinks are the best option for links to www2.gov.bc.ca for that reason.

@thegentlemanphysicist, I like your idea in #630 about automatically tracking link freshness as a long term solution across all links. :+1:

**Comment by thegentlemanphysicist** [comment]
@ty2k The guid trick was really useful, I didn't know BC gov sites had those :P I'll have to go through the rest of the app and clean up that tech debt
