### ISSUE TITLE
Code the home page

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#61]
#### Acceptance Criteria

- [ ] Page contains all content as shown on [Wireframes](https://miro.com/app/board/o9J_kslEIZ4=/?moveToWidget=3074457348200785828&cot=13) 
- [ ] Content renders in one-column layout on mobile phone displays, 12-column layout on larger/desktop

CSS for the following matches specs defined in the Design System:

- [ ] [Colour Palette](https://developer.gov.bc.ca/Design-System/Colour-Palette)
- [ ] [Typography](https://developer.gov.bc.ca/Design-System/Typography)
- [ ] [Links](https://developer.gov.bc.ca/Design-System/Links)
- [ ] [Icons](https://developer.gov.bc.ca/Design-System/Icons)
- [ ] [Header - Basic](https://developer.gov.bc.ca/Design-System/Header-Basic)
- [ ] [Footer](https://developer.gov.bc.ca/Design-System/Footer-Basic)
- [ ] [Navigation Bar - Basic](https://developer.gov.bc.ca/Design-System/Navigation-Bar-Basic) (collapses to hamburger)

#### D.O.D.

- [ ] Page can be viewed online in a DEV, TEST or PROD environment
- [ ] Page loads quickly

It's understood that the page will be flat, that none of the links will work yet (Navigation, teasers, footer) until more pages are built.

**Comment by Dianadec** [comment]
Cannot estimate yet since we need to see what the designs are.
AC needs revision.

**Comment by mark-a-wilson** [comment]
Took the liberty of filling in Acceptance Criteria, Definition of Done. @ryleyw - does this make sense/work for you?

**Comment by HeatherRemacle** [comment]
Looking forward to seeing this today @ryleyw - I've cleared space in my calendar for review
