### ISSUE TITLE
Implement WYSIWYG text editor for strapi rich text fields.

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#618]
Accidentally found a tutorial on implementing a text editor with live styling plugin for  rich text fields.  It's easy to do, worth the effort for an easier content experience. I was able to implement it on local development pretty trivially.  There may be some customizing that needs to be done.

[Link](https://strapi.io/documentation/developer-docs/latest/guides/registering-a-field-in-admin.html#setup
)
- note the default WISIG changes the markdown to html, either change the output to markdown, or change the frontend to accept html

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist -- I'm looking at deployment #646 -- nice! I think this editor provides a much nicer experience. Question, though: are there additional options to these that can be included in the editor (e.g. inserting photos in amongst formatted text)?

![image.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/d273ee7b-adb8-480b-b54e-613f72b2b003)
