### ISSUE TITLE
Create strapi plugin restricting image aspect ratio for cocos

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#619]
We would like to give strapi developers the ability to restrict image aspect ratios content managers are able to add to cocos.  This will require creating a new plugin for a 'restricted image field'  
This ticket should be tackled after we've had a chance to experiment with building pluggins.  Namely #510 and #618.
- The content manager should have a clear indication of which image aspect ratios are accepted
- If an incorrect image size is selcted, a clear error message should be displayed in red indicating what went wrong.
- Maybe document what was done in a medium article or something.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with team - NTH - closing ticket.
