### ISSUE TITLE
Reduce padding on contentBlockContainer

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#624]
There is too much space between sections of content on some pages, for example, on the Case Studies detail pages:

![contentBlockContainer.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/881fd4a7-8515-4ae3-a8b4-8b44677be4b5)

This appears to be due to `padding-bottom: 120px` on the `contentBlockContainer`. Please reduce this to `60px` (all breakpoints).

**Comment by thegentlemanphysicist** [comment]
@mark-a-wilson  I'm assuming this is specifically the case studies page so that is the only one I've touched

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist - the change you made has improved the spacing everywhere `contentBlockContainer` is being used -- in addition to the case studies pages, the Products & Services and Resources as well. 👍
