### ISSUE TITLE
Create the build and deploy infrastracture for Strapi

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/digital.gov.bc.ca#63]
Strapi has a docker based image that we shouuld be able to leverage for creating our strapi build and deploy configs. I'm not too if there are k8s based components we could borrow for this. 

## Notes

Let's make sure to well document or codeify our infrastructure so that it can be usable by the community

## Acceptance Criteria

- [x] strapi docker based build completed and is producing healthy images
- [ ] strapi deployment config created and is producing healthy pods (this should also include readiness and liveness checks)
- [ ] documentation on running strapi on openshift

## Other Notes

There are some unknowns on how strapi is configured. So let keep in mind we can mount configuration via different mechanisms: configmaps, secrets, and env vars.

**Comment by thegentlemanphysicist** [comment]
Status: the able to create a build in openshift
next attempt to deploy the build in os

**Comment by thegentlemanphysicist** [comment]
I am completely stuck on this until I can toruble shoot with patrick
