### ISSUE TITLE
Create or fix  a  broken link checker

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#630]
Our frontend has a lot of hard codded links, the sites that they link to often change things without telling us.  Goal set up a github action that periodically checks these links and raises a warning when one is out of date or returns status 404.

Investigate why our current testing framework isn't catching these.

Out of scope:  Links stored in strapi cms.

Examples of existing ones 
https://github.com/marketplace/actions/broken-link-checker-action

**Comment by thegentlemanphysicist** [comment]
Cron job has been set up to run on the third of the month.  Will check tomorrow to make sure it ran

**Comment by thegentlemanphysicist** [comment]
it ran as expected

**Comment by SteveChapmanBCDX** [comment]
Reviewed and closed.
