### ISSUE TITLE
Design the blog page

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#632]
Design the blog page

**Comment by singhinderdeep** [comment]
![Blog-white.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/cf3c3550-07a0-4f47-9720-f938ad2c53cb)![Blog-gray.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/c7f4b44d-8ba0-40c1-9e91-ddc1dc0727c9)

**Comment by mark-a-wilson** [comment]
@singhinderdeep Nice!
