### ISSUE TITLE
Setup Mongo HA ReplicaSet for strapi

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/digital.gov.bc.ca#65]
- [ ] a mongodb replicaset statefulset created for our strapi instance

- [ ] a mongodb replicaset build config created for our strapi instance (this may not be required, we may be able to leverage another image)

**Comment by parulmishra** [comment]
Raised a request for gluster-block storage for the issue #65 Setup Mongo HA replica set for Strapi @patricksimonian

**Comment by HeatherRemacle** [comment]
Need to post dummy data through mongo compass to test... There are other issues that should be written related to this.

**Comment by parulmishra** [comment]
PR link: https://github.com/bcgov/digital.gov.bc.ca/pull/78
