### ISSUE TITLE
Spike on cost of multiple roles

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#656]
Currently Strapi allows 3 roles - investigate cost of unlimited roles vs modifying Strapi's code

**Comment by thegentlemanphysicist** [comment]
The pricing plan is as follows:
https://strapi.io/pricing-self-hosted 
29$/month for the cheapest option, includes basic support and 30 custom roles
299$/month for unlimited roles

**Comment by thegentlemanphysicist** [comment]
Tracked down where the roles are mentioned in the node modules
strapi-app/node_modules/strapi-admin/services/role.js
strapi-app/node_modules/strapi-admin/services/__tests__/role.test.js

**Comment by thegentlemanphysicist** [comment]
Result: we can get past the pay wall by adding the new role directly to the database using :
 ```
db.strapi_role.insert({ "_id" : ObjectId(),"name" : "BlogAuthor", "code" : "blog-author", "description" : "The blog author can create and edit blogs.","createdAt" : ISODate("2021-04-20T20:51:21.022Z"),"updatedAt" : ISODate("2021-04-20T20:51:21.022Z"), "__v" : 0})
```
I have not tried it yet in the openshift environment.

It may be possible to use something like postman to make these changes directly in a safer way.
