### ISSUE TITLE
Strapi Database Backup and Restore implementation

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/digital.gov.bc.ca#66]
The HA mongo replica set will require care and feeding. This means we need to have ways to backup, restore and verify the data. The good news is that Rocketchat is already doing this so there should be a lot we can borrow. 

 ## Acceptance Criteria (not in order)
- [ ] backup and restore documentation created
- [ ] automated backups (and testing of backups) completed
- [ ] ansible script to restore database with backups if needed
- [ ] Architecture is documented

**Comment by parulmishra** [comment]
Questions for Backup and Restore:

1. Determining the size of the storage (and backup) as well as memory requirements for the DB: 
            a. How many total number of blogs/articles are we expecting in the DB? 
            b. Would the DB also support heavy binary files such as videos and images?
 2. Determining the frequency of backups:
            a. How many new blogs do we expect to come in every day/week/month?
            b. How far back should we hold the data in backups? - 1 month, 6 months or a year.

@patricksimonian  input required here. :)

**Comment by HeatherRemacle** [comment]
@parulmishra - I think this better fits within our Technical Excellence Epic. I converted this to an issue. It also sounds like we should have multiple related or dependent issues for the MongoDB set up as you referenced this morning. 

@Dianadec FYI

**Comment by Dianadec** [comment]
Will be considered Sprint 2.

**Comment by HeatherRemacle** [comment]
@parulmishra I believe we can check off those acceptance criteria and close the ticket, correct?
