### ISSUE TITLE
Strapi builds failing due to too many pull request

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#667]
Log of the build errors can be found here 
https://console.apps.silver.devops.gov.bc.ca/k8s/ns/c0cce6-tools/buildconfigs/strapi-pr-651/builds

https://console.apps.silver.devops.gov.bc.ca/k8s/ns/c0cce6-tools/builds/strapi-pr-651-4/logs

**Comment by parulmishra** [comment]
@thegentlemanphysicist resolved the issue with the PR https://github.com/bcgov/digital.gov.bc.ca/pull/681

**Comment by thegentlemanphysicist** [comment]
I believe this is working now.  Though I need to continue testing.

**Comment by thegentlemanphysicist** [comment]
Strapi deployments working, now I need to make certain they sitll run locally

**Comment by thegentlemanphysicist** [comment]
Local deployment still working.
