### ISSUE TITLE
Design annotated UI and navigation for Exchange Podcast teasers

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#672]
#### Acceptance Criteria
- [x] Figure out a logical place for the podcast teasers to reside on digital.gov.bc.ca
- [x] Figure out navigation (e.g. add link on homepage? to nav?)
- [x] Decide whether it makes sense for _all_ podcasts to be displayed, or only the most recent (like we're currently doing on bcdevexchange)
- [x] Wireframe is annotated for Jon so that he can create a Strapi content model to manage the content for these in Strapi

Podcast teasers should include:
- [x] image (can be uploaded by content manager)
- [x] title
- [x] description (text of the description should have options for bold and italic text)
- [x] button or link (content manager pastes Libsyn URL)

**Comment by singhinderdeep** [comment]
@mark-a-wilson Left some comments for you on Figma. Would appreciate your thoughts on them.
Otherwise, seems good to close from my end.

**Comment by mark-a-wilson** [comment]
Looks great. I'll create a separate ticket for the two illustrations that need to be made before Jon can pick up the development task.
