### ISSUE TITLE
Build React frontend and Strapi content model for Learning page (courses, events, podcast teasers

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#673]
See annotated Figma wireframes. 

Fix the email address to work for the section: Contact the Common Components team: Digital.Government@gov.bc.ca.

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist - Is this issue still blocked?

I tested in prod - the new page looks good.

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist - Disregard above comment.  I closed related blocker.

Closing ticket.
