### ISSUE TITLE
Off boarding task: Show Jon how to restore database from backup

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#692]
Make sure Jon can restore the prod database from backups if there is some kind of catastrofic failure.

**Comment by mark-a-wilson** [comment]
@thegentlemanphysicist -- do you have everything you need on this for me to close this ticket?

**Comment by mark-a-wilson** [comment]
closing this issue as meeting took place where Parul ran Jon through the process. Documentation of this process is in #728.
