### ISSUE TITLE
Create Blog Author Role

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#693]

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist - Has anybody tested this?

**Comment by thegentlemanphysicist** [comment]
This is the exact same pattern as with the Common components role.  I've tested it myself, but if you'd like someone else to QA I can create an account for them in test to verify.

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist - Thanks - if possible, I would prefer that the client that will be using the role tests it.  Here, that's probably Jaimie or someone on her team.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist - the blog function isn't active yet, so this will have to be tested later.
