### ISSUE TITLE
Offboarding task: Make sure the multiple cicd.yaml files are clearly documented

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#695]
Currently the documentation states that cicdv2.yaml "provides insight into what `Role` with delete permissions is created for each namespace."  

It is unclear why there are two of these files present.

**Comment by parulmishra** [comment]
@thegentlemanphysicist @mark-a-wilson @scchapma 

cicd.yaml and cicdv2.yaml are both used to create service accounts to enable github workflows to access openshift clusters and run workflows. 
cicd.yaml creates a service account with basic permissions to create builds, storage, configmaps, etc. as well as to deploy builds.
cicdv2.yaml creates a service account with more advanced permissions including delete. The service account created through cicdv2.yaml is used to delete/cleanup resources after a PR is completed.
The reason we have a superuser cicdv2.yaml is to ensure we don't delete things by default.
This file openshift\docs\deployment-automation.md provides all the details about the deployment automation.

**Comment by SteveChapmanBCDX** [comment]
@parulmishra - Can you add a link to the `openshift\docs\deployment-automation.md` file?

**Comment by thegentlemanphysicist** [comment]
The big distinction is that cicd.yaml has the permissions for test and prod service accounts, (no need for delete permission).  While cicd2.yaml, generates the service account permissions  needed for the dev namespace where the accounts need to be able to delete objects.
