### ISSUE TITLE
Create illustration for Podcast section on Learning page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#703]

**Comment by singhinderdeep** [comment]
![Podcast_gray.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/2dfa68c5-f13f-4cc0-9e7b-6ea0c96e8f17)

**Comment by singhinderdeep** [comment]
![Podcast_gray.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/033e161d-5d67-4067-8611-5dbaed49e46b)

![Podcast_white.png](https://images.zenhubusercontent.com/5eb1dbd03cd5665e2aefe526/650b5ed9-64a2-4b9b-bfcb-e2a0ca8cb733)

**Comment by mark-a-wilson** [comment]
very nice!
