### ISSUE TITLE
Create Strapi role for managing Common Components only

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#706]
Individuals granted this role should have full access to manage:

- CoCo Tags
- CoCos 

(these hopefully renamed to "Common Components Tags" and "Common Components", see #707 🙂)

As soon as this is created, you could invite these two individuals to TEST and PROD with that role assigned to them:

- Greg.Froh@gov.bc.ca
- Poornima.Sivanand@gov.bc.ca

Note, while doing this I should also create the blog author role. (it is minimal extra work to do this while working with the create author stuff)
Create three new roles:
CocoAdmin
BlogAuthor
LearningAdmin

**Comment by thegentlemanphysicist** [comment]
This is blocked until I am able to restore prod from backups

**Comment by thegentlemanphysicist** [comment]
I have noticed that my approach is not letting us access the media library

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist, @mark-a-wilson - Have we tested with the Common Components team?

**Comment by thegentlemanphysicist** [comment]
@scchapma We have not, we can get in touch with Greg if you'd like us to.  Their experience should not have been effected at all (we were using the editor role for them before this)

**Comment by SteveChapmanBCDX** [comment]
Yes, let's test with Greg and Poornima to make sure it works correctly.

**Comment by thegentlemanphysicist** [comment]
@SteveChapmanBCDX  Confirmed with Greg, everything's working as expected.

**Comment by SteveChapmanBCDX** [comment]
Thanks - closing ticket.
