### ISSUE TITLE
Create content for Products & Services page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#71]
**Target audience:** Any public servant 

**Desired outcome:**  Find products and services that can help them take a digital approach to service delivery.

#### Acceptance Criteria

- Add any specific acceptance criteria here, or delete this heading.

#### Definition of Done

- [x] [Content template](https://docs.google.com/document/d/1ZPV1sYVxEMiLaxjO-olx5AqyJEEmattQLOyaO1GK380/edit#) completed in Google Drive 
- [x] Content has been approved for publication by Product Owner

**Comment by mark-a-wilson** [comment]
Heather, I've drafted based on the items we identified on the [site map](https://miro.com/app/board/o9J_kslEIZ4=/?moveToWidget=3074457348088250292&cot=13). 

My approach was to try to summarize what each service is, to help the reader quickly scan and see whether it's something that might be of interest.

When I look at it now, though, this seems like a pretty selective list.

I'm not sure what the unifying thing is ... i.e. these are all "products and services" related to ______________?  Building digital applications? Or offered by __________?

**Comment by HeatherRemacle** [comment]
Looks great. Added one proposed resource RE working in the open.

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - a few questions for you in the comments in the doc about "working in the open".

**Comment by HeatherRemacle** [comment]
This is good. Let's put that "working in the open" page in the next sprint.
