### ISSUE TITLE
Infrastructure: site goes down for about a minute during deployments to test or prod

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#711]
When test or prod is deployed, the strapi app goes down for about a minute while the update happens. This should not be happening, openshift should allow us to deploy changes with zero down time

**Comment by thegentlemanphysicist** [comment]
look into Pod Disruption budgets.  Presentation was made on June 8 during the platform community meetup

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
