### ISSUE TITLE
Parul Offboarding: code climate

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#713]
Transfer code climate from private email account to team account

**Comment by thegentlemanphysicist** [comment]
Looks like code climate has been successfully turned off

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist - Do we want to use this tool?  If so, let's reinstall it using a government profile/account.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist.  In his opinion, Code Climate wasn't performing a useful function.
