### ISSUE TITLE
Offboarding Parul: Remove access

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#714]
The following apps need to have access revoked
- ~bcgov github~
- ~BCDevOps gibhub~
- ~digital.gov git repos~
- ~bcdevexchange git repos~
- ~exchange lab git repos~
- ~Marketplace git repos~
- ~Digital.gov openshift~
- ~exchange lab openshift~
- ~Market place openshift~
- other?

**Comment by mark-a-wilson** [comment]
requested removal from bcgov GitHub org membership:
https://github.com/BCDevOps/devops-requests/issues/1118

**Comment by mark-a-wilson** [comment]
requested removal of Parul from, and addition of Jon to, the OCP4 namespace for the bcdevexchange site:
https://github.com/BCDevOps/devops-requests/issues/1119

**Comment by thegentlemanphysicist** [comment]
Blocked until I get admin access to BCDevExchange in openshift.

**Comment by SteveChapmanBCDX** [comment]
This has been completed.  Closing ticket.
