### ISSUE TITLE
Set up reverse proxy for Digital Trust WP site

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#718]
#### Acceptance Criteria
- [x] The Digital Trust WP site is running at **https:digital.gov.bc.ca/digital-trust**

**Comment by thegentlemanphysicist** [comment]
Link to reverse proxy too:
https://bcdigitaltrust.info/
It will require a username and password until it goes live.

**Comment by thegentlemanphysicist** [comment]
I've set up test proxy in the dev environment for the digital trust people to play with.  (5 minutes of work to give them something to test against)

**Comment by thegentlemanphysicist** [comment]
https://digital-gov-frontend-pr-781-c0cce6-dev.apps.silver.devops.gov.bc.ca/ is reverse proxied to handle digital-trust route.
See PR #781

**Comment by SteveChapmanBCDX** [comment]
Work completed in Jan 2022 - closing ticket.
