### ISSUE TITLE
Provision Openshift namespaces

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/digital.gov.bc.ca#72]
## Acceptance

- [x] request for namespace completed at https://github.com/bcdevop/devops-requests/issues/choose

- [x] namespaces created

- [x] @parulmishra @patricksimonian @ryleyw granted edit access (or higher) @HeatherRemacle should probably be granted admin, other team members can be granted view/edit as needed

**Comment by thegentlemanphysicist** [comment]
pending response

**Comment by thegentlemanphysicist** [comment]
The request has been submitted, they would like an estimate on the load we can expect.  @HeatherRemacle

**Comment by HeatherRemacle** [comment]
I think this is done?
