### ISSUE TITLE
Make app fail gracefully in internet explorer browser

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#722]
Currently the app crashes when IE attempts to use it.  There should be a graceful failure informing the user which browsers are supported.

**Comment by SteveChapmanBCDX** [comment]
This link shows how to redirect client from IE to Edge.  This may be an elegant solution to the IE issue.  https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge

**Comment by thegentlemanphysicist** [comment]
I will start the research on this while waiting on the design.

**Comment by thegentlemanphysicist** [comment]
There is a PR up with the fall back coded.  Once designs are completed it can be added to the ie.html file. 
https://digital-gov-frontend-pr-782-c0cce6-dev.apps.silver.devops.gov.bc.ca/
When a user visits this deployment from the IE browser they are redirected to the page "HELLO IE USER"

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist at standup.  Change to be migrated to Prod.

Closing ticket.
