### ISSUE TITLE
Write document for mongo db manual backup and restore

### ISSUE THREAD

**Issue by parulmishra** [bcgov/digital.gov.bc.ca#728]

**Comment by parulmishra** [comment]
[https://app.zenhub.com/files/223664506/c2f0f7fd-3728-4993-ba54-6503f99440fb/download](https://app.zenhub.com/files/223664506/c2f0f7fd-3728-4993-ba54-6503f99440fb/download)

**Comment by parulmishra** [comment]
@scchapma @mark-a-wilson @thegentlemanphysicist @nmathava 
Added the document with this issue for the manual process to take the backup and restore the mongoDB.

**Comment by SteveChapmanBCDX** [comment]
Required Steps:

![image](https://user-images.githubusercontent.com/36771389/118051109-4bb93680-b335-11eb-8d92-2e70895134cc.png)

**Comment by SteveChapmanBCDX** [comment]
Required steps (from Parul's document):

![image](https://user-images.githubusercontent.com/36771389/118051213-75725d80-b335-11eb-9af8-a904149cf215.png)

**Comment by parulmishra** [comment]
Also there is a video that shows the whole process 
https://bcgov-my.sharepoint.com/personal/jonathan_sharman_gov_bc_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjonathan%5Fsharman%5Fgov%5Fbc%5Fca%2FDocuments%2FRecordings%2FKT%2D%20Database%2D20210510%5F140531%2DMeeting%20Recording%2Emp4&parent=%2Fpersonal%2Fjonathan%5Fsharman%5Fgov%5Fbc%5Fca%2FDocuments%2FRecordings&originalPath=aHR0cHM6Ly9iY2dvdi1teS5zaGFyZXBvaW50LmNvbS86djovZy9wZXJzb25hbC9qb25hdGhhbl9zaGFybWFuX2dvdl9iY19jYS9FYlJISmlMdUFXeEdoWHF2MUxYY0haa0JSMWxubldUZTVNTEhJM0tPVTE0NGNBP3J0aW1lPWlpdlBqVGdXMlVn
