### ISSUE TITLE
Design Incompatible browser fall back page

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#731]
When a user visits the site from an unsupported browser, they should have a page that tells them why the app isn't working.  
AC:
- design a beautiful page for Jon to implement

**Comment by singhinderdeep** [comment]
Figma file https://www.figma.com/file/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=4927%3A1
Please review

**Comment by SteveChapmanBCDX** [comment]
@singhinderdeep - The design looks really good.  No comments.  Closing this ticket.
