### ISSUE TITLE
Set up emergency fall back incase Marketplace 

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#735]
Goal of this ticket: minimize site disruption if something goes wrong.
Is there a point of contact and maintenance contract of any kind with the team that originally built the Marketplace site?

Write a fall back plan incase the current dev breaks something critical and the site needs to be recovered.

Also good to know what times the site has minimal activity, to ensure minimal disruption to operation if something goes wrong.

**Comment by thegentlemanphysicist** [comment]
Got in touch with Jeff, if something goes wrong in the next week he can point back at the old wordpress url

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist - Thanks for setting up a Plan B.  Closing this ticket.
