### ISSUE TITLE
Keycloak Prod (Digital Marketplace) - Add digital.gov url to whitelist on marketplace  site to allow reverse proxy testing

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#736]
Once Jon is onboarded to Marketplace project, there is a check in place that only allows users directed from `digital.gov.bc.ca/marketplace` to see the content of the site.  If we add an env variable that includes the `https://digital-gov-frontend-prod-c0cce6-prod.apps.silver.devops.gov.bc.ca/` url then include that url in the allowed origins list.  We should be able to test the reverse proxy.

**Comment by SteveChapmanBCDX** [comment]
Patrick already has set this up for the Test Keycloak realm.  This ticket is for the Prod Keycloak realm for Digital Marketplace.
