### ISSUE TITLE
Update cicd.yaml and cicd2.yaml templates

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#741]
During the process of fixing the docker image pull error the permissions of the service accounts used by the digital.gov.bc.ca app have been modified.  These changes are no longer reflected in the cicd templates.  
In order to keep the project in line with dev ops best practices the templates must be update so that they can be used to re-generate the necessary service accounts.

**Comment by thegentlemanphysicist** [comment]
Several things to add
- rename cicdv2 to something more descriptive like 'cicd-clean-up-sa'

**Comment by thegentlemanphysicist** [comment]
meeting scheduled for tomorrow with patrick

**Comment by thegentlemanphysicist** [comment]
Meeting was useful, going to focus on some small tickets at the start of the sprint.

**Comment by thegentlemanphysicist** [comment]
Testing notes
-deployment to dev and test still works with these permission. deployment of strapi still works to dev and test
-deletion script still works
-closing test deployment pr does not cause clean up scripts to run

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist - he reviewed the two cicd files and combined them into a single cicd file.

Closing ticket.
