### ISSUE TITLE
Reverse Proxy: Create in Test Environment/Namespace

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#745]
#### Description of Task 

- We need to test the Caddy reverse proxy before promoting to prod.  This will require the dev environment for `digital.gov`, the test environment for `marketplace` and the test namespace for `marketplace`.

Set up caddy to implement a reverse proxy from digital.gov.bc.ca -> marketplace (using same functionality as the current nginx reverse proxy uses).

Direct traffic from:
url/marketplace/* to be handled by the marketplace app

Direct non /marketplace/ traffic to our digital.gov site.

This is done by modifying the react deployment config file (/openshift/templates/react-frontend/dc.yaml) where the caddy file is defined.

Steps:

- get digital-marketplace-test reverse proxied to digital-dev/marketplace
- set the ORIGIN url on digital-marketplace-test set to digital-dev/marketplace to confirm the reverse proxying works as expected.

#### Acceptance Criteria 

- The new reverse proxy (included in Caddy file) works exactly the same as the existing nginx reverse proxy works.  This means that all marketplace traffic (URL of form digital.gov.bc.ca/marketplace/*) is directed to the marketplace application.  All other traffic for the digital.gov.bc.ca URL is directed to the digital.gov application.

#### Definition of Done

- [ ] Proxy test in test environments pass

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist - moving to Sprint Backlog.

**Comment by thegentlemanphysicist** [comment]
This is currently blocked until openshift is back to a stable state.

**Comment by thegentlemanphysicist** [comment]
Testing notes: this proxy will need to be tested pretty extensively.  Maked sure all the marketplace funcitonality still works.
 -login via keycloak (by idir and non idir users)
 -broswing all parts of the app still works

There are two more todo's with this ticket.
- document the process
- configure the reverse proxy such that we can change ORIGIN it points at depending on the namespace 
dev   -> ?
test   -> test
prod -> prod

**Comment by thegentlemanphysicist** [comment]
I've been testing this, login via keycloak is not working.  I believe the proxy is not handling the queries sent to the backend properly.
`<a href="/marketplace/auth/sign-in?provider=idir" tabindex="0" class="a d-inline-flex align-items-center flex-nowrap btn-primary position-relative btn btn-md " rel="external">Sign In Using IDIR</a>`
The `?provider=idir` is not being handle properly.  I believe the same is happening on all queries.
For example:
`https://digital-gov-frontend-pr-744-c0cce6-dev.apps.silver.devops.gov.bc.ca/marketplace/api/organizations?page=1&pageSize=20`
Should return a list of test organisations.  Instead it returns nothing.  

The nginx proxy used the line 

`proxy_pass https://app-digmkt-prod.apps.silver.devops.gov.bc.ca$1$is_args$args;`

To pass these params.  My next todo is to get this working in our proxy

**Comment by thegentlemanphysicist** [comment]
Resolved.  This brought to light some of the issues with Keycloak.  I'll need to be getting access to the https://test.oidc.gov.bc.ca/auth/realms/p2zhow64 Keycloak realm (we should also offboard people who shouldn't have access anymore)

**Comment by thegentlemanphysicist** [comment]
This is now in test and can be tested here:
https://digital-gov-frontend-test-c0cce6-test.apps.silver.devops.gov.bc.ca/

**Comment by thegentlemanphysicist** [comment]
Last thing to test is the email notifications, to do this I need someone with access to create an oportuninty in the test environment

**Comment by thegentlemanphysicist** [comment]
As recommended by Andrew Sutherland we tested the links generated in emails sent out by the site in the test environment.  All links had the correct url for example 
https://digital-gov-frontend-test-c0cce6-test.apps.silver.devops.gov.bc.ca/marketplace/opportunities/sprint-with-us/1ed3ee48-865b-4d2e-be2c-ffc3e9c25b16
