### ISSUE TITLE
Reverse Proxy:  Promote to Prod

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#749]
#### Description of Task 

- Promote Reverse Proxy to Prod
 
Set up caddy to implement a reverse proxy from digital.gov.bc.ca -> marketplace (using same functionality as the current nginx reverse proxy uses).

Direct traffic from:
url/marketplace/* to be handled by the marketplace app

Direct non /marketplace/ traffic to our digital.gov site.

This is done by modifying the react deployment config file (/openshift/templates/react-frontend/dc.yaml) where the caddy file is defined.

Steps:

- Promote the caddy file to prod and reverse proxy digital-marketplace-prod reverse proxied to digital-prod/marketplace
- Have the "digital.gov.bc.ca" switched over to our prod site. Confirm the site is live and that the marketplace url is working

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- New reverse proxy works in Prod

#### Definition of Done

- [ ] All tests (unit/functional/security/code cov.) pass
- [ ] Code review has been done
- [ ] Pipeline builds
- [ ] PO signs off on the build

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist - moving to Sprint Backlog.

**Comment by thegentlemanphysicist** [comment]
The reverse proxy code is currently in prod. It had to get pushed up in order to insure the deployment config was bug free.

**Comment by SteveChapmanBCDX** [comment]
Reviewed and signed off - closing ticket.
