### ISSUE TITLE
Reverse Proxy:  Migrate to Test Environments

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#755]
#### Description of Task 

Once the new Caddy reverse proxy has been tested in the Dev environments, it needs to be tested in the Test environments/namespaces (for both Digital.gov and Digital Marketplace).

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- Test against all existing Digital Marketplace routes
- Test against Digital Marketplace KeyCloak instance (the Digital.gov test URL has already been added to KC whitelist)

#### Definition of Done

- [ ] All tests (unit/functional/security/code cov.) pass
- [ ] Code review has been done
- [ ] Pipeline builds
- [ ] PO signs off on the build

**Comment by bdolor** [comment]
resovled in https://github.com/bcgov/digital.gov.bc.ca/pull/781
