### ISSUE TITLE
[CONTENT] Working in the Open

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#76]
Target audience (_Who is this content for?_): General BCPS employee seeking to apply digital principles

Desired outcome (_What do we want this content to help the reader understand or do?_): 

As a BCPS employee, I can understand why there is an expectation to work in the open and what some of the methods are for doing so. 
I can also understand when it is appropriate to not work in the open.
I can learn about others' experience doing so and what the benefits were.

#### Acceptance Criteria

- About about working in the open links to the digital principles
- There are clear statements that explain why working in the open helps deliver better public service.
- There are links to stories that help generate deeper understanding - inside the BCPS and elsewhere
- There is a section that describes the kinds of tools BCPS employees can use to work in the open - both internally across the public service (e.g. @Work, MS Teams, SharePoint) and externally (e.g. Github). 
- There are short vignettes that illustrate how to use these tools.
- There is a link to a discussion space for people to share their experience on @Work

#### Definition of Done

- [ ] Content template completed in Google Drive; link included 
- [ ] Content has been reviewed by someone other than the writer(s) (another team member, or a government employee outside our team) 
- [ ] Content has been approved for publication by Product Owner

#### Process

* **Assignee** - In the Google Drive [Content folder](https://drive.google.com/drive/u/2/folders/1YezB6ZLpTqun9Gb8tSf3bU81vhB5MZtL), make a new document from the document called ****Content Writing Template**** (right click > Make a Copy). After 1 and 2 of DOD are complete, move Issue to the 'For PO to Review' column
* **Product Owner** - If content is approved with no revisions necessary, move Issue to the 'Closed' column. If revision required, make comments in the Google Doc and move Issue back into the 'In Progress' column, and @tag the assignee.

**Comment by mark-a-wilson** [comment]
Stale task. "Content about Working in the Open" is in the feature wishlist on MIRO Roadmap board (linked to Epic #109).
