### ISSUE TITLE
Clean up config maps in dev namespace on PR close

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#761]
Currently when a pr is closed the artifacts in the dev namespace are deleted.  However the config maps were forgotten. As a result there are hundreds of config maps in the dev namespace that are taking up space.
AC

1. delete the unused config maps
2. and the config maps to the code artifacts that get deleted when a PR is closed in dev

**Comment by thegentlemanphysicist** [comment]
Tested this with a dummy PR, config maps got cleaned up.

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
