### ISSUE TITLE
Access to all of the keycloak realms

### ISSUE THREAD

**Issue by nmathava** [bcgov/digital.gov.bc.ca#771]

**Comment by thegentlemanphysicist** [comment]
Working through this. What needs to be done:
- Get @thegentlemanphysicist added as the techincal lead
- Set up a meeting between @thegentlemanphysicist, @SteveChapmanBCDX and the SSO team so that we can get onboarded onto the keycloak realms.

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist and I met with the SSO team yesterday.  Signing off this item.
