### ISSUE TITLE
Get IDIR login working with keycloak login

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#773]
Currently attempting to login using idir credentials fails for Jon.

Submit an issue to github keycloak team to get this fixed for jsharman

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist - Has this been sorted out?

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist at standup.  He advises that the issue syncing his vendor IDIR and government IDIR has been resolved.

Closing ticket.
