### ISSUE TITLE
Turn on the site

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#775]
Request the vanity url get changed over from existing word press site to our prod site.
- do this when there are no active procurements in the digital marketplace app
- go through Paruls correspondence  with the existing hosts of the site. (GDX I believe)
- Go live
- Test the live site, make certain everything works.

**Comment by thegentlemanphysicist** [comment]
Comment from Parul's offboarding: Once the reverse proxy is set, you can reach out to digital.gov wordpress site team and tell them the IP address of our prod env and they will point their DNS to our IP address. The usual approach

**Comment by thegentlemanphysicist** [comment]
Sent email to the GDX contact to clarify next steps.

**Comment by thegentlemanphysicist** [comment]
There is a PR up with the fall back coded.  Once designs are completed it can be added to the ie.html file. 
https://digital-gov-frontend-pr-782-c0cce6-dev.apps.silver.devops.gov.bc.ca/
When a user visits this deployment from the IE browser they are redirected to the page "HELLO IE USER"

**Comment by thegentlemanphysicist** [comment]
- The login as a vendor works
- The login as a gov employee works
- The Navigation to the different tabs works
- TEST CREAT AN OPORTUNITY
- TEST GETTING AN EMAIL NOTIFICATION WHEN CREATING AN OPORTUNITY

**Comment by SteveChapmanBCDX** [comment]
Testing complete, no issues.  Closing this ticket.

@thegentlemanphysicist - Great job on hard ticket!
