### ISSUE TITLE
remove "Teams" icon from common components cards

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#776]
The "number of teams using this common component" is a piece of data that is very unlikely to be kept track of and included when publishing. We are handling this well on the detail page: if it is included, the feature appears; if not included, it doesn't.

But on the card, it isn't good to have the icon with a question mark. 😬

![labels.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/5d230bb6-d8b9-4aa9-80b2-868d1aec7816)

#### Acceptance criteria
- [ ] teams icon no longer appears on the card
- [ ] the other three icons remain on the card, spaced evenly

**Comment by mark-a-wilson** [comment]
@gfroh - based on the feedback you've been supplying me with, would completing this issue be sufficient for MVP release of common components?

**Comment by poornima-sivanand** [comment]
@mark-a-wilson : Ignore if not possible, but is the icon a definite present or not present, and not something like, it is present if value available? If it has to appear as a question mark, yes it does make sense to not include it right now and go ahead with the resolution of this issue.

**Comment by mark-a-wilson** [comment]
Thanks for reviewing, @poornima-sivanand. 

@thegentlemanphysicist -- would this be a lot of effort?:

#### Acceptance criteria:

1. Teams icon displays if data has been entered
2. Teams icon does not display if no data has been entered
3. All icons are evenly spaced across bottom of card, regardless of whether displaying 3 or 4

**Comment by SteveChapmanBCDX** [comment]
The Common Components team has decided, for now, to cover up the icons block entirely (see issue #805).  

We can revisit the required logic for the "Teams" icon in the future.

Closing the ticket.
