### ISSUE TITLE
design an alternative to Ministry wordmarks (logos)

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#778]
#### The issue (from user feedback)
In the "Who else is using this?" section on common components, the only logos being used are ministry word marks. The name of the ministry (font in the word mark) is small and hard to read. It is also not very compelling visually to see the BC Gov sunset repeated so many times on the same page — seems like overkill.

#### Acceptance criteria
- [ ] create a wireframe to show one or more alternative designs ideas for how to display the ministry name for each "Who else is using this?" item

**Comment by singhinderdeep** [comment]
Updated the logo design in the wireframes. Please refer to Logo-update frames in https://www.figma.com/file/XPe01CLbBIUuIaUJRHGOM8/CoCo?node-id=1606%3A209

**Comment by SteveChapmanBCDX** [comment]
Reviewed.  Changes look good.  Closing ticket.
