### ISSUE TITLE
review user feedback on Strapi UX

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#779]
We have received some constructive feedback on the UX of Strapi for the common components content.

#### Acceptance Criteria
- [x] review [this recording](https://bcgov.sharepoint.com/:u:/t/00109-digital.gov.bc.ca/EWfbqzePzzZBvdhjL_G9O10BX1NolVjBoDB_M5YLCnNgvQ?e=QVkAhO) of user feedback provided on the UX of Strapi
- [x] design + developer discuss issues that were identified and what improvements are possible
- [x] create ZenHub tickets/GitHub issues for enhancements that could be considered by PO for future sprints, each with Acceptance Criteria

**Comment by singhinderdeep** [comment]
Tickets have been created for all the enhancements required and mapped to the relevant Epic.
