### ISSUE TITLE
Migration of Exchange Lab page on @Work

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#797]
#### Description of Task 
There's a wealth of information currently stored on the Exchange on the @Work site.
Unfortunately, the @Work site will be taken offline soon (July 30, 2021),

Let's plan to migrate these resources over to the Digitial.gov.bc.ca site.

Requirements:
* Meeting among Ari, Mark, Inderdeep, Steve to determine how to add content to the Digital.gov site (options include using current patterns or developing new ones).

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)
- [ ] Work with Ari and design the wireframes

**Comment by mark-a-wilson** [comment]
@SteveChapmanBCDX, 

Summary of meeting with Ari on June 24:

- Ari will ensure all content on @Work is scraped and saved.
- No action required by the digital.gov.bc.ca team at this time.
- As the Learning page and Blog features are released on digital.gov.bc.ca, we will touch base with Ari to reassess whether any of the saved @Work content should be republished on digital.gov.bc.ca and define any new work in the Backlog for prioritization.

Propose this issue be reestimated as a 0.5 and closed.
