### ISSUE TITLE
Add testing to developed strapi features

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#803]
Currently there is no way to test features built in the strapi codebase.  Goal enable unit testing for strapi code. Specifically the eventbrite api integration implemented in #799

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- [ ] Setup testing framework for Strapi functions
- [ ]  Write tests for the Eventbrite function

**Comment by thegentlemanphysicist** [comment]
This is causing too many issues se issue #961 for implementing this after the postgres migration

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist - Closing.
