### ISSUE TITLE
Add a title image and description to the site so that url previews have a logo

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#804]
Currently when we share the url link we get a preview image
![image.png](https://images.zenhubusercontent.com/5e66cb541c5fcd60e21b8c1a/9e48f61e-3109-4ed1-8dc0-79d67b7fe0b6)
We should have a proper preview icon and probably a better tag-line than 'Website created using create react app"

**Comment by SteveChapmanBCDX** [comment]
Tested in Teams.  Fix looks good.  Closing ticket.
