### ISSUE TITLE
Common Components Page - Recommendation on "Free/Paid" Icon

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#806]
#### Audience

Business areas have asked us to remove this icon, at least for now.  But users have asked for it (see PO client engagement on Common Components project).  What to do?

#### Desired outcome (_What do we want this content to help the reader understand or do?_):

Let's engage with Greg Froh and the Common Components team to get their advice here.  Catherine has asked for our recommendation on this point.

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)

- Prepare recommendation for Catherine

#### Definition of Done

- [x] Recommendation complete
- [x] Recommendation reviewed with Catherine

**Comment by mark-a-wilson** [comment]
Presented a recommendation via a Teams chat with Catherine, Steve and Greg. Awaiting Catherine's response on the recommendation.

**Comment by SteveChapmanBCDX** [comment]
@mark-a-wilson - Catherine approved so long as Greg is happy with this.  Let's confirm with Greg, if we haven't already.

**Comment by SteveChapmanBCDX** [comment]
Comment from Catherine on verbiage:

"I don't know how locked in we are to wording... but also free does not sound exactly right to me,  something more along the lines of no cost to consume... or no cost to implement, is likely more accurate, but don't want to hold something up for that kind of small nuance... I'll leave it up to you to figure out how people like to consume the information... just  cognizant of the fact that these services all have costs... is just a matter of who pays for them."

> them"

**Comment by SteveChapmanBCDX** [comment]
@mark-a-wilson - Can you confirm that Greg has signed off on your recommendation?

**Comment by mark-a-wilson** [comment]
@SteveChapmanBCDX -- Greg has confirmed we don't need to bother with restoring the tags to the cards for now (our recommendation) .... this design can be revisited later.
