### ISSUE TITLE
As a visitor, I can trust the Authority of the website and know who to contact (about us page)

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#81]
It should be clear who is maintaining this website, contributing to the development of it, and who to call for clarity, help or feedback.

**Comment by rumoncarter** [comment]
@HeatherRemacle, acknowledging this is a picky question and I generally get the point of the issue, what's a "program lead"?

**Comment by mark-a-wilson** [comment]
Stale epic. Added "About Us content" to the feature wish list section on the MIRO Roadmap board (linked here).
