### ISSUE TITLE
Design page(s) for new "Hosting Options" content

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#816]
Request from Greg Froh of Common Components team:

[Yesterday 4:52 p.m.] Froh, Greg CITZ:EX
    Chernoff, Catherine CITZ:EX and Chapman, Steve CITZ:EX - what would be involved in getting the content in Word doc below posted to digital.gov.bc.ca ?

Not as part of common components, more likely under Resources:
https://digital.gov.bc.ca/resources

In fact, would probably best replace this:
(and strategy PDF would then be linked from Hosting and App Dev resources page)

[Hosting Options Navigator Webpage - web content_FINAL.docx](https://bcgov.sharepoint.com/:w:/t/00109-digital.gov.bc.ca/ETDdkdU79GNCtp8-SgQUfvgBN4bzPNAMW2OJlS4cvlYsTQ?e=sOdSZ6)

#### Definition of Done
- [x] Consult with Greg Froh on where to lay this new content out on the site and its relation to the existing Hosting & Application Development Strategy card on the Resources page
- [x] Update wireframes
- [x] Check wireframe with Greg

**Comment by SteveChapmanBCDX** [comment]
@mark-a-wilson - Can you add this to the next sprint and notify Greg when this has been resolved.  I'm supportive of however you want to handle this one.

**Comment by mark-a-wilson** [comment]
Updated [wireframes](https://www.figma.com/file/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=5527%3A10607) and checked with Greg -- he's good.
