### ISSUE TITLE
Integrate strapi content and eventbrite API

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#817]
This ticket sets up a cron job that populates the strapi CMS with eventbrite data. It is associated with #799.
AC
- Add event content type to strapi
- create cron job that runs once a day and pulls content from the eventbrite API
- if event is no longer live delete it otherwise create/update teh event
- Add a cron job to the strapi deployment config so that the job is only run once  for the app.

**Comment by thegentlemanphysicist** [comment]
This was merged in with #799 .
I will deploy to test to make certain everything is working smoothly

**Comment by thegentlemanphysicist** [comment]
This change is currently in test. The job will run over night, so tomorrow we can make sure everything is running properly.

**Comment by SteveChapmanBCDX** [comment]
@thegentlemanphysicist - Have you tested this in Test?

**Comment by thegentlemanphysicist** [comment]
@SteveChapmanBCDX  Shoot, found a bug in test, should be a quick fix, but I'll feel better if it's handled before pushing to prod.

**Comment by thegentlemanphysicist** [comment]
Fixed the bug, just waiting for it to re-deploy before merging into develop and deploying to test and prod.

**Comment by thegentlemanphysicist** [comment]
It is running without errors in test environment.

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
