### ISSUE TITLE
Improve quality of site logo

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#822]
#### Issue
We are currently using a low-res .png for our site logo. It is very poor quality when zoomed in on:

![site logo.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/68ab7e41-5708-437c-afc9-0ccb5828e59e)

#### Acceptance Criteria
BC Gov logo is sharp when zoomed in on, on both desktop and mobile screens

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
