### ISSUE TITLE
Collection type title should match in sidebar and main page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#826]
#### Issue
It doesn't make sense to a content manager why these titles wouldn't be the same?

![match.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/a990ff15-8699-4269-92a8-17a5e57c5e17)

#### Acceptance Criteria
- [x] Title on the list for the collection type matches the title that's displayed in the sidebar

**Comment by thegentlemanphysicist** [comment]
see pr #859

**Comment by mark-a-wilson** [comment]
Jon explained to me that Strapi auto-creates the label for the Collection Type based on the title that has been manually created. The AC has been met as best it can by #859.

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
