### ISSUE TITLE
Getting the project running locally is having some issues with strapi and react

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#831]
After helping @mark-a-wilson start the project locally we noticed two issues that need to be fixed
- Strapi plugin libraries don't get installed during the `docker-compose build` and `docker-compose up` runs.
- The react packages don't get installed properly during the build and up commands.

AC: Make certain the project starts successfully on a fresh machine using only these two commands.

**Comment by SteveChapmanBCDX** [comment]
Reviewed - closing ticket.
