### ISSUE TITLE
SPIKE:  Move database from mongo to postgres

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#837]
Strapi seems to be moving away from mongo support in version 4.  It may be a good idea to swap over our content.

**Comment by SteveChapmanBCDX** [comment]
Good idea - let's spike this to get a sense of the risk and time commitment here.

**Comment by thegentlemanphysicist** [comment]
@steve

**Comment by SteveChapmanBCDX** [comment]
Reviewed - closing ticket.
