### ISSUE TITLE
[CONTENT] Digital Framework

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#84]
As a **BC Public Servant**, I want to **learn about the Digital Framework**.

#### Acceptance Criteria

- [x] Office of the Chief Digital Officer provides any updates that should be made to the Digital Framework content originally published

#### Definition of Done

- [x] [Content template](https://docs.google.com/document/d/18TVH89DAnFVTchT1mTbR0WTkCslzxRjAUudacAsO-qY/edit) completed

**Comment by mark-a-wilson** [comment]
Just spoke to Danny on this. He will speak to Jaimie about this and get back to us in the next few days. His sense is that Jaimie will not want us to publish the old(original) Framework content, as they are underway on a new version of it. If we want to publish Framework content ASAP, it might look kind of minimal, with a contact address for site visitors who want to learn more about the work underway.

**Comment by Dianadec** [comment]
@mark-a-wilson is this considered a Sprint 2 milestone card? As in, can I label it with the Sprint 2 milestone? Just checking for tracking purposes. Thank you

**Comment by mark-a-wilson** [comment]
Sure -- it wasn't originally in our Sprint Backlog, but I ran out of stuff to do, and this one is done now.

**Comment by mark-a-wilson** [comment]
Moving this to Closed as, based on discussion at standup today, Heather doesn't need to review the content to approve (we're just publishing the old content).
