### ISSUE TITLE
Renew Istore order - Digital.gov.bc.ca SSL

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#841]
digital.gov.bc.ca SSL is expiring very soon. (Jul 22)

-bcdevechange (dev, test, and prod) needs it's ssl certs renewed (Aug 25)
-We also need to renew the SSL used for both the react and strapi apps in dev, test and prod namespaces. (Aug 25)

**Comment by nmathava** [comment]
[https://app.zenhub.com/files/223664506/910c7a69-8318-41c8-8e6e-dff4a2b762cf/download](https://app.zenhub.com/files/223664506/910c7a69-8318-41c8-8e6e-dff4a2b762cf/download)

**Comment by thegentlemanphysicist** [comment]
Istore request submitted for digital.gov

**Comment by SteveChapmanBCDX** [comment]
SSL has been renewed until July 22, 2022.  Closing ticket.
