### ISSUE TITLE
Client Engagement - One-Page Information Page (About page)

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital.gov.bc.ca#845]
Talked to Mark and Inderdeep about creating some summary information about the publication process for business areas.

Draft list of elements:
* Client intake - business outcomes
* Service design workshop with clients to design presentation (look and feel)
* Introduce them to Strapi and how to modify the content
* Content review (where required)

Form of this content (e.g., one-page document, video, graphics) left to discretion of Mark and Inderdeep.

#### Acceptance Critera / D.O.D.
- [x] Create a 1st draft of this information
- [x] Steve edits/approves the draft
- [x] Draft is shared with Digital Investment Board staff (Parisa & Lenore) and their feedback is elicited on how to improve it

**Comment by mark-a-wilson** [comment]
@singhinderdeep , @SteveChapmanBCDX -- I'd propose ultimately including this info as part of an 'About' page on the website (a link in the footer nav would be added).

Here's a 1st draft for your comments and edits:
https://bcgov.sharepoint.com/:w:/t/00109-digital.gov.bc.ca/ET8OLMnM62hEgVQT9NkiU_IBYJaBGp6JxJj3XCEchccfuw?e=TUvA0R

**Comment by SteveChapmanBCDX** [comment]
@mark-a-wilson - The draft looks good.  I made some changes and add a comment for you to review.

Once you have reviewed the comment, I think it's fit to be used with the new DIO project.

**Comment by mark-a-wilson** [comment]
Sent draft to Lenore and Parisa for feedback.

**Comment by mark-a-wilson** [comment]
Now waiting for feedback from Sia Agriwal.

**Comment by mark-a-wilson** [comment]
Feedback received was that the content looks good. This content could be used for an **About** page, as part of #871.
