### ISSUE TITLE
Make Common Components cards display in alphabetical order

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#847]
#### Issue
Currently on the Common Components index page, the cards display in the order in which they were created. Because the list is not alphabetical, it seems 'random', and it makes it harder for a user with a particular component name in mind to scan the page to find what they're looking for. 

#### Acceptance Criteria
- [x] Common Components cards display in alphabetical order (by Name), regardless of when the data was created.

**Comment by thegentlemanphysicist** [comment]
See PR 859

**Comment by mark-a-wilson** [comment]
Cards displaying in alphabetical order now #859

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
