### ISSUE TITLE
Renew BCDevExchange SSL

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#849]

**Comment by thegentlemanphysicist** [comment]
The new ssl cert has been requested at a 'Normal' priority.  csr file has been submitted and a new secret has been added to the prod environment for when we get the cert installed.

**Comment by thegentlemanphysicist** [comment]
The istore requires csr's not be generated until a month before renewal, meaning this is on hold until july 26 2021

**Comment by SteveChapmanBCDX** [comment]
Reviewed - certificate extended to August 26, 2022.
