### ISSUE TITLE
As a BCPS employee, I can learn about how digital-era public services are delivered (Case Studies)

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#85]
## Problem

BC Public Service employees and partners that have been working in traditional delivery models may not see the value of learning and adopting new approaches without sensing the improvement to team function and service delivery that occurs. There needs to be a sense of urgency to promote the change. 

It is also hard to understand the application of a variety of new approaches and when and where they should be applied, particularly in the public sector context.

## Hypothesis

If the results that can be achieved by adopting digital approaches are clearly articulated, as well as the ways they were applied, then people will better understand what they should consider and do next to adopt these approaches for their service delivery.

## Outcomes

- More demand for digital service delivery training, support and resources. 
- Connections between public servants who can learn from each other.
- Talent attracted to working for and with the BC Public Service.

## Acceptance Criteria - 
- Show the case studies that currently exist on the site and add one new one
- Answer "why, what and how"
- Include at least one image
- If possible, include an image of the team that delivered the service
- Build a design that we can implement using Strapi in a future iteration (contemplate a blog function)

**Comment by rumoncarter** [comment]
Slight - but important IMO - tweak to language in this issue title. Any explanation required, let me know.

**Comment by HeatherRemacle** [comment]
Note - this stuff needs to be coordinated between devs and design
