### ISSUE TITLE
GetStartedSteps data doesn't display anywhere on frontend

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#852]
#### Issue
In the Common Components Strapi model, there is a field labeled **GetStartedSteps**. In the data, the content manager has been entering instructions in this field—for example, here's what's entered for **BC Express Pay**:

![image.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/e7c3a9ec-eedf-4b4e-a1ad-4e1e06f68c88)

However, this data doesn't display anywhere on the frontend. (Somehow we've never noticed this before.)

#### Acceptance Criteria

- [x] Data entered in the GetStartedSteps field displays _before_ the boilerplate paragraph under the **Getting started** heading:

![getstartedsteps.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/728fd034-6f66-43a0-b31c-63e95b35df3d) 

- [ ] Implement frontend test that guarantees when this data is provided it is rendered on the frontend

**Comment by thegentlemanphysicist** [comment]
see pr #859

**Comment by mark-a-wilson** [comment]
This data is now displaying on the frontend as desired #859

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
