### ISSUE TITLE
Add navigation and Homepage card for Learning

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#854]
The Learning page has been built (#836) and is ready to be promoted to production, but we do not have any way to navigate to that page yet.

#### Acceptance Criteria 
- [x] Add **Learning** link to navbar, after Case Studies and before Marketplace
- [x] Remove the "Learn from Others" heading on the homepage
- [x] Add a third card in the final row of cards, after Case Studies: 

![image.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/d2fa85f2-7bd9-4086-b3c3-b56faa263472)

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
