### ISSUE TITLE
[CONTENT] Products and Services

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#87]
As a **current or potential Product Owner**, I want to **navigate the services and products** that will help me get started building a team and product.

#### Acceptance Criteria

- [ ] A new PO should understand if they are ready to start accessing the services (where are they at in their journey?)
- [ ] Do user research on the content designed so far and make sure that the products and services described make sense to a non technical person. 
- [ ] Reference the readiness criteria the DRU uses to create alignment with the organizational process - we want some consistency there.
- [ ] Link to a hand out that describes readiness (PDF)

#### Definition of Done

- [x] [Content template](https://docs.google.com/document/d/1TI0hHSvGrgidBWyILvdJwrqrEx1ccm6l_J0KX_GfyYw/edit) completed
- [ ] Content has been approved for publication by Product Owner
- [x] Test draft with users

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - could you take a look at the direction I'm taking with [this draft](https://docs.google.com/document/d/1TI0hHSvGrgidBWyILvdJwrqrEx1ccm6l_J0KX_GfyYw/edit#)? See questions in the comments. Thanks!

**Comment by Dianadec** [comment]
Should be updated to be included in Sprint 3 backlog.

**Comment by mark-a-wilson** [comment]
Have completed a draft and sent to 9 folks for some feedback (see [here](https://drive.google.com/drive/u/2/folders/1Tg2AQ9qR2TPvnz63ZL02WH3ZrD6EIJfA)). Sticking this in 'Blocked' while I wait.

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - please review [my latest redraft](https://docs.google.com/document/d/1TI0hHSvGrgidBWyILvdJwrqrEx1ccm6l_J0KX_GfyYw/edit#), which is in response to [feedback](https://drive.google.com/drive/u/2/folders/1Tg2AQ9qR2TPvnz63ZL02WH3ZrD6EIJfA) I received from 5 government users on the previous draft .

**Comment by HeatherRemacle** [comment]
I have made updates and worked this through with @singhinderdeep - good to go and it will be good to get more feedback once there are some things to click on :)
