### ISSUE TITLE
Update Resources page and add new "Hosting Options" page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#873]
#### Acceptance Criteria
See [updated wireframe](https://www.figma.com/file/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=5527%3A10607):
- [ ] Update the Resources page
- [ ] Create Hosting Options page and hard-code its content

[Content for new Hosting Options page in Word doc](https://bcgov.sharepoint.com/:w:/t/00109-digital.gov.bc.ca/ETDdkdU79GNCtp8-SgQUfvgBN4bzPNAMW2OJlS4cvlYsTQ?e=IRXEE2)

**Comment by SteveChapmanBCDX** [comment]
Reviewed - closing ticket.
