### ISSUE TITLE
Add OrgBook BC Case Study

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#880]
Add new case study for OrgBook BC

#### Definition of Done
- [x] Implements [new content and layout defined in wireframe](https://www.figma.com/file/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=5759%3A11253) (#913)

**Comment by thegentlemanphysicist** [comment]
List of cards to be tested:

- [ ] community page
- [ ] common components
- [ ] home page
- [ ] case studies
- [ ] blog cards
