### ISSUE TITLE
Redo PR #869 (implement consistent styling across clickable cards)

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#881]
#869 was merged to master but soon afterwards it was discovered that something in it had broken the links between the Common Components cards and detail page.

Submit a new pull request with the same styling changes, but ensure the links are not broken.

**Comment by thegentlemanphysicist** [comment]
Testing notes:  Areas of code that need to be checked for responsiveness styling and functionality:

- [ ] blog cards
- [ ] coco cards
- [ ] digital principles
- [ ] hosting options
- [ ] event cards

**Comment by thegentlemanphysicist** [comment]
Approved
