### ISSUE TITLE
Add health checks to the pods

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#882]
Currently there is no way for the team to be made aware when the site goes down, set up some kind of health check that alerts the team to problems (health checks).  @thegentlemanphysicist has not done this before so it may be a large task

**Comment by thegentlemanphysicist** [comment]
Looking into https://developer.gov.bc.ca/OpenShift-User-Guide-to-Creating-and-Using-a-Sysdig-Team-for-Monitoring
sysdig seems to be the goto

**Comment by thegentlemanphysicist** [comment]
Sysdig is now configured.  
Email alerts are set up for prod. (react and strapi)

TODO
- add alerts for mongo
- get alerts set up for other team members that want them
- add sysdig to the off boarding checklist

**Comment by SteveChapmanBCDX** [comment]
Looks good - closing ticket.
