### ISSUE TITLE
Products and Services page

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#89]
Acceptance Criteria
- Applies design
-Loads correctly and quickly

**Comment by ryleyw** [comment]
Going to add the breadcrumbs to this ticket as well

**Comment by Dianadec** [comment]
Mark - need to look at responsiveness

**Comment by HeatherRemacle** [comment]
Noting that once this page is ready to post, there isn't a link to it on the home page or in the nav yet. We need to consider how this page shows up - I would rather have this page featured on the home page than have the Digital Policy Featured - possible to make this change @ryleyw @patricksimonian @singhinderdeep

**Comment by singhinderdeep** [comment]
@HeatherRemacle Products & Services is featured on the home page as a card, though it's not there in the navbar

**Comment by singhinderdeep** [comment]
@HeatherRemacle Products & Services is featured on the homepage (as per your comment in Figma as you wanted that to be prioritized over the Digital Policy). Guess, @ryleyw missed that
