### ISSUE TITLE
Set up readiness check for pods

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#894]
- Set up a readyness or liveness check for fronend pods before turning them on to external trafic
- Set up an alert for frontend memory usage in sysdig so that we are alerted when memory usage is becoming an issue.

**Comment by thegentlemanphysicist** [comment]
This was tested by deploying both strapi and react independently. then manually redployed.  The readyness checks insure the roll outs don't take the site down on redeployments

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist - Closing ticket.
