### ISSUE TITLE
Spike: investigate frontend memory spike in caddy pods

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#895]
Currently when new pods are created there is  a massive spike in memory usage by the caddy pods our site uses.  Research why this is happening.

**Comment by thegentlemanphysicist** [comment]
step one find logs from pods that crashed sunday morning

**Comment by thegentlemanphysicist** [comment]
Note: attempted to access caddy logs but they are only stored as far back as august first

**Comment by thegentlemanphysicist** [comment]
https://caddy.community/t/caddy-memory-usage-over-300mb-any-clue/2351/9 useful hint

**Comment by thegentlemanphysicist** [comment]
Found a similar problem here https://github.com/caddyserver/caddy/issues/2283 
looking at implementing a timeout
https://caddyserver.com/docs/caddyfile/options

**Comment by thegentlemanphysicist** [comment]
This has branched into a new issue that requires upgrading the caddy server. Please see issue #944

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist - closing spike.  Moving on to substantive issues.
