### ISSUE TITLE
Generate a downloadable version of SWU/CWU past opportunities

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#9]
## User Stories
- As a business, I'd like to know what kinds of opportunities have been offered in the past so I might be able to prepare to apply to some in the future
- As a public servant, I would like to see past opportunities that might relate to one I need to create.
- As a public servant, I would like to know if there is an open code repository associated with the past projects posted.

## Acceptance Criteria
- The information contained in the downloadable file was all previously public
- The file has appropriate meta data (document descriptions) to indicate the source
- The file is formatted such that the headings are obvious and they can be filtered and sorted easily
- The file contains an introduction or readme that describes why the file exists and what it contains.
-

**Comment by mark-a-wilson** [comment]
@parulmishra - I have a lot of history working with the types of people identified in the User Stories above. Can I work with you on this to ensure that whatever solution we deliver will be usable for those people?

**Comment by mark-a-wilson** [comment]
Something we may want to add to this (or reflect in a separate ticket):

Most of the past CWU/SWU opportunities will have a corresponding GitHub repo and Issue like this:
![image.png](https://images.zenhubusercontent.com/5756f782bf93871ccd9c3b53/99773d5e-8905-4a16-9e9c-6472ffc7d082)

Because those auto-generated links back to the opportunity details are now broken, we should find all of those Issues and post a new comment in the thread (or edit the initial comment) to provide instructions about how to retrieve or request information about the archived opportunity.

**Comment by parulmishra** [comment]
Finished exporting the collections in the json format. Will need to confirm with Andrew if we have gotten all the collections: So far we have : Opportunities, Messages, Capabilities, Orgs, Programs, Projects, Proposals and Users.

**Comment by mark-a-wilson** [comment]
@HeatherRemacle - Need to check in with you on your expectations for completion of this. The user stories as written will not be fulfilled by what's been achieved so far.

Talked to @parulmishra this morning and learned that the json format we have to work with cannot easily be converted into records that are complete, readable, searchable, sortable (e.g. like a spreadsheet). 

We at least *have* the data now, so, if we're asked for particular information about past opportunities, we will be able to produce it, though with quite a lot of manual effort. 

Our choices are: 

1. Leave data in json format; if/when people to ask for information, Parul or another developer will have to do the work to extract it from the json — no further effort required (now)
2. Republish the data in a readable format — significant effort required
3. Turn the json into a different format that is complete and readable — significant effort required

**Comment by parulmishra** [comment]
Took the csv files for all the 19 collections from mongodb. @mark-a-wilson let me know if you are interested in formatting it so that it will be usable for the targeted users?

**Comment by parulmishra** [comment]
Moved all the csvs file here: https://teams.microsoft.com/_#/files/digital.gov.bc.ca?threadId=19%3Af78c23767e214080840d1b7e37bd91d7%40thread.tacv2&ctx=channel&context=CWU%2520SWU%2520PastOpportunties&rootfolder=%252Fteams%252F00109-digital.gov.bc.ca%252FShared%2520Documents%252Fdigital.gov.bc.ca%252FDigital%2520Marketplace%252FCWU%2520SWU%2520PastOpportunties

**Comment by mark-a-wilson** [comment]
Just finished opening up the .csv files in spreadsheets to see how usable they'd be to fulfill the user stories — not very.

For the first three user stories, the .csv files will not be of much use. We're pretty much out of luck unless we redeploy the devex app somewhere else just for this purpose.

For the last user story about analyzing data, it will probably be more useful to look at the two spreadsheets I manually kept saved on our LAN under _Accelerator.

**Comment by HeatherRemacle** [comment]
Thanks both. I've adjusted the user stories to match what is feasible currently.

Looking at the projects csv, it would seem possible to extract the short description and name of each of the previously posted projects. There are about 50.

I would be happy with having just that data. 

An added bonus would be to associate a program (organization) with each, and to add a link to the github repo where the code or product was delivered to (given that all these opportunities are for open source). This would require some research and data entry, unless someone can find a fancy way of automating a match between the projects and programs csv files....
