### ISSUE TITLE
[Design] Digital Framework Page

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#90]
# Acceptance Criteria
- Should not be too different from the current site
- Should contemplate how we highlight the updates to the framework (in the future, this might be  featuring an update delivered in a blog with context)

**Comment by singhinderdeep** [comment]
@HeatherRemacle Desktop and mobile versions of the Digital Framework page are done and in For PO to review (mobile has two versions with a slight difference and we can choose one of them).
