### ISSUE TITLE
Digital Framework Page

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#91]
Acceptance Criteria
- Follows Design
- No issues and loads quickly

**Comment by HeatherRemacle** [comment]
Looking great! How are we doing with filling in that image though? I wonder if we could just use the image that we have on the current site.

@singhinderdeep @ryleyw

**Comment by Dianadec** [comment]
Main headers: pull from wordpress site

**Comment by mark-a-wilson** [comment]
@ryleyw - one thing I notice on this page that's still not working is the links to page anchors under **Our Priorities** (I'm looking at https://digital-gov-frontend-pr-147-xdwiwd-dev.pathfinder.gov.bc.ca/digital-framework)

**Comment by ryleyw** [comment]
Moving this to closed and creating a CSS ticket to record needed changes
