### ISSUE TITLE
Update case studies design

### ISSUE THREAD

**Issue by singhinderdeep** [bcgov/digital.gov.bc.ca#913]
#### Description of Task
Update case studies wireframe design to accomodate OrgBook case study

#### Acceptance Criteria (_What does the content need to include to be accepted by the PO?_)
- Conforms to BC Gov Design System.
- Wireframes are annotated for Jon
- Reviewed. by PO

**Comment by singhinderdeep** [comment]
@mark-a-wilson please review

**Comment by mark-a-wilson** [comment]
Looks good -- I'm gonna implement this in #881 -- can you send me the image you used?
