### ISSUE TITLE
Design feature for Digital Government monthly update calls

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#916]
We should feature the **Digital Government monthly update** calls on digital.gov.bc.ca. 

The calls are presented through Slido and are recorded and published on YouTube: https://www.youtube.com/playlist?list=PL9CV_8JBQHiqpIJZd7V4stSAwo4jxfJ9b

Public servants can sign up to receive reminders and calendar invitations to monthly calls through MailChimp:  https://us3.list-manage.com/subscribe?u=2cd8863adab4f39ade7cbee34&id=2f0e1bae04

For now, we could add a simple feature section to the Learning page, although this page is getting a bit unwieldy already. Perhaps we need a News page?

**Comment by mark-a-wilson** [comment]
@SteveChapmanBCDX -- please visit [this link](https://www.figma.com/file/IriR79YsGk0KynDbBLC5EG/DigitalGov?node-id=5860%3A12542
) to view the design for this feature to be added to the homepage. Let me know if you're OK with it, and if you are, will create a dev ticket for Jon to implement.

**Comment by SteveChapmanBCDX** [comment]
@mark-a-wilson - this looks good.  Let's add it to the homepage.

Closing ticket.
