### ISSUE TITLE
Upgrade Caddy server

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#944]
In Spike #895 we found a slow growth in the memory requirements of the frontend app.  We believe that this is caused by the caddy server leaving some connections open indefinitely.  Using timeouts should force these to close.

Adding a block to the caddy file  before everything else in the dc.yaml
```
{
	# Server Options
	servers {
		timeouts {
			read_body 1h
			read_header 1h
			write 1h
			idle 5m
		}
	}
}
4000:
...
```
Should prevent the slow memory leak in the app.  However the current version of the caddy in the imgage created by platform services is 2.1.1, the feature is not available there.  To fix this we can upgrade to version 2.4.5 where this caddyfile is valid.

**Comment by thegentlemanphysicist** [comment]
Approved by Patrick, will merge into develop, then deploy to test.  Test extensively with marketplace integration and finally deploy to prod

**Comment by thegentlemanphysicist** [comment]
To Test:

- [ ] that the upgraded version of caddy is being used in react front end

- [ ] that the deployment functions as expected

- [ ] that markeplace test site is still accessible from digital test site

- [ ] That the app runs without issue all weekend with no crashes

**Comment by thegentlemanphysicist** [comment]
Prod is deployed.  I've put a note in may callendar to check memory consumption in a few weeks to see if it's creeping up again @SteveChapmanBCDX

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @thegentlemanphysicist.  Jonathan has create diary entry to review memory consumption.  Closing ticket.
