### ISSUE TITLE
Autoscaling health check

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#971]
Platform Services is concerned that autoscaling has been misconfigured on multiple projects.  PS recommends that we investigate and fix if the project is misconfigured.

See email from platform services email titled "Misconfigured Horizontal Pod Autoscalers in OpenShift 4 Projects"

**Comment by thegentlemanphysicist** [comment]
It appears that no autoscaling is set up for digital marketplace. (it is not misconfigured, it isn't configured)

**Comment by SteveChapmanBCDX** [comment]
Reviewed with team.

Next steps:
* Does Digital.gov scale, or is usage stable?
* What is immediate cost of implementation?
* What are ongoing costs of maintenance?
