### ISSUE TITLE
Update content of BCDevExchange community page

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital.gov.bc.ca#976]
Ari sent me a list of requests ....

**Comment by mark-a-wilson** [comment]
Ari's requests don't fit the template for a Community page. Need to connect with him to explain. Also awaiting audit and recommendations on all these web properties (including bcdevexchange.org) from Brittany Decker.

**Comment by SteveChapmanBCDX** [comment]
Mark responded to Ari to explain the constraints of this page.  Closing issue for now - will reopen if Ari responds.
