### ISSUE TITLE
As a Digital Team Member, I can access & contribute to the development of digital resources, products and services

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#98]
We really like what New South Wales has does with their digital community to develop resources associated with their design system - https://www.digital.nsw.gov.au/get-involved

**The PO is gathering insights** (user needs and technical requirements) on a set of features that might do the same in BC. In particular, we need to clarify what kinds of resources, products and services might be included in the community, recognizing there are multiple teams working on these resources across government, and they each have their own approaches do developing and managing products.

## Problems
- Resources, products and services that might help someone in their Digital Service Delivery journey can be difficult to interpret for the variety of unique circumstances people are navigating.
- It isn't always clear who to ask for help from (where the knowledge or experience lives)
- It is hard to know if a resource, product or service is current or reliable, or how to offer feedback or insights on how to improve it.

## Hypothesis

If we create a way for the growing digital community to discover and build resources, products and services together, then these things will improve and people will be more capable of applying them.
 
## Outcomes
- People who are starting out on a digital delivery journey will be able to get started more quickly with the best possible digital approaches and tools for their particular context.
- People will contribute their insights and feedback to improve the resources, products and services. 
- Digital services will be delivered with greater speed and quality,

**Comment by mark-a-wilson** [comment]
Closing this stale Epic. Can recreate in much smaller pieces when necessary.
