### ISSUE TITLE
document CPU request and limits confirm they are below 2 and 4 cores for each namespace

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#986]
Platform Services is requiring teams that use Silver Cluster tools namespaces to reduce their resources.

We should document our CPU request and limits to confirm that they are below 2 and 4 cores for the tools namespace.

These were the limits in the build configs, I noticed something different in the dc.yaml files. I need to confirm which is being used.

CPU	requests	limits
React	300m	500m 
Strapi	850m	1500m
Backup	100m	250m
Total Withoud Mongo 1.25	2.25

Mongo dev	80m	100m
Mongo test	500m	1
Monge prod	1	2	

Total with mongo
Mongo dev	1.33	2.35
Mongo test	1.75	3.25
Monge prod	2.25	4.25

**Comment by SteveChapmanBCDX** [comment]
@bdolor to review here and determine next steps.
