### ISSUE TITLE
Delete unneeded config maps in dev namespace

### ISSUE THREAD

**Issue by thegentlemanphysicist** [bcgov/digital.gov.bc.ca#987]
There are about 100 config maps that were not cleaned up when we fixed the clean up script.  

These relics do nothing but take up space, using up our apps quota.  Delete all unused config maps.  The automated clean up scripts will automatically delete new config maps as they become irrelevant.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @bdolor - work complete - closing ticket.
