### ISSUE TITLE
As a BCPS Employee, I can understand the Digital Principles

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/digital.gov.bc.ca#99]
This Epic will lead to a web page that communicates each of the digital principles as they have been released by the Digital Policy Team here: https://github.com/bcgov/digital-principles

This User Story puts the content of this markdown file into a page, to be found here: **Digital.gov.bc.ca/resources/digital-principles**

However, as we develop this content we are also seeking to do some research on UI and tech approaches now to prepare for some future functions:

As these principles are considered version 1, we'd like to consider **how we might update them in future** and to signal those updates. Perhaps we draw directly from the markdown directly in the Policy team's Github, where they intend to make incremental improvements, into a Strapi Content Type. Alternatively, they may wish to transition to authoring in Strapi, if there are not many changes anticipated (i.e. the Github is retired).

If we do this research now and find useful features, these functions could be useful for other content types and user needs, such as a common components library or persona profiles

# Acceptance Criteria:
- Post the Digital Principle content exactly as it is on the Github repo, and confirm the content is displayed as desired by the Policy Team PO (Sara Bose)
- Link back to the github repo where people can see how the principles were developed
- Determine if a Strapi content page can directly reference and render Markdown language from Github, and if BC Gov design system style can be applied appropriately - document the process.

**Comment by Dianadec** [comment]
Heather's explanation: 
Includes page on digital principles, notifications on the digital framework page so that we might highlight a section (modifications to the design) - if there is reference to the platform development. If we have an update on that, that might include some design work - would it be a popup box? different page? drop down? Unique interface options to be able to communicate updates on the framework.

To Clarify: we are building one page and modifying another page

A Design Spike might be needed.

Splitting this card:
1. As a user I can understand the Digital Principles
2. As a user I can see what parts of the Digital Framework have been updated

**Comment by mark-a-wilson** [comment]
From Danny clarifying their wishes about publishing the principles:

> "I think you are good to use the content on GitHub for the sake of consistency. I’m trying to track down a visual of the 10 principles to make the page more engaging. As soon as I find it I’ll send to you.
>  
> As per your suggestion below, I agree that this should be posted when the new site is launched.
>  
> It would be prudent to add how the principles were and continue to be developed “in the open” and continue to point them to the GitHub repo if they have comments. If you feel an explanation of how to file an issue is required I think that’s useful as many people don’t have experience of the platform. However, I’d suggest you also add an email address for people that are not comfortable using GitHub."

**Comment by thegentlemanphysicist** [comment]
Link is here: https://digital-gov-frontend-pr-196-xdwiwd-dev.pathfinder.gov.bc.ca/

**Comment by mark-a-wilson** [comment]
That width is great - very readable!

**Comment by thegentlemanphysicist** [comment]
This is building a deployment, may take a few minutes.

**Comment by thegentlemanphysicist** [comment]
This is in code review right now,
